-- ============================================================================
-- mod-tcg-vendors  --  migration: Tyrael's Hilt reward_group key rename
--
-- Tyrael's Hilt moved out of the promo vendor catalogue into the dedicated
-- Worldwide Invitational vendors (npc_tyraels_vendor, entries 29093/29095).
-- As part of that move the reward group key was renamed:
--
--     PROMO_TYRAELS_HILT  ->  WWI_TYRAELS_HILT
--
-- Codes generated by an older tools/generate_codes.py were written with the old
-- key, and the server resolves codes via REWARD_GROUPS in
-- src/mod_tcg_vendors.cpp.  An unknown key is refused at redemption time with
-- "Your code is valid but references an unknown reward", so those rows must be
-- renamed here or they are permanently unusable.
--
-- Idempotent: a second run matches zero rows.
--
-- Filename note: the "zzz_" prefix is required.  The update fetcher sorts
-- SQL files by basename alone (UpdateFetcher.cpp PathCompare) and ignores the
-- base/ vs updates/ distinction, and it invokes mysql without --force, so a
-- statement touching a not-yet-created table aborts server startup.  This file
-- must therefore sort after create_tcg_codes_table.sql.
-- ============================================================================
UPDATE `account_tcg_codes`
   SET `reward_group` = 'WWI_TYRAELS_HILT'
 WHERE `reward_group` = 'PROMO_TYRAELS_HILT';
