-- ============================================================
-- mod-tcg-vendors  --  Redemption Code Batch
-- Generated : 2026-10-03 02:30:18 UTC
-- Groups    : 70
-- Total     : 1400 codes
-- Apply to  : characters database
-- ============================================================

-- TCG_TABARD_OF_FLAME  (Tabard of Flame)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('W8R8-TKAQ-QYT9-6MJP', 'TCG_TABARD_OF_FLAME'),
    ('P2JY-DPX6-GH72-6J8K', 'TCG_TABARD_OF_FLAME'),
    ('KNQD-RGU3-2H8K-VEEF', 'TCG_TABARD_OF_FLAME'),
    ('QAP7-ZGN5-XTNW-WWF8', 'TCG_TABARD_OF_FLAME'),
    ('GNV3-7CFT-PCEN-6FFZ', 'TCG_TABARD_OF_FLAME'),
    ('JGYR-MF34-PYBE-GHDX', 'TCG_TABARD_OF_FLAME'),
    ('CMWJ-KA34-SPE8-E4PQ', 'TCG_TABARD_OF_FLAME'),
    ('5ZNN-9B4W-NB3C-N84F', 'TCG_TABARD_OF_FLAME'),
    ('5Z4P-RHSS-6T48-ZYHF', 'TCG_TABARD_OF_FLAME'),
    ('V3ZX-XBA5-9M88-TGJR', 'TCG_TABARD_OF_FLAME'),
    ('32E3-EV5E-NAGN-KYKA', 'TCG_TABARD_OF_FLAME'),
    ('WSMH-TZXV-FPZN-HHCQ', 'TCG_TABARD_OF_FLAME'),
    ('RFNT-DU82-H3N5-3NQP', 'TCG_TABARD_OF_FLAME'),
    ('VWFV-RTGQ-8K58-SPAZ', 'TCG_TABARD_OF_FLAME'),
    ('HNT6-SKGM-4AF7-NC6C', 'TCG_TABARD_OF_FLAME'),
    ('DQ37-KJA5-KBDW-M93D', 'TCG_TABARD_OF_FLAME'),
    ('GDAE-WU6C-VK4J-EVYH', 'TCG_TABARD_OF_FLAME'),
    ('DQNU-BEAQ-TW8E-UF9N', 'TCG_TABARD_OF_FLAME'),
    ('FJK9-77JG-H7TJ-3MWS', 'TCG_TABARD_OF_FLAME'),
    ('TA3T-E9UH-ZWDU-WC9E', 'TCG_TABARD_OF_FLAME');

-- TCG_HIPPOGRYPH_HATCHLING  (Hippogryph Hatchling)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('VHXN-9MJC-NFT6-Z769', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('WPQ5-PMKE-RYF6-B559', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('XNR8-A2ZB-XNVU-GSR8', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('8ZW9-QZNT-7YAE-PQQZ', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('SCBX-M9EN-JAD5-9NGF', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('9D69-KH5R-Q8CF-KK38', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('F89B-EBPF-Y9DW-DSGS', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('J2T8-FFBJ-KUUN-E5QZ', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('P3CW-CNNF-P7QW-62PR', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('VHK4-VZ6H-KGBA-APNR', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('N24K-T7VM-FMMH-ZGTA', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('JAEQ-G5BG-XGJV-76J2', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('EP85-99HE-C465-PTJ3', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('TTGF-BFGV-EH5M-6W6D', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('6WVS-NDRS-HY5G-ZR62', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('WEUY-TRBR-CBCP-7KPU', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('X7XQ-PKZV-Y3PD-6PG7', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('RHD7-TS78-REVZ-7ZUJ', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('XWTU-VPWF-ZRJN-73EB', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('TDTM-KUFA-EJV7-EUCK', 'TCG_HIPPOGRYPH_HATCHLING');

-- TCG_RIDING_TURTLE  (Riding Turtle)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('4MUD-5649-94YU-6BYR', 'TCG_RIDING_TURTLE'),
    ('7G3F-RSM7-ZHPV-GJHA', 'TCG_RIDING_TURTLE'),
    ('WVRX-JRC3-8RGU-CP8D', 'TCG_RIDING_TURTLE'),
    ('TFU9-TZ2U-ZMRV-ATBY', 'TCG_RIDING_TURTLE'),
    ('3WMF-92WF-HDPV-VZEV', 'TCG_RIDING_TURTLE'),
    ('3DNE-2RRJ-UM3U-A9VS', 'TCG_RIDING_TURTLE'),
    ('BYMP-N6P3-V9C5-38U4', 'TCG_RIDING_TURTLE'),
    ('7XBK-EEYC-DKMF-C9MV', 'TCG_RIDING_TURTLE'),
    ('N88Z-GCUE-6QAB-6N9F', 'TCG_RIDING_TURTLE'),
    ('2XX2-C5A4-T592-3UYZ', 'TCG_RIDING_TURTLE'),
    ('99N7-2ZZ4-RD5W-MXZD', 'TCG_RIDING_TURTLE'),
    ('Y6VB-E4RD-9G4K-C4D7', 'TCG_RIDING_TURTLE'),
    ('5356-QJC9-NMMZ-GG3N', 'TCG_RIDING_TURTLE'),
    ('BSQ4-DSYJ-6TKS-JG5D', 'TCG_RIDING_TURTLE'),
    ('XCGM-NRXF-M726-DTDE', 'TCG_RIDING_TURTLE'),
    ('SREW-C374-4ZP2-QJRA', 'TCG_RIDING_TURTLE'),
    ('WHZS-KEVD-U72Q-MP8A', 'TCG_RIDING_TURTLE'),
    ('Y7KD-7RXF-SCW8-TMY5', 'TCG_RIDING_TURTLE'),
    ('BH8M-7PGC-5QS6-MWX3', 'TCG_RIDING_TURTLE'),
    ('MRDU-JUDH-VD9F-XF2M', 'TCG_RIDING_TURTLE');

-- TCG_PICNIC_BASKET  (Picnic Basket)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('HX5A-C2KA-BYBT-3R5S', 'TCG_PICNIC_BASKET'),
    ('5SSS-H3QZ-QXB4-J2D8', 'TCG_PICNIC_BASKET'),
    ('W54A-CNSQ-PV7U-8TE6', 'TCG_PICNIC_BASKET'),
    ('T944-M8UG-X9WE-HVH7', 'TCG_PICNIC_BASKET'),
    ('9EAY-M3S3-3PTN-Y26Y', 'TCG_PICNIC_BASKET'),
    ('7RMX-Y7GF-5BY8-3KJN', 'TCG_PICNIC_BASKET'),
    ('MR6G-Z2JK-9HUV-N8PW', 'TCG_PICNIC_BASKET'),
    ('9KDX-28GS-D83C-6TZP', 'TCG_PICNIC_BASKET'),
    ('5CU2-PMCX-GTR4-M89N', 'TCG_PICNIC_BASKET'),
    ('2XPE-FTAX-Q857-ZGAR', 'TCG_PICNIC_BASKET'),
    ('VSP2-8C47-9N6B-J7Y2', 'TCG_PICNIC_BASKET'),
    ('RFS5-WV5E-A9NS-6MS5', 'TCG_PICNIC_BASKET'),
    ('STSM-CZBV-5S7X-434A', 'TCG_PICNIC_BASKET'),
    ('TXGV-P3ZX-KB3U-PEVF', 'TCG_PICNIC_BASKET'),
    ('VZ7K-3SPQ-UN4A-6VX6', 'TCG_PICNIC_BASKET'),
    ('BG8V-HK33-3TDN-66NS', 'TCG_PICNIC_BASKET'),
    ('CGFR-6MRT-XH58-GKKK', 'TCG_PICNIC_BASKET'),
    ('GZ3N-5JQ8-2JGZ-D7XR', 'TCG_PICNIC_BASKET'),
    ('3YBY-4VT2-2YV7-RGJ9', 'TCG_PICNIC_BASKET'),
    ('P568-R3US-HAU7-8YE2', 'TCG_PICNIC_BASKET');

-- TCG_BANANA_CHARM  (Banana Charm)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('3BJS-982V-8AJA-YM6K', 'TCG_BANANA_CHARM'),
    ('JS9S-U6FD-S3A5-DZYW', 'TCG_BANANA_CHARM'),
    ('374R-V7V7-X2C6-6SF8', 'TCG_BANANA_CHARM'),
    ('J46R-SUP8-KT7N-HXUB', 'TCG_BANANA_CHARM'),
    ('KER8-9EPP-9ACS-6JE9', 'TCG_BANANA_CHARM'),
    ('SMG5-BAZA-C48V-VE3P', 'TCG_BANANA_CHARM'),
    ('Y9WM-3XFJ-BRBT-DAES', 'TCG_BANANA_CHARM'),
    ('ME37-YDXQ-YRPF-A67D', 'TCG_BANANA_CHARM'),
    ('5ZA6-E435-UMQ9-DJAW', 'TCG_BANANA_CHARM'),
    ('DG35-2U8R-HQAT-WGZG', 'TCG_BANANA_CHARM'),
    ('ZEDB-P5CY-K67J-22Z2', 'TCG_BANANA_CHARM'),
    ('85ND-MGCW-C994-2BVB', 'TCG_BANANA_CHARM'),
    ('NXEZ-3CMB-BZFB-S459', 'TCG_BANANA_CHARM'),
    ('PGME-RYJ9-TRRW-QC5N', 'TCG_BANANA_CHARM'),
    ('ATPF-EQCY-3QSV-HVRW', 'TCG_BANANA_CHARM'),
    ('88W7-R3K3-A6DB-T9GA', 'TCG_BANANA_CHARM'),
    ('TYE5-79VR-TSJA-KFKV', 'TCG_BANANA_CHARM'),
    ('FHF8-RJZ5-EQ69-TE6V', 'TCG_BANANA_CHARM'),
    ('UB82-ZVHN-UTSW-3QMG', 'TCG_BANANA_CHARM'),
    ('Y74D-V5Q5-4AQT-KZVV', 'TCG_BANANA_CHARM');

-- TCG_IMP_IN_A_BALL  (Imp in a Ball)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('HSH4-VYZ2-QPHC-ZMKE', 'TCG_IMP_IN_A_BALL'),
    ('BCKB-KS3J-7U2E-9YJ5', 'TCG_IMP_IN_A_BALL'),
    ('VSPA-62VZ-VGES-F99G', 'TCG_IMP_IN_A_BALL'),
    ('ESSF-32M3-QM92-GWMW', 'TCG_IMP_IN_A_BALL'),
    ('C8FD-2GDS-4GTQ-7XAA', 'TCG_IMP_IN_A_BALL'),
    ('JCGQ-FVYP-MFE2-7VFF', 'TCG_IMP_IN_A_BALL'),
    ('M75P-V7GS-6VSJ-M6AF', 'TCG_IMP_IN_A_BALL'),
    ('RCQM-GKWH-NM5N-XU9V', 'TCG_IMP_IN_A_BALL'),
    ('NXYM-DPYT-DCXP-F6K5', 'TCG_IMP_IN_A_BALL'),
    ('5HF3-E2SJ-X2DR-9DAH', 'TCG_IMP_IN_A_BALL'),
    ('YCB4-FBVJ-APR4-X9RQ', 'TCG_IMP_IN_A_BALL'),
    ('WKAA-NUY9-VQDA-AFHH', 'TCG_IMP_IN_A_BALL'),
    ('WT38-K2YF-UQ2E-DSWA', 'TCG_IMP_IN_A_BALL'),
    ('ANNP-49CY-B75B-28GG', 'TCG_IMP_IN_A_BALL'),
    ('CK83-GZR9-A7Z2-XHD9', 'TCG_IMP_IN_A_BALL'),
    ('2QSK-39AY-XKFE-HCAB', 'TCG_IMP_IN_A_BALL'),
    ('TM4W-UDNW-AD6A-DNJ7', 'TCG_IMP_IN_A_BALL'),
    ('FNW7-BEP4-YJYP-V9MC', 'TCG_IMP_IN_A_BALL'),
    ('J7MM-ZK6J-7UC6-7RJV', 'TCG_IMP_IN_A_BALL'),
    ('YBGW-CW5F-AMDT-49KX', 'TCG_IMP_IN_A_BALL');

-- TCG_GOBLIN_GUMBO_KETTLE  (Goblin Gumbo Kettle)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('A25X-7XQF-EZ9Q-YGT8', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('BUEB-KXJD-A2UK-7WH9', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('HBVR-W9CT-7D5U-5MMA', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('HT9K-4Z3K-2GRG-J9GZ', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('XCNU-3UNX-ZZA8-EZM4', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('RM5E-S58T-ZDN3-G9DW', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('7WU3-QSVJ-TDXQ-25VC', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('WJS8-WGXP-MVBR-M5JG', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('YW6R-TN8X-UBCG-3D5Z', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('ABEV-WSZG-6NBP-W282', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('HZAJ-GAXX-HH5R-EQKD', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('HHVC-5CMG-93JP-PPZE', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('FR6F-ARWT-YHJS-DD2Y', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('36JN-4HHX-E5E9-EZ47', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('64FM-E7GS-NZJY-ZNXH', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('BXVR-SQK7-99QV-A99J', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('JJMX-74UH-J75P-7NCA', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('S2HV-BVEJ-2S9D-9M3H', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('ZBG3-DPJT-KNCM-8UEB', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('PPM7-GEFG-BFBJ-WQTH', 'TCG_GOBLIN_GUMBO_KETTLE');

-- TCG_FISHING_CHAIR  (Fishing Chair)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('GG4D-JMGV-54K4-GFNM', 'TCG_FISHING_CHAIR'),
    ('XD4C-4PPR-FGYT-TA2G', 'TCG_FISHING_CHAIR'),
    ('MVBT-VRA7-FMWS-2WJG', 'TCG_FISHING_CHAIR'),
    ('JBWY-XBY2-CHKE-PV7S', 'TCG_FISHING_CHAIR'),
    ('MD8S-QNPS-WRTE-6CS9', 'TCG_FISHING_CHAIR'),
    ('FMN2-HN6A-X55H-FSHM', 'TCG_FISHING_CHAIR'),
    ('WDTK-UQZS-MVNV-R543', 'TCG_FISHING_CHAIR'),
    ('6JT9-CTKH-GA4Z-T5YP', 'TCG_FISHING_CHAIR'),
    ('AQFF-33RK-K8WN-9K2W', 'TCG_FISHING_CHAIR'),
    ('DSTT-46PT-6EME-UFC9', 'TCG_FISHING_CHAIR'),
    ('QN5M-KJHV-9T26-4TUR', 'TCG_FISHING_CHAIR'),
    ('P7K3-U4TW-24K6-7MNE', 'TCG_FISHING_CHAIR'),
    ('X7NW-7NYS-PZSD-MFE3', 'TCG_FISHING_CHAIR'),
    ('ABV8-8NQG-UHB6-6A93', 'TCG_FISHING_CHAIR'),
    ('7BH2-FZHN-G9UX-GD5C', 'TCG_FISHING_CHAIR'),
    ('MMNE-8PHH-UQSG-T5MG', 'TCG_FISHING_CHAIR'),
    ('ZY9W-4HUT-G6Z7-Y29R', 'TCG_FISHING_CHAIR'),
    ('JY83-6P68-YVK6-DGKK', 'TCG_FISHING_CHAIR'),
    ('EZEX-57N4-UMMF-64AA', 'TCG_FISHING_CHAIR'),
    ('9P9B-Q5XG-QT82-NWR7', 'TCG_FISHING_CHAIR');

-- TCG_SPECTRAL_TIGER  (Reins of the Spectral Tiger (both variants))
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('D3VS-3NGD-GZW4-GYGJ', 'TCG_SPECTRAL_TIGER'),
    ('E9EN-SRDC-CXKD-NC3T', 'TCG_SPECTRAL_TIGER'),
    ('YXZU-P7AM-559R-F4WV', 'TCG_SPECTRAL_TIGER'),
    ('B7T6-JRJU-P8CJ-B4JJ', 'TCG_SPECTRAL_TIGER'),
    ('SJM8-V9HS-A926-XMAQ', 'TCG_SPECTRAL_TIGER'),
    ('7YAA-74RB-DBBK-MYFN', 'TCG_SPECTRAL_TIGER'),
    ('QXM6-RGYM-DF8R-NR66', 'TCG_SPECTRAL_TIGER'),
    ('JMQ9-J4J7-U5VM-FK6C', 'TCG_SPECTRAL_TIGER'),
    ('PRQH-RVV5-DCYE-NF63', 'TCG_SPECTRAL_TIGER'),
    ('QJXX-QZJC-X5EP-J65G', 'TCG_SPECTRAL_TIGER'),
    ('XC3R-VD9E-DVBE-HC9J', 'TCG_SPECTRAL_TIGER'),
    ('XQVG-3VF7-Q2GR-RJM7', 'TCG_SPECTRAL_TIGER'),
    ('A6R9-2EK2-5BUR-KEBW', 'TCG_SPECTRAL_TIGER'),
    ('Z3NE-UKXR-EWV7-W855', 'TCG_SPECTRAL_TIGER'),
    ('RN7K-4HHW-PGFD-UU88', 'TCG_SPECTRAL_TIGER'),
    ('963C-QVYT-JEAK-Y4R6', 'TCG_SPECTRAL_TIGER'),
    ('4W2Q-AGY2-Y63B-5USV', 'TCG_SPECTRAL_TIGER'),
    ('6KMD-VCQD-ZW8U-72Z3', 'TCG_SPECTRAL_TIGER'),
    ('3R83-X77S-G27J-CC6Z', 'TCG_SPECTRAL_TIGER'),
    ('JGFA-FTES-MGVJ-9ZYZ', 'TCG_SPECTRAL_TIGER');

-- TCG_PAPER_FLYING_MACHINE  (Paper Flying Machine Kit)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('T3DV-WT7V-9J4C-YC4J', 'TCG_PAPER_FLYING_MACHINE'),
    ('6QCK-3MV9-7DCT-2TE8', 'TCG_PAPER_FLYING_MACHINE'),
    ('86V7-MGHC-NHCN-GSF2', 'TCG_PAPER_FLYING_MACHINE'),
    ('GKB5-XX3E-2Y6T-GXXS', 'TCG_PAPER_FLYING_MACHINE'),
    ('2STD-H7GE-MSYC-5FDZ', 'TCG_PAPER_FLYING_MACHINE'),
    ('UXCM-W6PS-WK6W-GYCQ', 'TCG_PAPER_FLYING_MACHINE'),
    ('Z9AP-6X7A-HH7K-RDXE', 'TCG_PAPER_FLYING_MACHINE'),
    ('FJVR-TPMM-4QMS-KB5C', 'TCG_PAPER_FLYING_MACHINE'),
    ('MWCJ-8RDT-XTAV-5GU3', 'TCG_PAPER_FLYING_MACHINE'),
    ('XETP-WQFG-ZYCH-P5FZ', 'TCG_PAPER_FLYING_MACHINE'),
    ('VR29-K8K2-ZJKU-2P95', 'TCG_PAPER_FLYING_MACHINE'),
    ('2ART-BE48-G9Q5-ED5H', 'TCG_PAPER_FLYING_MACHINE'),
    ('UYFC-F8SG-P7F3-RJQA', 'TCG_PAPER_FLYING_MACHINE'),
    ('YZGY-Z99K-D49P-7BHK', 'TCG_PAPER_FLYING_MACHINE'),
    ('Q3PV-AA85-YWBC-QEQ5', 'TCG_PAPER_FLYING_MACHINE'),
    ('NKAP-EDZY-9BNJ-HWZT', 'TCG_PAPER_FLYING_MACHINE'),
    ('BKBM-CYZP-VHKS-RKJ8', 'TCG_PAPER_FLYING_MACHINE'),
    ('ZN9Q-BVMR-H5KN-7JM7', 'TCG_PAPER_FLYING_MACHINE'),
    ('PFD2-86TQ-7MCP-XWAE', 'TCG_PAPER_FLYING_MACHINE'),
    ('HGCU-SWG5-MP26-UBXF', 'TCG_PAPER_FLYING_MACHINE');

-- TCG_ROCKET_CHICKEN  (Rocket Chicken)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('NWAC-CTRH-EFRP-26P9', 'TCG_ROCKET_CHICKEN'),
    ('6QKD-4PAZ-SUVE-GSZR', 'TCG_ROCKET_CHICKEN'),
    ('YFAA-GQ6R-UQBE-UE87', 'TCG_ROCKET_CHICKEN'),
    ('3FPX-JDT8-82F5-4UT4', 'TCG_ROCKET_CHICKEN'),
    ('S53H-GCBU-8TAN-QX5K', 'TCG_ROCKET_CHICKEN'),
    ('ZZKD-EGZX-AYHH-UJJN', 'TCG_ROCKET_CHICKEN'),
    ('X3PZ-C6EG-PV72-J77U', 'TCG_ROCKET_CHICKEN'),
    ('YE33-FFQU-8AY7-PSJ6', 'TCG_ROCKET_CHICKEN'),
    ('HSNJ-74NA-T4BV-27KA', 'TCG_ROCKET_CHICKEN'),
    ('PRAW-JTDH-NNTM-DWXX', 'TCG_ROCKET_CHICKEN'),
    ('6HEJ-XV9G-XUPU-ZEXA', 'TCG_ROCKET_CHICKEN'),
    ('DYV8-6KZC-SAG8-PSSY', 'TCG_ROCKET_CHICKEN'),
    ('VQRD-6WUG-HUNZ-9M3P', 'TCG_ROCKET_CHICKEN'),
    ('4KXW-7W5J-F37R-EEVZ', 'TCG_ROCKET_CHICKEN'),
    ('GA2X-ERNM-PCDU-KQBC', 'TCG_ROCKET_CHICKEN'),
    ('MUH2-4G8R-JKGY-ZC8V', 'TCG_ROCKET_CHICKEN'),
    ('K28W-7URS-M5DC-SQEQ', 'TCG_ROCKET_CHICKEN'),
    ('TEB6-UA8A-DW76-BMAR', 'TCG_ROCKET_CHICKEN'),
    ('JSVZ-BMAK-VARZ-ZWR6', 'TCG_ROCKET_CHICKEN'),
    ('FYU5-7NCV-6WZS-JM8R', 'TCG_ROCKET_CHICKEN');

-- TCG_DRAGON_KITE  (Dragon Kite)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('JN24-BR65-EY9F-MTHN', 'TCG_DRAGON_KITE'),
    ('T94H-AWVV-R2MH-2GXT', 'TCG_DRAGON_KITE'),
    ('CKZE-RDSF-KRMB-ET8A', 'TCG_DRAGON_KITE'),
    ('4J7E-SMT8-SPTJ-BRMV', 'TCG_DRAGON_KITE'),
    ('5PWV-8XGZ-V5EN-KXZA', 'TCG_DRAGON_KITE'),
    ('M7F6-4TF5-EM8Z-E6ZU', 'TCG_DRAGON_KITE'),
    ('RKQG-PB8V-XW32-ZGYJ', 'TCG_DRAGON_KITE'),
    ('R9ZZ-J6GN-4QF4-F82G', 'TCG_DRAGON_KITE'),
    ('9NAW-D83U-AY8A-KQGD', 'TCG_DRAGON_KITE'),
    ('24CX-TV8J-5UZ9-2T5W', 'TCG_DRAGON_KITE'),
    ('Y7FS-C6QF-5256-KBG4', 'TCG_DRAGON_KITE'),
    ('S8Z9-2KKM-GXTP-6E2B', 'TCG_DRAGON_KITE'),
    ('YG7T-KF6T-A5QG-5JFE', 'TCG_DRAGON_KITE'),
    ('NKCQ-XZ8G-XGK4-3GQA', 'TCG_DRAGON_KITE'),
    ('S56K-88F6-QHKC-2HDF', 'TCG_DRAGON_KITE'),
    ('CD4Q-DUMY-7US8-T6SM', 'TCG_DRAGON_KITE'),
    ('8Q8Q-GSG3-2JHV-TZ6X', 'TCG_DRAGON_KITE'),
    ('4XQ4-58UB-QUAU-4ZEY', 'TCG_DRAGON_KITE'),
    ('8XN5-N537-MP36-UZD5', 'TCG_DRAGON_KITE'),
    ('VTDV-WKHX-WYVW-M2GY', 'TCG_DRAGON_KITE');

-- TCG_X51_NETHER_ROCKET  (X-51 Nether-Rocket (both variants))
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('ACRN-DU95-BTGN-9V5Q', 'TCG_X51_NETHER_ROCKET'),
    ('GHAZ-6BHP-8BZ4-J6BJ', 'TCG_X51_NETHER_ROCKET'),
    ('JXMA-EHWM-JDMX-FDE5', 'TCG_X51_NETHER_ROCKET'),
    ('XJJZ-SN72-FQ5Q-7MVB', 'TCG_X51_NETHER_ROCKET'),
    ('3AVP-P2P9-BHP5-XXFD', 'TCG_X51_NETHER_ROCKET'),
    ('P84G-VTS4-Y3FY-SSH2', 'TCG_X51_NETHER_ROCKET'),
    ('5AZD-JABU-QG3M-TNAJ', 'TCG_X51_NETHER_ROCKET'),
    ('GWEE-3RVV-T3HW-HNKD', 'TCG_X51_NETHER_ROCKET'),
    ('EDG8-SJ9F-QNMY-RT6W', 'TCG_X51_NETHER_ROCKET'),
    ('QN8Y-88XB-CKZG-VZDY', 'TCG_X51_NETHER_ROCKET'),
    ('CBRN-SA7Q-K2KM-ZS8K', 'TCG_X51_NETHER_ROCKET'),
    ('QH5Y-GBDJ-RABT-T647', 'TCG_X51_NETHER_ROCKET'),
    ('KWDG-PSR3-YNJ8-DKH9', 'TCG_X51_NETHER_ROCKET'),
    ('849T-JYD6-29KJ-2TH3', 'TCG_X51_NETHER_ROCKET'),
    ('NZ7N-TF3W-CNAG-YVMK', 'TCG_X51_NETHER_ROCKET'),
    ('6N4U-PH3C-K6VU-UP98', 'TCG_X51_NETHER_ROCKET'),
    ('D65V-UKD5-UAUR-CW2X', 'TCG_X51_NETHER_ROCKET'),
    ('AYFP-CANM-B6HJ-WR3Y', 'TCG_X51_NETHER_ROCKET'),
    ('A3GV-U82Q-TQBQ-77RH', 'TCG_X51_NETHER_ROCKET'),
    ('UE2R-KHJ7-3DBA-SEDX', 'TCG_X51_NETHER_ROCKET');

-- TCG_PET_BISCUIT  (Papa Hummel's Old-Fashioned Pet Biscuit)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('SQE5-ETYV-UGJV-7BH6', 'TCG_PET_BISCUIT'),
    ('4MND-5X9J-PME9-52JV', 'TCG_PET_BISCUIT'),
    ('4B8Z-4RFJ-RUUR-CVMB', 'TCG_PET_BISCUIT'),
    ('Z3YM-6EQQ-GRYS-PPSW', 'TCG_PET_BISCUIT'),
    ('3CMC-MJ28-4KTS-F2HT', 'TCG_PET_BISCUIT'),
    ('QQC5-P5A7-YPJQ-HHD7', 'TCG_PET_BISCUIT'),
    ('7VAG-67D4-ANDC-MYAG', 'TCG_PET_BISCUIT'),
    ('98CF-5GCG-88K8-YDDX', 'TCG_PET_BISCUIT'),
    ('DW8F-Z4VG-VF7T-J7QX', 'TCG_PET_BISCUIT'),
    ('GD5R-NJKV-7SYW-3RVF', 'TCG_PET_BISCUIT'),
    ('UVWZ-M9E5-6CXN-K5J4', 'TCG_PET_BISCUIT'),
    ('72K7-5JFF-6NMH-VTAN', 'TCG_PET_BISCUIT'),
    ('P8VF-RW4N-8VKN-HMFG', 'TCG_PET_BISCUIT'),
    ('EY4Q-9K8W-NAMM-WFCX', 'TCG_PET_BISCUIT'),
    ('5MQE-7KMZ-27AJ-SHPH', 'TCG_PET_BISCUIT'),
    ('QT6J-5TTF-KM3Z-PY29', 'TCG_PET_BISCUIT'),
    ('ZKQT-JVXU-6RBE-UT9P', 'TCG_PET_BISCUIT'),
    ('DRFX-CYFV-UGWU-PCK8', 'TCG_PET_BISCUIT'),
    ('ET8N-6S44-CYRF-3VZD', 'TCG_PET_BISCUIT'),
    ('YK2W-NB3Q-GQ65-GAMT', 'TCG_PET_BISCUIT');

-- TCG_GOBLIN_WEATHER_MACHINE  (Goblin Weather Machine - Prototype 01-B)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('Y9AE-P2AN-SFUE-ME9U', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('8XM7-EA5E-V3YS-A4DC', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('T35T-WFD6-JKQW-6N7B', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('TQEA-HCJA-K3JQ-EUYY', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('3256-5QC7-HQ7C-2PFT', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('94QW-YFXW-4YDR-NCB6', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('5BWU-P6B3-UH7X-J4U8', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('UUM8-3ZRV-9PQ4-G2JE', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('B3BU-95B3-KB4P-9PPB', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('TKS9-C75X-GTFK-5DEN', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('87BT-4YSZ-USQR-WMUT', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('PY35-EBSS-XWX6-AMNM', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('MRBT-AGEB-6XYM-54FJ', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('NCGC-8VSM-WHWP-SZRZ', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('83EE-8CHS-93MM-SRPC', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('YXPA-6W34-7B3T-NPB4', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('ED5U-MS6Y-APZM-PPHM', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('DRPP-2P5H-VRKP-G2GR', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('C4XV-2DVH-YFXY-FYKS', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('N4ZE-UHCQ-GDW2-AQFA', 'TCG_GOBLIN_WEATHER_MACHINE');

-- TCG_PATH_OF_ILLIDAN  (Path of Illidan)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('WY24-H8Y3-U5XM-R8PQ', 'TCG_PATH_OF_ILLIDAN'),
    ('4USX-T4QY-JG66-5YD2', 'TCG_PATH_OF_ILLIDAN'),
    ('N95S-6XYF-C3TW-R7M6', 'TCG_PATH_OF_ILLIDAN'),
    ('WTPS-SGKK-2C7H-7FBH', 'TCG_PATH_OF_ILLIDAN'),
    ('FY4J-2K8C-B5VE-ZZWM', 'TCG_PATH_OF_ILLIDAN'),
    ('VW6B-BM78-Z2F9-S27K', 'TCG_PATH_OF_ILLIDAN'),
    ('PHGU-MGD9-GTQ9-53EK', 'TCG_PATH_OF_ILLIDAN'),
    ('PXJE-7DF9-GY5N-5HYR', 'TCG_PATH_OF_ILLIDAN'),
    ('VCJS-KUCE-PUG5-PENY', 'TCG_PATH_OF_ILLIDAN'),
    ('RN4E-47JH-NBZ6-5DAP', 'TCG_PATH_OF_ILLIDAN'),
    ('BQY9-3YUJ-UCAH-BAYK', 'TCG_PATH_OF_ILLIDAN'),
    ('DA5T-RZVQ-ZWYF-6GHM', 'TCG_PATH_OF_ILLIDAN'),
    ('MWWJ-U8NX-JM88-H88B', 'TCG_PATH_OF_ILLIDAN'),
    ('ESZC-7T3S-Y52W-3VPF', 'TCG_PATH_OF_ILLIDAN'),
    ('MXWR-Y5CV-PJJS-7FY2', 'TCG_PATH_OF_ILLIDAN'),
    ('HKAS-DP4H-KMRC-AD3T', 'TCG_PATH_OF_ILLIDAN'),
    ('3BWV-78R5-9DFJ-MJHW', 'TCG_PATH_OF_ILLIDAN'),
    ('USJG-4WYN-2QZT-FVVE', 'TCG_PATH_OF_ILLIDAN'),
    ('XQNM-2JTE-US9E-X5WD', 'TCG_PATH_OF_ILLIDAN'),
    ('3Y82-DZSE-GJD7-Q2CH', 'TCG_PATH_OF_ILLIDAN');

-- TCG_DISCO  (D.I.S.C.O.)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('VUZA-NHSZ-GSXR-DQFS', 'TCG_DISCO'),
    ('WYUU-G846-D496-PEWY', 'TCG_DISCO'),
    ('R99E-DFW5-G9K8-EESR', 'TCG_DISCO'),
    ('DTMT-W6EU-W97V-36B8', 'TCG_DISCO'),
    ('D2RP-W74X-VQUA-VXJ4', 'TCG_DISCO'),
    ('DWJZ-J5WK-7NCU-9SX4', 'TCG_DISCO'),
    ('RC97-E2X6-QE8H-XWHD', 'TCG_DISCO'),
    ('2B4R-Q9J3-VNQG-RXQS', 'TCG_DISCO'),
    ('JVFK-7YAP-PUTD-RV3R', 'TCG_DISCO'),
    ('PHJA-9XGQ-F5YX-CNM8', 'TCG_DISCO'),
    ('GJB6-6VSQ-QR7E-BWWW', 'TCG_DISCO'),
    ('US8G-U5U7-WMMG-ECVE', 'TCG_DISCO'),
    ('DRCF-9R6P-GWUU-9TRK', 'TCG_DISCO'),
    ('GHPN-DJBP-438C-B2ZS', 'TCG_DISCO'),
    ('9DDE-P4DA-CWT8-EZJR', 'TCG_DISCO'),
    ('K39D-BWC7-694N-9JR9', 'TCG_DISCO'),
    ('7DT5-JPSM-YB5D-AFTW', 'TCG_DISCO'),
    ('GGDA-QJPX-NJWX-8AP7', 'TCG_DISCO'),
    ('MN2S-E4FG-37UB-QZEC', 'TCG_DISCO'),
    ('TYKK-44JQ-ZTND-YDUB', 'TCG_DISCO');

-- TCG_SOUL_TRADER_BEACON  (Soul-Trader Beacon)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('GPVA-Y2KB-385E-ZQ97', 'TCG_SOUL_TRADER_BEACON'),
    ('PJSW-KS64-9YHU-ZYKT', 'TCG_SOUL_TRADER_BEACON'),
    ('TN3C-2575-YH8M-7P97', 'TCG_SOUL_TRADER_BEACON'),
    ('9E8M-NCA4-MHFT-2P52', 'TCG_SOUL_TRADER_BEACON'),
    ('FYQA-7UC9-3TU5-Z497', 'TCG_SOUL_TRADER_BEACON'),
    ('NA7D-9U22-T2BY-P7K9', 'TCG_SOUL_TRADER_BEACON'),
    ('TNG5-ENGX-A8KC-DJRH', 'TCG_SOUL_TRADER_BEACON'),
    ('RMH6-Z6J4-YNB8-MT9W', 'TCG_SOUL_TRADER_BEACON'),
    ('FFW7-M8MH-JSTE-92WC', 'TCG_SOUL_TRADER_BEACON'),
    ('7SZA-E2ZC-299Q-PFE8', 'TCG_SOUL_TRADER_BEACON'),
    ('Y63Q-9KDV-5YKT-H3P2', 'TCG_SOUL_TRADER_BEACON'),
    ('HKT6-B2A8-BHSK-EZMV', 'TCG_SOUL_TRADER_BEACON'),
    ('PU8N-SKV9-3E8T-YHUN', 'TCG_SOUL_TRADER_BEACON'),
    ('J8WJ-AR43-MXQV-QPGT', 'TCG_SOUL_TRADER_BEACON'),
    ('F5U7-5MDE-FK2Q-6M33', 'TCG_SOUL_TRADER_BEACON'),
    ('P7BM-6E3J-KRAZ-PEJR', 'TCG_SOUL_TRADER_BEACON'),
    ('TJC5-F84H-2VNQ-7DYS', 'TCG_SOUL_TRADER_BEACON'),
    ('WPH5-YE5Y-R3RQ-JKYM', 'TCG_SOUL_TRADER_BEACON'),
    ('MKSB-HRCC-2E9A-83BT', 'TCG_SOUL_TRADER_BEACON'),
    ('9NMH-2CWC-PKHJ-8SJD', 'TCG_SOUL_TRADER_BEACON');

-- TCG_PARTY_GRENADE  (Party G.R.E.N.A.D.E.)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('WCAG-GJKR-SUFC-M36J', 'TCG_PARTY_GRENADE'),
    ('6J5F-BTJR-74BJ-23UH', 'TCG_PARTY_GRENADE'),
    ('36SK-PKU7-28WQ-97BR', 'TCG_PARTY_GRENADE'),
    ('F899-PZQV-WPQB-R4UR', 'TCG_PARTY_GRENADE'),
    ('99PW-78KT-UM5A-GT32', 'TCG_PARTY_GRENADE'),
    ('B5UG-HX3H-T7K7-AARF', 'TCG_PARTY_GRENADE'),
    ('2N8S-A9G4-JAYB-DAXN', 'TCG_PARTY_GRENADE'),
    ('VJNC-XAFC-MDKB-KXJM', 'TCG_PARTY_GRENADE'),
    ('GPZH-AJGP-KFZY-KRAG', 'TCG_PARTY_GRENADE'),
    ('YF5G-3DUC-MXGC-374Z', 'TCG_PARTY_GRENADE'),
    ('2XZB-HMXJ-72YY-44VM', 'TCG_PARTY_GRENADE'),
    ('7QMV-U58M-R5ZE-UVH4', 'TCG_PARTY_GRENADE'),
    ('9YFR-U4NH-TM97-UP44', 'TCG_PARTY_GRENADE'),
    ('4ZAG-239X-VWJ9-8Y8Q', 'TCG_PARTY_GRENADE'),
    ('FPDN-ZMW9-HPHG-5M9C', 'TCG_PARTY_GRENADE'),
    ('DRKB-4UFX-EPH2-A4R8', 'TCG_PARTY_GRENADE'),
    ('Y2JN-5BNH-XNJJ-Q4UU', 'TCG_PARTY_GRENADE'),
    ('YVUB-K7X3-3JFP-HXG7', 'TCG_PARTY_GRENADE'),
    ('S98R-B6UQ-PNE6-5HFR', 'TCG_PARTY_GRENADE'),
    ('FQD9-Q8KS-U5NJ-7NUF', 'TCG_PARTY_GRENADE');

-- TCG_FLAG_OF_OWNERSHIP  (The Flag of Ownership)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('CNWB-KMQA-DGQY-FFUF', 'TCG_FLAG_OF_OWNERSHIP'),
    ('DRRP-F7U6-MX56-B26Y', 'TCG_FLAG_OF_OWNERSHIP'),
    ('3FFB-Y5NP-Z4QZ-WMYM', 'TCG_FLAG_OF_OWNERSHIP'),
    ('TP6G-MBWQ-MGZX-W5QY', 'TCG_FLAG_OF_OWNERSHIP'),
    ('ST86-T25W-6A8U-HPXN', 'TCG_FLAG_OF_OWNERSHIP'),
    ('YVUQ-NEZZ-X62Y-MVMD', 'TCG_FLAG_OF_OWNERSHIP'),
    ('FPAP-T4UV-335F-JERA', 'TCG_FLAG_OF_OWNERSHIP'),
    ('R7QT-97ZH-DWZX-5UQQ', 'TCG_FLAG_OF_OWNERSHIP'),
    ('5DDV-M52E-ECF3-DWQ3', 'TCG_FLAG_OF_OWNERSHIP'),
    ('TFAM-K4WH-P4VR-3ZZR', 'TCG_FLAG_OF_OWNERSHIP'),
    ('3YZ2-Z5DA-ZAB6-HK38', 'TCG_FLAG_OF_OWNERSHIP'),
    ('3HXS-J2KP-KYC8-U7ET', 'TCG_FLAG_OF_OWNERSHIP'),
    ('YGK3-QP4P-CURA-734Z', 'TCG_FLAG_OF_OWNERSHIP'),
    ('SJXQ-DU6R-M6AM-8WT2', 'TCG_FLAG_OF_OWNERSHIP'),
    ('SUNP-SXER-52AS-YNFF', 'TCG_FLAG_OF_OWNERSHIP'),
    ('UDP9-MNUJ-V657-NYCF', 'TCG_FLAG_OF_OWNERSHIP'),
    ('BSM4-AUWH-5XUS-ABHH', 'TCG_FLAG_OF_OWNERSHIP'),
    ('HK3A-XWEB-BZZZ-E38B', 'TCG_FLAG_OF_OWNERSHIP'),
    ('7MGT-TVXH-SB55-TPRU', 'TCG_FLAG_OF_OWNERSHIP'),
    ('J7E4-M78T-9TUG-N4ZG', 'TCG_FLAG_OF_OWNERSHIP');

-- TCG_BIG_BATTLE_BEAR  (Big Battle Bear)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('4DC8-BVUE-ER2V-V5MZ', 'TCG_BIG_BATTLE_BEAR'),
    ('4HW8-Q66F-955U-V4B6', 'TCG_BIG_BATTLE_BEAR'),
    ('NR4V-VTSW-EYPH-BQZF', 'TCG_BIG_BATTLE_BEAR'),
    ('GBE4-CFZ8-GM8Q-G35W', 'TCG_BIG_BATTLE_BEAR'),
    ('TXNN-XPM3-QNQU-7536', 'TCG_BIG_BATTLE_BEAR'),
    ('AYM4-9PDV-FEJU-8W82', 'TCG_BIG_BATTLE_BEAR'),
    ('3PF6-BPNC-PZPW-8GZH', 'TCG_BIG_BATTLE_BEAR'),
    ('A64C-M4RC-2N2H-GBFF', 'TCG_BIG_BATTLE_BEAR'),
    ('C7K2-V65N-DPFB-2MBT', 'TCG_BIG_BATTLE_BEAR'),
    ('XZVV-SHEH-GPQB-U9TS', 'TCG_BIG_BATTLE_BEAR'),
    ('V86F-X3X5-SZQ2-DQ77', 'TCG_BIG_BATTLE_BEAR'),
    ('BGBB-VB47-TZSH-TFMK', 'TCG_BIG_BATTLE_BEAR'),
    ('XF7U-7E8S-QWKA-EMQF', 'TCG_BIG_BATTLE_BEAR'),
    ('YTBV-J6PA-AJRD-NBG9', 'TCG_BIG_BATTLE_BEAR'),
    ('Z8YR-ZFTA-SMUP-45TQ', 'TCG_BIG_BATTLE_BEAR'),
    ('SD4J-BCA6-NCUY-EAD3', 'TCG_BIG_BATTLE_BEAR'),
    ('YK4R-X7HX-6XXW-JBSW', 'TCG_BIG_BATTLE_BEAR'),
    ('NG2X-JZT6-HUKP-7TKJ', 'TCG_BIG_BATTLE_BEAR'),
    ('KU6Q-79X7-HBGR-R959', 'TCG_BIG_BATTLE_BEAR'),
    ('84KT-KMM3-5FPA-UVHR', 'TCG_BIG_BATTLE_BEAR');

-- TCG_SANDBOX_TIGER  (Sandbox Tiger)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('M6Z2-E25Z-WVSA-VC2K', 'TCG_SANDBOX_TIGER'),
    ('Z9Q8-39QR-HKND-AQJ8', 'TCG_SANDBOX_TIGER'),
    ('DXNW-UZ23-5TMA-FX9B', 'TCG_SANDBOX_TIGER'),
    ('ZKXA-5Z2H-7JXY-WPF3', 'TCG_SANDBOX_TIGER'),
    ('9H27-24BT-WRDV-6KUM', 'TCG_SANDBOX_TIGER'),
    ('EXUE-C86N-KZTD-MXDG', 'TCG_SANDBOX_TIGER'),
    ('NEEB-AP4P-9M4N-JG5F', 'TCG_SANDBOX_TIGER'),
    ('3DDF-YTYN-GAVN-ENAE', 'TCG_SANDBOX_TIGER'),
    ('88MQ-PGJM-V7HV-JDJZ', 'TCG_SANDBOX_TIGER'),
    ('TNHJ-T3WM-HFKN-SG46', 'TCG_SANDBOX_TIGER'),
    ('KB4E-D4TW-FGAA-SCXW', 'TCG_SANDBOX_TIGER'),
    ('44XM-UWW4-EPQE-84W6', 'TCG_SANDBOX_TIGER'),
    ('BFN5-FPCT-PDBJ-KCFR', 'TCG_SANDBOX_TIGER'),
    ('8FTH-6ZAP-A438-8REV', 'TCG_SANDBOX_TIGER'),
    ('SMSR-P4X6-ZH3U-7GYX', 'TCG_SANDBOX_TIGER'),
    ('BS9M-8PH8-KMYA-K35K', 'TCG_SANDBOX_TIGER'),
    ('4DX7-84Z8-38K9-R3RU', 'TCG_SANDBOX_TIGER'),
    ('F24K-26BC-VXTS-T54F', 'TCG_SANDBOX_TIGER'),
    ('S4HC-8TF7-83H7-242F', 'TCG_SANDBOX_TIGER'),
    ('S89F-EQPP-CSAP-4JN3', 'TCG_SANDBOX_TIGER');

-- TCG_EPIC_PURPLE_SHIRT  (Epic Purple Shirt)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('6QT5-UC6B-2FT8-KS52', 'TCG_EPIC_PURPLE_SHIRT'),
    ('RUMD-XCW6-T8QJ-7ZZQ', 'TCG_EPIC_PURPLE_SHIRT'),
    ('XJXM-B3E5-TMVG-7YKJ', 'TCG_EPIC_PURPLE_SHIRT'),
    ('BHDW-2BAP-YHW4-8J7H', 'TCG_EPIC_PURPLE_SHIRT'),
    ('2JFA-VARY-93TS-S6VR', 'TCG_EPIC_PURPLE_SHIRT'),
    ('5KJZ-8DSW-TV5T-WV7X', 'TCG_EPIC_PURPLE_SHIRT'),
    ('SUZR-PSBR-22FA-FJEA', 'TCG_EPIC_PURPLE_SHIRT'),
    ('AFQ5-9K97-PC4C-7AD7', 'TCG_EPIC_PURPLE_SHIRT'),
    ('PQW3-K2P9-DM69-35DV', 'TCG_EPIC_PURPLE_SHIRT'),
    ('KWYS-RQ7Y-PB3P-2DSD', 'TCG_EPIC_PURPLE_SHIRT'),
    ('25AU-TMB3-AD6D-MJ6Z', 'TCG_EPIC_PURPLE_SHIRT'),
    ('DUPT-WYZ4-GWUW-SERY', 'TCG_EPIC_PURPLE_SHIRT'),
    ('X9GC-ZVJZ-JH7G-CZKA', 'TCG_EPIC_PURPLE_SHIRT'),
    ('7YD2-75XZ-GQW9-TM2C', 'TCG_EPIC_PURPLE_SHIRT'),
    ('MJJE-8HKN-FU8D-8WRT', 'TCG_EPIC_PURPLE_SHIRT'),
    ('BDK9-5SSQ-WEGJ-8DZ9', 'TCG_EPIC_PURPLE_SHIRT'),
    ('DJXZ-39YS-AU79-SW9E', 'TCG_EPIC_PURPLE_SHIRT'),
    ('XET8-55KC-2MR3-N792', 'TCG_EPIC_PURPLE_SHIRT'),
    ('3NDC-TXJG-9J7Y-6PSX', 'TCG_EPIC_PURPLE_SHIRT'),
    ('TP5K-BB88-HK4R-9Q5P', 'TCG_EPIC_PURPLE_SHIRT');

-- TCG_FOAM_SWORD_RACK  (Foam Sword Rack)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('Y2FV-KJKT-2846-77BA', 'TCG_FOAM_SWORD_RACK'),
    ('NR3D-V5XU-5CYM-Z5MZ', 'TCG_FOAM_SWORD_RACK'),
    ('U98C-6ZER-D388-4VJX', 'TCG_FOAM_SWORD_RACK'),
    ('5Z24-GQ4P-JA5G-HNFG', 'TCG_FOAM_SWORD_RACK'),
    ('ZVA9-YN89-Q737-GF35', 'TCG_FOAM_SWORD_RACK'),
    ('TWNC-D6P4-HSRE-6NHQ', 'TCG_FOAM_SWORD_RACK'),
    ('MEEQ-V4Q7-3QY6-MFUX', 'TCG_FOAM_SWORD_RACK'),
    ('WJR9-ZMMT-A3NV-H66Q', 'TCG_FOAM_SWORD_RACK'),
    ('5EKT-NR99-UVTA-4CA5', 'TCG_FOAM_SWORD_RACK'),
    ('ESK7-PTV2-AUAT-WD5E', 'TCG_FOAM_SWORD_RACK'),
    ('G6XQ-THBK-TRPS-MVZZ', 'TCG_FOAM_SWORD_RACK'),
    ('52YV-QPRA-JUXZ-G75Y', 'TCG_FOAM_SWORD_RACK'),
    ('YDHD-UB8Z-9UWT-JTCT', 'TCG_FOAM_SWORD_RACK'),
    ('YSK7-MS24-R9Y9-SHF7', 'TCG_FOAM_SWORD_RACK'),
    ('P7BW-9FUS-ZD5F-9SUH', 'TCG_FOAM_SWORD_RACK'),
    ('8JUX-45QX-FTP6-ESSS', 'TCG_FOAM_SWORD_RACK'),
    ('RNE4-AHNG-M4KW-A2Z2', 'TCG_FOAM_SWORD_RACK'),
    ('TJH9-5E97-2T7F-52FW', 'TCG_FOAM_SWORD_RACK'),
    ('TQST-4WAR-DAQZ-CCAM', 'TCG_FOAM_SWORD_RACK'),
    ('WWEZ-JDNS-HFJY-Y47S', 'TCG_FOAM_SWORD_RACK');

-- TCG_PATH_OF_CENARIUS  (Path of Cenarius)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('EEHR-SF9D-5YJ9-2XST', 'TCG_PATH_OF_CENARIUS'),
    ('35DQ-D7DT-A2VS-47DE', 'TCG_PATH_OF_CENARIUS'),
    ('3A8W-KJPN-RMJB-KEHX', 'TCG_PATH_OF_CENARIUS'),
    ('5J2K-4V2V-9NTR-JRRE', 'TCG_PATH_OF_CENARIUS'),
    ('XDW5-92FT-R2EQ-GTUQ', 'TCG_PATH_OF_CENARIUS'),
    ('GJ5R-JZTH-2CXU-ZG58', 'TCG_PATH_OF_CENARIUS'),
    ('G9GG-P95S-89GN-835U', 'TCG_PATH_OF_CENARIUS'),
    ('UUXU-VFS9-9CT7-YYBQ', 'TCG_PATH_OF_CENARIUS'),
    ('Q59M-7T86-AS7D-QDSC', 'TCG_PATH_OF_CENARIUS'),
    ('ENPP-YXXD-4JU3-TK3R', 'TCG_PATH_OF_CENARIUS'),
    ('9T39-TSB2-XDAC-9HFN', 'TCG_PATH_OF_CENARIUS'),
    ('UU8H-TSA6-ZQQX-X963', 'TCG_PATH_OF_CENARIUS'),
    ('WXNU-9JKW-HSRC-4TU9', 'TCG_PATH_OF_CENARIUS'),
    ('FA9D-UX6G-HGQD-Q65N', 'TCG_PATH_OF_CENARIUS'),
    ('5GVM-FGMX-53CB-WGAH', 'TCG_PATH_OF_CENARIUS'),
    ('WW54-AKXA-4GQT-PZTF', 'TCG_PATH_OF_CENARIUS'),
    ('7V3E-HBV9-TYCC-HZW7', 'TCG_PATH_OF_CENARIUS'),
    ('JT5M-3UJM-GZ7R-B576', 'TCG_PATH_OF_CENARIUS'),
    ('DH7Z-N4DR-44GU-SE9Z', 'TCG_PATH_OF_CENARIUS'),
    ('UC5Y-4H3P-8QR3-SZ6D', 'TCG_PATH_OF_CENARIUS');

-- TCG_OGRE_PINATA  (Ogre Pinata)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('WKZ2-RWZU-G56E-UZ6K', 'TCG_OGRE_PINATA'),
    ('U52R-EDHV-AFUK-QC2Y', 'TCG_OGRE_PINATA'),
    ('HSED-PPHA-UMVE-827D', 'TCG_OGRE_PINATA'),
    ('G7PE-CTE8-JY4D-74AK', 'TCG_OGRE_PINATA'),
    ('YR48-4UB9-DEFG-95VX', 'TCG_OGRE_PINATA'),
    ('KGPF-T3YC-YWRM-YXUA', 'TCG_OGRE_PINATA'),
    ('UPDP-6KZX-4982-PJ2G', 'TCG_OGRE_PINATA'),
    ('GKRR-ZYEY-GKB6-YHHN', 'TCG_OGRE_PINATA'),
    ('E39U-KM49-6X7R-UQ9M', 'TCG_OGRE_PINATA'),
    ('M2DT-F5R4-KF2X-B44P', 'TCG_OGRE_PINATA'),
    ('BX87-E8VC-YTFR-GF7V', 'TCG_OGRE_PINATA'),
    ('C9RK-PQBZ-SSUD-BU8P', 'TCG_OGRE_PINATA'),
    ('WS4V-CVM3-26AA-KRYH', 'TCG_OGRE_PINATA'),
    ('STGN-SN5T-86JB-U42B', 'TCG_OGRE_PINATA'),
    ('XYM4-CR9M-ZBB8-K454', 'TCG_OGRE_PINATA'),
    ('RK5B-SMVB-2B6J-FZ6Q', 'TCG_OGRE_PINATA'),
    ('4JCF-8W24-6AGY-XSGU', 'TCG_OGRE_PINATA'),
    ('7SKB-XYNT-GRVW-USVW', 'TCG_OGRE_PINATA'),
    ('J8MP-GJ5R-H8FS-CK9W', 'TCG_OGRE_PINATA'),
    ('FE2W-T9MT-EQUQ-3K4S', 'TCG_OGRE_PINATA');

-- TCG_MAGIC_ROOSTER_EGG  (Magic Rooster Egg)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('QPMM-AHBX-YRUX-2296', 'TCG_MAGIC_ROOSTER_EGG'),
    ('ZJCV-7465-SBTK-GKB3', 'TCG_MAGIC_ROOSTER_EGG'),
    ('C36X-TDMW-2VPB-TPJE', 'TCG_MAGIC_ROOSTER_EGG'),
    ('55C6-RWH2-W2H5-2QGB', 'TCG_MAGIC_ROOSTER_EGG'),
    ('JBC8-X77Y-2PBH-PFDW', 'TCG_MAGIC_ROOSTER_EGG'),
    ('BW9H-DYQ8-5P6Y-MWE5', 'TCG_MAGIC_ROOSTER_EGG'),
    ('MR4M-FSP6-WVBC-Y3XX', 'TCG_MAGIC_ROOSTER_EGG'),
    ('HKQA-FM4Y-7WAC-SX4J', 'TCG_MAGIC_ROOSTER_EGG'),
    ('VQJC-MVY2-D34B-SVCW', 'TCG_MAGIC_ROOSTER_EGG'),
    ('KVYP-HJ5V-FKJE-4F56', 'TCG_MAGIC_ROOSTER_EGG'),
    ('JRVD-PY84-CEBU-QD82', 'TCG_MAGIC_ROOSTER_EGG'),
    ('CAW5-6SV6-AZPJ-78YU', 'TCG_MAGIC_ROOSTER_EGG'),
    ('JVWK-ZGTM-X835-F88G', 'TCG_MAGIC_ROOSTER_EGG'),
    ('E3FW-FVA5-EPVX-2T69', 'TCG_MAGIC_ROOSTER_EGG'),
    ('JST4-Q893-NMKC-8AUP', 'TCG_MAGIC_ROOSTER_EGG'),
    ('NGZW-YVYT-NB58-YU73', 'TCG_MAGIC_ROOSTER_EGG'),
    ('T9VY-XF4A-M7QW-RZ5X', 'TCG_MAGIC_ROOSTER_EGG'),
    ('TAW6-47XZ-828X-8DWW', 'TCG_MAGIC_ROOSTER_EGG'),
    ('69VS-NJUK-AAWK-F4ZT', 'TCG_MAGIC_ROOSTER_EGG'),
    ('UPKJ-EBHW-QKR2-9YS4', 'TCG_MAGIC_ROOSTER_EGG');

-- TCG_SCOURGEWAR_MINIMOUNT  (Scourgewar Mini-Mount (faction-aware))
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('5B2G-MGB9-PZ4C-22R2', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('47HV-QC6S-7DSK-ASYN', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('H23H-GHYY-QKJZ-P65Z', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('NBXD-AZXF-46ZY-N4Z7', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('GCSW-CYKW-YAAE-6RHD', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('A5YU-5E4E-QJTE-PU29', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('VS2P-KPNV-W7EP-JFBU', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('Q5VM-RTK9-XEF3-G8JV', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('UCXH-R2DJ-Z6JM-3NSK', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('MBVR-K5WD-SPD9-TZVW', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('TXRX-PVQF-HMFH-KKW9', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('HUWX-ZBNB-MS7C-GCSJ', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('R45T-FPG7-ABY7-HYYN', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('4AVA-KD6Z-D7SR-FFG7', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('MGHQ-PMEJ-A2W8-2WNV', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('SC2R-9FD4-Q23B-AFRF', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('P62X-A9F8-PS8Q-KV9S', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('AXT3-5YJF-UYGW-RXK8', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('9AZP-22RT-T733-BGRY', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('JQWD-KS4C-ZZBQ-UE9A', 'TCG_SCOURGEWAR_MINIMOUNT');

-- TCG_TUSKARR_KITE  (Tuskarr Kite)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('JFGF-SRX3-8FE5-R7VE', 'TCG_TUSKARR_KITE'),
    ('KJ8B-4MFV-4PQ2-HMJT', 'TCG_TUSKARR_KITE'),
    ('RQED-6DNG-PF3P-URGC', 'TCG_TUSKARR_KITE'),
    ('Q5ZT-XDSC-WRHY-HXCA', 'TCG_TUSKARR_KITE'),
    ('N722-T5QG-G4XH-2F45', 'TCG_TUSKARR_KITE'),
    ('E4A2-UKUF-DRMC-PXWG', 'TCG_TUSKARR_KITE'),
    ('GAZN-8T38-JBEZ-C3Y3', 'TCG_TUSKARR_KITE'),
    ('PGA8-C3YC-326J-ZNCW', 'TCG_TUSKARR_KITE'),
    ('XNQP-K3QK-WWD2-VGJA', 'TCG_TUSKARR_KITE'),
    ('JT4Z-XKVQ-G86T-5KU8', 'TCG_TUSKARR_KITE'),
    ('44C9-4PDP-GGK5-KCYC', 'TCG_TUSKARR_KITE'),
    ('C8ZB-7WFZ-RDZE-U5UZ', 'TCG_TUSKARR_KITE'),
    ('YYFT-HMBY-XF4J-9CMQ', 'TCG_TUSKARR_KITE'),
    ('6X97-WSN5-UT45-4KQ8', 'TCG_TUSKARR_KITE'),
    ('JJRC-CJWC-57SE-N5R6', 'TCG_TUSKARR_KITE'),
    ('6C9A-RR98-HD6R-F9TB', 'TCG_TUSKARR_KITE'),
    ('K3GR-9RQ6-A2HC-B847', 'TCG_TUSKARR_KITE'),
    ('DMYJ-ZAX3-B5EC-GEJQ', 'TCG_TUSKARR_KITE'),
    ('KTMW-E2MR-M4HY-PNRT', 'TCG_TUSKARR_KITE'),
    ('H7JZ-255K-6UJJ-V95K', 'TCG_TUSKARR_KITE');

-- TCG_SPECTRAL_TIGER_CUB  (Spectral Tiger Cub)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('4NDD-U3ZC-XM6P-KCFV', 'TCG_SPECTRAL_TIGER_CUB'),
    ('DEJ5-WB3E-UBA2-JU9N', 'TCG_SPECTRAL_TIGER_CUB'),
    ('ZU9B-3SAW-B4JV-6RK7', 'TCG_SPECTRAL_TIGER_CUB'),
    ('BV37-XPF8-8KTS-3Y9Y', 'TCG_SPECTRAL_TIGER_CUB'),
    ('V2AQ-EU4U-PUMY-FQ7Z', 'TCG_SPECTRAL_TIGER_CUB'),
    ('6XDU-WDRD-QRD5-QQGY', 'TCG_SPECTRAL_TIGER_CUB'),
    ('82D2-VA2Q-Q9ES-6CNH', 'TCG_SPECTRAL_TIGER_CUB'),
    ('PW93-DTGU-V4J6-G27E', 'TCG_SPECTRAL_TIGER_CUB'),
    ('C4F3-D6QB-DVU4-T422', 'TCG_SPECTRAL_TIGER_CUB'),
    ('XMEJ-89KZ-WJW6-XT7M', 'TCG_SPECTRAL_TIGER_CUB'),
    ('APQ9-BZAC-B3Z3-C4TR', 'TCG_SPECTRAL_TIGER_CUB'),
    ('R27J-5SNY-M5XF-8765', 'TCG_SPECTRAL_TIGER_CUB'),
    ('XBHJ-A8WR-8A8C-MN8P', 'TCG_SPECTRAL_TIGER_CUB'),
    ('RQWN-ZTDH-X5KJ-XW6S', 'TCG_SPECTRAL_TIGER_CUB'),
    ('KJAD-RE35-BSEN-5U8P', 'TCG_SPECTRAL_TIGER_CUB'),
    ('WCX7-9K2D-3MKC-8WW9', 'TCG_SPECTRAL_TIGER_CUB'),
    ('85JZ-WR5Y-GYMK-5293', 'TCG_SPECTRAL_TIGER_CUB'),
    ('DKC3-8S7B-843T-M3GJ', 'TCG_SPECTRAL_TIGER_CUB'),
    ('VXND-HT8J-DHKR-E32N', 'TCG_SPECTRAL_TIGER_CUB'),
    ('ZNWB-86RN-55J6-6FB7', 'TCG_SPECTRAL_TIGER_CUB');

-- TCG_LANDROS_GIFT_BOX  (Landro's Gift Box)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('CBNN-79GK-2YV7-7JV7', 'TCG_LANDROS_GIFT_BOX'),
    ('FSUZ-8TUH-8KR4-XA5V', 'TCG_LANDROS_GIFT_BOX'),
    ('7426-M5DS-QZK2-2C3P', 'TCG_LANDROS_GIFT_BOX'),
    ('57KD-NHEK-KBUY-7C68', 'TCG_LANDROS_GIFT_BOX'),
    ('TYWD-WNXC-84WG-WMQC', 'TCG_LANDROS_GIFT_BOX'),
    ('R6C2-AV9C-33HU-RC32', 'TCG_LANDROS_GIFT_BOX'),
    ('YBPT-K3P3-YD9V-XDN4', 'TCG_LANDROS_GIFT_BOX'),
    ('UMC7-YCK2-3KAJ-MUDA', 'TCG_LANDROS_GIFT_BOX'),
    ('HX6P-AEFF-WZCK-9BE7', 'TCG_LANDROS_GIFT_BOX'),
    ('GBT7-WBDQ-GGQW-Q5AV', 'TCG_LANDROS_GIFT_BOX'),
    ('K68T-A3RX-EE8V-MZJV', 'TCG_LANDROS_GIFT_BOX'),
    ('NAA6-NPNJ-K976-QVMF', 'TCG_LANDROS_GIFT_BOX'),
    ('JZTS-FYK2-K6ZE-BQAJ', 'TCG_LANDROS_GIFT_BOX'),
    ('MDNC-ZMWB-PPXX-AE8P', 'TCG_LANDROS_GIFT_BOX'),
    ('VWHH-F8Z6-RBNM-79V3', 'TCG_LANDROS_GIFT_BOX'),
    ('W6AS-DCAN-8AVK-5B8H', 'TCG_LANDROS_GIFT_BOX'),
    ('T5QX-2RKY-PM8C-7YFE', 'TCG_LANDROS_GIFT_BOX'),
    ('YBHR-7TFJ-5HUR-AXQ5', 'TCG_LANDROS_GIFT_BOX'),
    ('UF5B-6MR6-HWDE-66V7', 'TCG_LANDROS_GIFT_BOX'),
    ('7FER-JAG5-K26U-5KGB', 'TCG_LANDROS_GIFT_BOX');

-- TCG_INSTANT_STATUE_PEDESTAL  (Instant Statue Pedestal)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('A3T8-F4EN-9759-JEND', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('CD32-379M-34CH-VXZM', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('PSCA-4PHR-TJHV-7B4W', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('SUDM-WU7A-W4D8-PREF', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('M7M9-GXMF-KQ2J-QUE6', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('A9FR-9SY9-HJ23-SYWW', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('VDYA-M35D-3ZK7-REVM', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('YUQ4-6NK4-PYPG-3TRZ', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('MQB6-UBK5-G35R-W63A', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('9BB4-B9MD-H4SG-RCUW', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('WK5R-DX34-CDH7-GB3Q', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('S6G3-J6UT-9K7F-9MGU', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('DDSR-SXZY-3HCW-CVAR', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('Z6TB-7K4K-Z3T4-9WD7', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('WF6R-CE7G-3JBP-XZ77', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('S2SP-JQ7P-2SG7-X5TM', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('MGHX-KQBJ-4GZR-U58P', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('6A5N-MHGP-HW7U-857D', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('RDQX-3NFK-G9PS-22V5', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('DTXV-84ZA-UXQ8-SEG3', 'TCG_INSTANT_STATUE_PEDESTAL');

-- TCG_BLAZING_HIPPOGRYPH  (Blazing Hippogryph)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('RM2U-KUMC-7DTN-8ZEF', 'TCG_BLAZING_HIPPOGRYPH'),
    ('JB6C-UKH5-EDWK-J8HF', 'TCG_BLAZING_HIPPOGRYPH'),
    ('FNQ8-4HZH-ZNSN-3KH4', 'TCG_BLAZING_HIPPOGRYPH'),
    ('CDJB-ZQ8Q-BCKT-78DZ', 'TCG_BLAZING_HIPPOGRYPH'),
    ('4JGQ-AXE6-TMCB-77PE', 'TCG_BLAZING_HIPPOGRYPH'),
    ('YD2B-WJZ5-C3M9-XTCQ', 'TCG_BLAZING_HIPPOGRYPH'),
    ('564D-FB4W-BK9K-J8WS', 'TCG_BLAZING_HIPPOGRYPH'),
    ('BKTD-38XH-PXKR-994C', 'TCG_BLAZING_HIPPOGRYPH'),
    ('GU25-7YVB-86EX-97ET', 'TCG_BLAZING_HIPPOGRYPH'),
    ('J997-J73E-FM9V-56BY', 'TCG_BLAZING_HIPPOGRYPH'),
    ('B3AZ-XVZW-Y78W-3224', 'TCG_BLAZING_HIPPOGRYPH'),
    ('FUYJ-HXNP-F7SU-3CYK', 'TCG_BLAZING_HIPPOGRYPH'),
    ('78G9-S5JH-3RXJ-2XE3', 'TCG_BLAZING_HIPPOGRYPH'),
    ('8V88-CKFV-CAWU-A5JE', 'TCG_BLAZING_HIPPOGRYPH'),
    ('JJXV-MD76-5YQA-M65W', 'TCG_BLAZING_HIPPOGRYPH'),
    ('QT8W-MMRR-CSX9-3YHT', 'TCG_BLAZING_HIPPOGRYPH'),
    ('EKKE-VV8V-W9UX-99X3', 'TCG_BLAZING_HIPPOGRYPH'),
    ('WMFV-9T46-FA25-EPFB', 'TCG_BLAZING_HIPPOGRYPH'),
    ('UCPR-P8RU-TFEJ-VF24', 'TCG_BLAZING_HIPPOGRYPH'),
    ('8E6Z-BJFB-CN4C-5J28', 'TCG_BLAZING_HIPPOGRYPH');

-- TCG_PAINT_BOMB  (Paint Bomb)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('WBQB-HRR6-4VFM-WR6U', 'TCG_PAINT_BOMB'),
    ('HKBB-GTBE-R68M-BGY5', 'TCG_PAINT_BOMB'),
    ('9QAV-CK6E-HK38-EW4A', 'TCG_PAINT_BOMB'),
    ('3QDB-7PS3-FC3M-J7BR', 'TCG_PAINT_BOMB'),
    ('2E7H-6TM2-8BND-BDMA', 'TCG_PAINT_BOMB'),
    ('MH7X-RW7X-FZHC-D6B7', 'TCG_PAINT_BOMB'),
    ('GKD8-PRTV-G8T3-5B89', 'TCG_PAINT_BOMB'),
    ('WAPZ-JJW5-J96U-PTB4', 'TCG_PAINT_BOMB'),
    ('HR6M-M9V6-YHC5-CXGG', 'TCG_PAINT_BOMB'),
    ('BKMU-DNCM-QPQ9-UDJA', 'TCG_PAINT_BOMB'),
    ('WY7Y-8SC5-QXHX-9N74', 'TCG_PAINT_BOMB'),
    ('4YJ4-FAMZ-DGYK-X9TF', 'TCG_PAINT_BOMB'),
    ('XWU2-YTHR-2QM3-W7ZB', 'TCG_PAINT_BOMB'),
    ('RNN6-B5DN-PVAW-MZ4D', 'TCG_PAINT_BOMB'),
    ('VRWM-WFCA-Z3S9-J53Y', 'TCG_PAINT_BOMB'),
    ('HHWC-GZTJ-84XM-NHZU', 'TCG_PAINT_BOMB'),
    ('UGAQ-C549-MGWZ-G5HA', 'TCG_PAINT_BOMB'),
    ('WAAY-7NJA-B5QH-3ZUV', 'TCG_PAINT_BOMB'),
    ('D4FM-KW5U-96TN-C392', 'TCG_PAINT_BOMB'),
    ('G635-3YF8-V8US-V723', 'TCG_PAINT_BOMB');

-- TCG_ETHEREAL_PORTAL  (Ethereal Portal)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('WH5Y-8DFR-GZF6-KP2W', 'TCG_ETHEREAL_PORTAL'),
    ('JDZK-TTBW-RAAV-QKPM', 'TCG_ETHEREAL_PORTAL'),
    ('3G5R-5RAU-Q2QK-8FY7', 'TCG_ETHEREAL_PORTAL'),
    ('QAM7-G3MN-3RQ7-2Z8X', 'TCG_ETHEREAL_PORTAL'),
    ('6E39-B6F4-E7QR-GR9U', 'TCG_ETHEREAL_PORTAL'),
    ('WSH7-B6MM-4RKM-9Q38', 'TCG_ETHEREAL_PORTAL'),
    ('TUXN-7NRY-TYD4-CTNY', 'TCG_ETHEREAL_PORTAL'),
    ('FGZP-U5RB-2DHY-NUVB', 'TCG_ETHEREAL_PORTAL'),
    ('NX93-G96V-YEFD-3TFH', 'TCG_ETHEREAL_PORTAL'),
    ('WEZY-MFWM-WHZG-K5EQ', 'TCG_ETHEREAL_PORTAL'),
    ('BT7N-JJ43-KYGB-558W', 'TCG_ETHEREAL_PORTAL'),
    ('7PKH-VR7H-SEZM-WUTP', 'TCG_ETHEREAL_PORTAL'),
    ('EZCQ-QWJJ-5ZBA-ER7Y', 'TCG_ETHEREAL_PORTAL'),
    ('8J89-ZX9B-EAVT-9QWQ', 'TCG_ETHEREAL_PORTAL'),
    ('A6VA-N8NG-QCF2-H336', 'TCG_ETHEREAL_PORTAL'),
    ('QYU2-PYHC-EGEH-HXES', 'TCG_ETHEREAL_PORTAL'),
    ('ZBPP-FNNE-HDHV-H8VN', 'TCG_ETHEREAL_PORTAL'),
    ('76GR-3PJV-2HQB-MYWY', 'TCG_ETHEREAL_PORTAL'),
    ('SNTF-3BVQ-DVS8-87TA', 'TCG_ETHEREAL_PORTAL'),
    ('JMJK-E9B4-2KUM-YDCK', 'TCG_ETHEREAL_PORTAL');

-- TCG_WOOLY_WHITE_RHINO  (Wooly White Rhino)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('XQT5-HE5F-J6CW-XXXN', 'TCG_WOOLY_WHITE_RHINO'),
    ('N6WD-DWE4-293T-JG8K', 'TCG_WOOLY_WHITE_RHINO'),
    ('8VU9-CX3V-9DXE-EN2B', 'TCG_WOOLY_WHITE_RHINO'),
    ('AY76-W7ER-YQDZ-6H56', 'TCG_WOOLY_WHITE_RHINO'),
    ('ECCH-M7UN-ST7B-9YDT', 'TCG_WOOLY_WHITE_RHINO'),
    ('8SJW-UH9X-S6VX-7GTP', 'TCG_WOOLY_WHITE_RHINO'),
    ('J54Y-R35K-DC2X-D7HB', 'TCG_WOOLY_WHITE_RHINO'),
    ('95BG-SJGK-JNU9-CPEM', 'TCG_WOOLY_WHITE_RHINO'),
    ('FQPU-3FSV-QA4G-43M7', 'TCG_WOOLY_WHITE_RHINO'),
    ('BJXT-3SM2-74XX-C8G6', 'TCG_WOOLY_WHITE_RHINO'),
    ('74RW-3MDD-CR7Z-V3T6', 'TCG_WOOLY_WHITE_RHINO'),
    ('MNNE-GP82-E7TG-P2RN', 'TCG_WOOLY_WHITE_RHINO'),
    ('XAB2-QNUC-UJ49-QN9D', 'TCG_WOOLY_WHITE_RHINO'),
    ('E74S-WHTC-C5UD-2XE7', 'TCG_WOOLY_WHITE_RHINO'),
    ('7PSX-N2Q3-ZSJU-XE39', 'TCG_WOOLY_WHITE_RHINO'),
    ('RRM2-WWEA-WDG3-4QQ9', 'TCG_WOOLY_WHITE_RHINO'),
    ('8X3F-WADJ-UXTF-XZ73', 'TCG_WOOLY_WHITE_RHINO'),
    ('JPFU-KJE2-6QE3-CXPZ', 'TCG_WOOLY_WHITE_RHINO'),
    ('B5YZ-46QD-BV9X-FH24', 'TCG_WOOLY_WHITE_RHINO'),
    ('S2Z8-AW7Z-3G9Q-GC8D', 'TCG_WOOLY_WHITE_RHINO');

-- TCG_TABARD_OF_FROST  (Tabard of Frost)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('WBCB-Z9YB-PDAZ-D5KX', 'TCG_TABARD_OF_FROST'),
    ('QU94-W6QD-TRFS-9956', 'TCG_TABARD_OF_FROST'),
    ('4NBP-86E7-DXNJ-JGEN', 'TCG_TABARD_OF_FROST'),
    ('8TWR-3Z5A-KYYR-4N3W', 'TCG_TABARD_OF_FROST'),
    ('KEJY-FH2V-MGNC-JGV3', 'TCG_TABARD_OF_FROST'),
    ('B57Q-JWGU-JCUV-AH6D', 'TCG_TABARD_OF_FROST'),
    ('ZYSK-FR8D-E8UA-NUJT', 'TCG_TABARD_OF_FROST'),
    ('ZUUZ-B9QP-7MZY-SCAU', 'TCG_TABARD_OF_FROST'),
    ('QRFS-RU64-QPGY-KPBH', 'TCG_TABARD_OF_FROST'),
    ('XX3W-W25J-WWUW-M3JE', 'TCG_TABARD_OF_FROST'),
    ('BZ4K-GRVU-6CNS-5WG3', 'TCG_TABARD_OF_FROST'),
    ('MFVR-6X3Q-T8E7-PUD6', 'TCG_TABARD_OF_FROST'),
    ('MQ4Y-WCZH-JP63-P2SH', 'TCG_TABARD_OF_FROST'),
    ('F6VJ-VT2R-2Z43-UBR9', 'TCG_TABARD_OF_FROST'),
    ('TV5K-FY32-V3DM-5THQ', 'TCG_TABARD_OF_FROST'),
    ('FVHK-KGJM-SPNA-J2EE', 'TCG_TABARD_OF_FROST'),
    ('4J5Z-GMQP-6ZX4-MRUK', 'TCG_TABARD_OF_FROST'),
    ('HUWY-Y37G-KBP5-A579', 'TCG_TABARD_OF_FROST'),
    ('ZTJD-B8ZF-PJZW-ZBCP', 'TCG_TABARD_OF_FROST'),
    ('SMHJ-ZWFS-D937-WFT3', 'TCG_TABARD_OF_FROST');

-- TCG_PERPETUAL_PURPLE_FIREWORK  (Perpetual Purple Firework)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('5JB4-54VF-FQGY-DTVW', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('QZPN-7DBC-5FP7-KKPH', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('MKXH-GY4X-PKKJ-Q9P8', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('RP66-WBQJ-AHYV-UDJF', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('DKAT-ECKA-TY89-V29P', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('EA7R-YW8U-G35K-5GPM', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('EWYN-3BUZ-KFFP-TX7U', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('T9E9-JR2N-2774-FBVZ', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('2FFK-P6SK-PZ8Q-MBSV', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('S9JY-SYBN-QCQC-4FJU', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('WQCB-KVUP-QDZT-QA3P', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('BDRE-BB5F-CPQ8-3HYU', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('8WTA-Z3E6-WE9J-X2TT', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('ARSQ-DMCJ-EG89-CZC2', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('HA54-J6UT-SR2E-RMG9', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('9S94-H2ZQ-ASM3-QYBT', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('6C2Y-TBT5-EY3D-YP57', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('YM5Z-47NT-57PJ-NNZP', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('2UVE-GZCX-SGYK-U5UH', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('CV4H-XBCK-WH76-XWFB', 'TCG_PERPETUAL_PURPLE_FIREWORK');

-- TCG_CARVED_OGRE_IDOL  (Carved Ogre Idol)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('9DEW-J2MR-7388-BFR6', 'TCG_CARVED_OGRE_IDOL'),
    ('3VED-5A4T-DSNN-JXHZ', 'TCG_CARVED_OGRE_IDOL'),
    ('JDUF-BFMX-ZBWC-92Q4', 'TCG_CARVED_OGRE_IDOL'),
    ('24J6-GXNR-K38H-ZDUE', 'TCG_CARVED_OGRE_IDOL'),
    ('9PV2-QP4F-6DS2-CM8H', 'TCG_CARVED_OGRE_IDOL'),
    ('HPK2-UT77-63M3-VUZ2', 'TCG_CARVED_OGRE_IDOL'),
    ('JB32-UZPE-QCHD-MDV3', 'TCG_CARVED_OGRE_IDOL'),
    ('PXPK-4KYN-WKQZ-5ZBY', 'TCG_CARVED_OGRE_IDOL'),
    ('3YJ6-NKPD-X9VK-KRVT', 'TCG_CARVED_OGRE_IDOL'),
    ('TQ3N-SV9X-2SW9-59ZP', 'TCG_CARVED_OGRE_IDOL'),
    ('G32S-BMNJ-76DU-DSQA', 'TCG_CARVED_OGRE_IDOL'),
    ('3EHR-C7HU-DKXC-4QMX', 'TCG_CARVED_OGRE_IDOL'),
    ('8Y49-R37T-TPF4-2BNE', 'TCG_CARVED_OGRE_IDOL'),
    ('GPAM-B8AC-QQEZ-2UNS', 'TCG_CARVED_OGRE_IDOL'),
    ('WW4D-3H8H-58HQ-NSRR', 'TCG_CARVED_OGRE_IDOL'),
    ('AV83-38WW-Y4ZK-KEGK', 'TCG_CARVED_OGRE_IDOL'),
    ('TKA4-BUJP-7S5P-QU86', 'TCG_CARVED_OGRE_IDOL'),
    ('ZABG-CMD3-EQYC-B7P3', 'TCG_CARVED_OGRE_IDOL'),
    ('6P9K-4MQN-F5MN-UBYN', 'TCG_CARVED_OGRE_IDOL'),
    ('KSYT-4SQZ-9QN4-2KQU', 'TCG_CARVED_OGRE_IDOL');

-- TCG_TABARD_OF_THE_ARCANE  (Tabard of the Arcane)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('V5VX-EF7Y-EYHR-V7PP', 'TCG_TABARD_OF_THE_ARCANE'),
    ('W9Q5-YJ8G-6NAH-2WWU', 'TCG_TABARD_OF_THE_ARCANE'),
    ('WX3M-X98T-A27Z-98HJ', 'TCG_TABARD_OF_THE_ARCANE'),
    ('2HDT-DZ8C-AYQM-V9W7', 'TCG_TABARD_OF_THE_ARCANE'),
    ('GRV9-2TNN-KV9Z-Q4MX', 'TCG_TABARD_OF_THE_ARCANE'),
    ('CEH3-543S-M4DG-BF9Y', 'TCG_TABARD_OF_THE_ARCANE'),
    ('BZ72-63G5-NFJ3-C6G2', 'TCG_TABARD_OF_THE_ARCANE'),
    ('J772-Z9JW-84JA-H7WG', 'TCG_TABARD_OF_THE_ARCANE'),
    ('G28C-77XW-S5XX-G37M', 'TCG_TABARD_OF_THE_ARCANE'),
    ('UHWV-6G2W-JGJQ-KRRS', 'TCG_TABARD_OF_THE_ARCANE'),
    ('FY7J-NNPX-8ZU4-RBYA', 'TCG_TABARD_OF_THE_ARCANE'),
    ('CK3P-3KBC-EJRW-9YXG', 'TCG_TABARD_OF_THE_ARCANE'),
    ('TMV6-QZ44-BCHK-WJ73', 'TCG_TABARD_OF_THE_ARCANE'),
    ('85A5-DC8G-J8YA-VPBG', 'TCG_TABARD_OF_THE_ARCANE'),
    ('P767-NYZR-2M82-RVA9', 'TCG_TABARD_OF_THE_ARCANE'),
    ('TJBS-4G49-SXKH-RFZN', 'TCG_TABARD_OF_THE_ARCANE'),
    ('WTH2-AM9B-8YX6-HN5K', 'TCG_TABARD_OF_THE_ARCANE'),
    ('MPZS-N9RC-5JZA-8P9A', 'TCG_TABARD_OF_THE_ARCANE'),
    ('2EK6-9RN9-EFXD-JQAB', 'TCG_TABARD_OF_THE_ARCANE'),
    ('2PRX-UG3G-QYV5-BPJY', 'TCG_TABARD_OF_THE_ARCANE');

-- TCG_TABARD_OF_BRILLIANCE  (Tabard of Brilliance)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('HZWF-BNGU-2RY7-YX89', 'TCG_TABARD_OF_BRILLIANCE'),
    ('3NSR-45ZY-7VJK-BF3M', 'TCG_TABARD_OF_BRILLIANCE'),
    ('EZYU-4KMX-HXQH-99C9', 'TCG_TABARD_OF_BRILLIANCE'),
    ('YJC6-6FMM-HAR2-GQEG', 'TCG_TABARD_OF_BRILLIANCE'),
    ('Q42Y-XVJ5-BKMB-ESPC', 'TCG_TABARD_OF_BRILLIANCE'),
    ('RT42-4J23-CSAG-3ANH', 'TCG_TABARD_OF_BRILLIANCE'),
    ('J4XA-AVR9-XRNH-DYH5', 'TCG_TABARD_OF_BRILLIANCE'),
    ('JSXV-228H-MX5G-SF93', 'TCG_TABARD_OF_BRILLIANCE'),
    ('E9UD-ERB7-2SCC-WQJ2', 'TCG_TABARD_OF_BRILLIANCE'),
    ('JTPH-D23C-BTPY-GGMY', 'TCG_TABARD_OF_BRILLIANCE'),
    ('6V6D-AM88-PQKM-3TAC', 'TCG_TABARD_OF_BRILLIANCE'),
    ('2K7A-FB7P-Y8B5-EZNR', 'TCG_TABARD_OF_BRILLIANCE'),
    ('33K8-WSRU-8FPK-JGDG', 'TCG_TABARD_OF_BRILLIANCE'),
    ('DAT7-TW42-P8NN-UAJW', 'TCG_TABARD_OF_BRILLIANCE'),
    ('JQ4J-YSKX-WBU8-PPRP', 'TCG_TABARD_OF_BRILLIANCE'),
    ('386U-3NES-6FNB-3DMX', 'TCG_TABARD_OF_BRILLIANCE'),
    ('5UHD-JY55-XQB8-6S97', 'TCG_TABARD_OF_BRILLIANCE'),
    ('RGMC-43NB-44Z7-BBNZ', 'TCG_TABARD_OF_BRILLIANCE'),
    ('7CE6-EZQS-PCUU-J5GW', 'TCG_TABARD_OF_BRILLIANCE'),
    ('CKGS-UAMZ-FZ2Z-MXCH', 'TCG_TABARD_OF_BRILLIANCE');

-- TCG_TABARD_OF_THE_DEFENDER  (Tabard of the Defender)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('DGP8-JSCE-2CYJ-2R2X', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('57YF-YUW4-WQPD-JRK8', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('G96X-HUQC-8SS9-VUYB', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('E3DZ-3VA8-2X84-KA3W', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('N296-D75V-TQ4U-GFEZ', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('S547-GNR3-KSGQ-B44R', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('KXWY-CDP9-77UW-FDHJ', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('94FQ-G35A-K7B5-DQGR', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('B6AT-6GGS-MB5T-MRCV', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('WAQ9-CGT6-XKU4-X5TR', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('9N22-S8AP-TWHM-X9WF', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('5S66-2QP3-7VAD-UTKG', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('BVAH-DDTH-YAPH-237V', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('N3MJ-84QQ-EY8Q-YWRR', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('CGBQ-BBKF-DGNA-PD2K', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('EJYA-3VUJ-QAMK-6V8J', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('Y887-W9N5-Y5DZ-7GCA', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('ND89-6S7W-2PAE-4M8N', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('Y9XD-HJ5A-J9FK-6DMB', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('RNH4-9K9F-WC4K-4N74', 'TCG_TABARD_OF_THE_DEFENDER');

-- TCG_TABARD_OF_FURY  (Tabard of Fury)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('VTPX-JXB2-99G9-TY9A', 'TCG_TABARD_OF_FURY'),
    ('BBHT-5H9G-5CPD-8945', 'TCG_TABARD_OF_FURY'),
    ('WM9R-BQK8-3TBA-PCSV', 'TCG_TABARD_OF_FURY'),
    ('9UJZ-6GB5-H543-3QN7', 'TCG_TABARD_OF_FURY'),
    ('5US5-K7FC-76AA-8SD5', 'TCG_TABARD_OF_FURY'),
    ('XT43-C7DE-WGHH-YHHC', 'TCG_TABARD_OF_FURY'),
    ('Z8FT-97VE-5S2W-GDSZ', 'TCG_TABARD_OF_FURY'),
    ('4J2F-MAK8-YGZG-7EVZ', 'TCG_TABARD_OF_FURY'),
    ('JFA6-286T-2YUY-AU2R', 'TCG_TABARD_OF_FURY'),
    ('HEE2-U8FR-CN3D-UMMB', 'TCG_TABARD_OF_FURY'),
    ('JRJU-KJ24-DG6T-ZG8M', 'TCG_TABARD_OF_FURY'),
    ('G7ZA-9JFC-2DQU-6879', 'TCG_TABARD_OF_FURY'),
    ('RVQ4-778M-CS5Y-XT8F', 'TCG_TABARD_OF_FURY'),
    ('J865-8YN2-ZBDS-67DH', 'TCG_TABARD_OF_FURY'),
    ('HYTD-7787-B2BN-X7F5', 'TCG_TABARD_OF_FURY'),
    ('XAVE-UDKU-EC92-ZUNP', 'TCG_TABARD_OF_FURY'),
    ('B2X4-K5ZN-ZYHX-BMD2', 'TCG_TABARD_OF_FURY'),
    ('HV6U-2D92-U9D7-XMHB', 'TCG_TABARD_OF_FURY'),
    ('W62Z-RRED-EM2G-PJAB', 'TCG_TABARD_OF_FURY'),
    ('XYSY-Y86R-Q2H2-R7Z6', 'TCG_TABARD_OF_FURY');

-- TCG_TABARD_OF_NATURE  (Tabard of Nature)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('QXYC-9UVS-G8FV-EJTW', 'TCG_TABARD_OF_NATURE'),
    ('RMS9-CARR-H3BV-4HZ2', 'TCG_TABARD_OF_NATURE'),
    ('5EFT-ST2H-X9PP-F37U', 'TCG_TABARD_OF_NATURE'),
    ('8XR4-87WA-BRSG-VT7Q', 'TCG_TABARD_OF_NATURE'),
    ('KYPA-GQXA-6RB5-RYCQ', 'TCG_TABARD_OF_NATURE'),
    ('NEBK-UP69-YD2M-Z7YD', 'TCG_TABARD_OF_NATURE'),
    ('T4KZ-HZM2-MRAR-DQHC', 'TCG_TABARD_OF_NATURE'),
    ('634E-VJ3Q-3XD6-EF9W', 'TCG_TABARD_OF_NATURE'),
    ('XNFZ-7H9A-2AMS-6GHX', 'TCG_TABARD_OF_NATURE'),
    ('PHXM-TDWB-ZZ3P-UEWK', 'TCG_TABARD_OF_NATURE'),
    ('RDW9-A8HH-BM4N-R2YR', 'TCG_TABARD_OF_NATURE'),
    ('BX66-DFV6-NAQE-7GNC', 'TCG_TABARD_OF_NATURE'),
    ('HF7D-78R2-9WXQ-M6SU', 'TCG_TABARD_OF_NATURE'),
    ('WXQD-EW5D-3PBT-S8MN', 'TCG_TABARD_OF_NATURE'),
    ('786K-W5EH-J8WN-6X5R', 'TCG_TABARD_OF_NATURE'),
    ('VV2Y-F269-74MZ-SEKX', 'TCG_TABARD_OF_NATURE'),
    ('YHAJ-YGFK-RAX7-2S3D', 'TCG_TABARD_OF_NATURE'),
    ('8GMH-TCHV-5D4C-YSST', 'TCG_TABARD_OF_NATURE'),
    ('GR86-438N-NKJV-2ABS', 'TCG_TABARD_OF_NATURE'),
    ('DS4M-MUCK-MWYU-XA55', 'TCG_TABARD_OF_NATURE');

-- TCG_TABARD_OF_THE_VOID  (Tabard of the Void)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('7WAG-9C5P-XEM5-56JV', 'TCG_TABARD_OF_THE_VOID'),
    ('ZUH2-G52T-CBCP-RXWK', 'TCG_TABARD_OF_THE_VOID'),
    ('CZNC-2CT5-TW6R-MU76', 'TCG_TABARD_OF_THE_VOID'),
    ('9AE3-YJNA-UPJS-PZ5C', 'TCG_TABARD_OF_THE_VOID'),
    ('T2A5-47G9-HA6A-HG9C', 'TCG_TABARD_OF_THE_VOID'),
    ('9HXG-H927-88HQ-W4KR', 'TCG_TABARD_OF_THE_VOID'),
    ('9JR9-ZC83-VRZX-8AU2', 'TCG_TABARD_OF_THE_VOID'),
    ('AG2W-NU5C-U22K-SQTE', 'TCG_TABARD_OF_THE_VOID'),
    ('D465-3SF3-GXTD-FZTU', 'TCG_TABARD_OF_THE_VOID'),
    ('P96K-4ZJY-2GPY-8HQ5', 'TCG_TABARD_OF_THE_VOID'),
    ('JATH-NU64-9QHP-XR75', 'TCG_TABARD_OF_THE_VOID'),
    ('D4W4-NTE9-MRWD-DZCD', 'TCG_TABARD_OF_THE_VOID'),
    ('7VFT-JGRA-7GMG-8H75', 'TCG_TABARD_OF_THE_VOID'),
    ('XKW6-6BRU-BD8E-FU6V', 'TCG_TABARD_OF_THE_VOID'),
    ('7PUD-YWMB-5UXX-N7D9', 'TCG_TABARD_OF_THE_VOID'),
    ('7VUZ-X4ED-SNXH-8M8H', 'TCG_TABARD_OF_THE_VOID'),
    ('4BG5-7D6G-8NJK-KYU6', 'TCG_TABARD_OF_THE_VOID'),
    ('GP59-QDVM-3BP2-PJSQ', 'TCG_TABARD_OF_THE_VOID'),
    ('JBNE-XXQU-UDPZ-4S53', 'TCG_TABARD_OF_THE_VOID'),
    ('FS8H-9CV9-QN2E-E25J', 'TCG_TABARD_OF_THE_VOID');

-- TCG_LANDROS_PET_BOX  (Landro's Pet Box)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('AH7Y-6JEU-ZUG6-66K7', 'TCG_LANDROS_PET_BOX'),
    ('E3GN-27RS-SEUY-Z5YV', 'TCG_LANDROS_PET_BOX'),
    ('FV3K-863V-44CN-TFUC', 'TCG_LANDROS_PET_BOX'),
    ('2ABS-JUH5-SDBC-847G', 'TCG_LANDROS_PET_BOX'),
    ('BERU-Q6AU-9TSZ-YES3', 'TCG_LANDROS_PET_BOX'),
    ('GTTK-SUT2-USKX-SE8R', 'TCG_LANDROS_PET_BOX'),
    ('5NQ5-T4FG-UQZB-QBFY', 'TCG_LANDROS_PET_BOX'),
    ('7KRY-GHJ8-SAVD-X5T6', 'TCG_LANDROS_PET_BOX'),
    ('MKFC-THTK-33WQ-FTFJ', 'TCG_LANDROS_PET_BOX'),
    ('VC4E-JFN3-9UFW-VSFA', 'TCG_LANDROS_PET_BOX'),
    ('U4A4-A7Q6-XF2F-CQ6A', 'TCG_LANDROS_PET_BOX'),
    ('D2FH-DK3B-UHRG-9GET', 'TCG_LANDROS_PET_BOX'),
    ('JPTV-GFDX-X3FJ-BUD3', 'TCG_LANDROS_PET_BOX'),
    ('RWRK-FX2X-9B7Y-4WWE', 'TCG_LANDROS_PET_BOX'),
    ('WWDP-V8BN-R8BK-X32D', 'TCG_LANDROS_PET_BOX'),
    ('WXXU-FTF7-SQV8-Z2J4', 'TCG_LANDROS_PET_BOX'),
    ('UTU2-PE9U-F3CX-X232', 'TCG_LANDROS_PET_BOX'),
    ('5XPF-XCE9-3Q99-2DBR', 'TCG_LANDROS_PET_BOX'),
    ('RWNN-9EHB-P6P6-NVBN', 'TCG_LANDROS_PET_BOX'),
    ('EFMS-WP8Q-9FSS-ET43', 'TCG_LANDROS_PET_BOX');

-- BLIZZCON_MURKY  (Murky (Blue Murloc Egg))
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('Y8Z5-MMVJ-U99K-NBQ3', 'BLIZZCON_MURKY'),
    ('RKVE-CZKW-GHY4-SPFH', 'BLIZZCON_MURKY'),
    ('NT3N-EKS5-VPW5-AA5M', 'BLIZZCON_MURKY'),
    ('D7PK-JB82-HENG-RYVR', 'BLIZZCON_MURKY'),
    ('TXN4-BJCC-399J-QP7N', 'BLIZZCON_MURKY'),
    ('3KRU-52FE-SG2S-ESRK', 'BLIZZCON_MURKY'),
    ('ET5M-CPQV-6ZAS-PCVM', 'BLIZZCON_MURKY'),
    ('CF96-NJQ7-AP74-2XVV', 'BLIZZCON_MURKY'),
    ('EHXG-Z68F-HQXU-4SMZ', 'BLIZZCON_MURKY'),
    ('EZJ7-MJYZ-7NQE-UDTZ', 'BLIZZCON_MURKY'),
    ('F7TA-PW8G-AW9A-XAAG', 'BLIZZCON_MURKY'),
    ('G8CU-BW43-779G-DW7T', 'BLIZZCON_MURKY'),
    ('5JC2-Q9F9-MUVE-FS6M', 'BLIZZCON_MURKY'),
    ('F5SP-5DB8-ZVVH-QADD', 'BLIZZCON_MURKY'),
    ('C3DF-UKEH-2MNX-RGD6', 'BLIZZCON_MURKY'),
    ('7S8E-C8TJ-6X7P-B4BP', 'BLIZZCON_MURKY'),
    ('YNYZ-DRUB-UPWS-3TN9', 'BLIZZCON_MURKY'),
    ('MYN8-2TU6-9F2A-GJQ2', 'BLIZZCON_MURKY'),
    ('TZ7E-CWXR-4WKC-HCB7', 'BLIZZCON_MURKY'),
    ('XUPG-MSAR-E586-XXQC', 'BLIZZCON_MURKY');

-- BLIZZCON_MURLOC_COSTUME  (Murloc Costume)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('DYSH-97DK-4UM6-W6G9', 'BLIZZCON_MURLOC_COSTUME'),
    ('EYWD-TJQJ-5A3K-U2AW', 'BLIZZCON_MURLOC_COSTUME'),
    ('2UJM-KRNT-RJWB-MA2S', 'BLIZZCON_MURLOC_COSTUME'),
    ('AF5H-VNH4-XCEN-TZST', 'BLIZZCON_MURLOC_COSTUME'),
    ('DCKB-QJXW-4V4F-DZNR', 'BLIZZCON_MURLOC_COSTUME'),
    ('54PC-5W6D-U82X-XCW9', 'BLIZZCON_MURLOC_COSTUME'),
    ('GZPU-NQRS-8UW5-3YGT', 'BLIZZCON_MURLOC_COSTUME'),
    ('2CE6-Q76Z-DT9E-8YD3', 'BLIZZCON_MURLOC_COSTUME'),
    ('MFBE-6V4T-FJME-NSBR', 'BLIZZCON_MURLOC_COSTUME'),
    ('CNV2-UR8A-RMG4-VY69', 'BLIZZCON_MURLOC_COSTUME'),
    ('5CXN-4277-D84R-59W6', 'BLIZZCON_MURLOC_COSTUME'),
    ('B6YP-67UW-GMXB-UTRJ', 'BLIZZCON_MURLOC_COSTUME'),
    ('YAP6-8R98-GQYS-ZK98', 'BLIZZCON_MURLOC_COSTUME'),
    ('4YX4-XVJM-6569-CB5B', 'BLIZZCON_MURLOC_COSTUME'),
    ('9VJD-HH2B-QZMW-GEWZ', 'BLIZZCON_MURLOC_COSTUME'),
    ('D4DM-33ST-8V2G-JAHM', 'BLIZZCON_MURLOC_COSTUME'),
    ('FZJX-VGCE-8TCA-77BA', 'BLIZZCON_MURLOC_COSTUME'),
    ('4MNQ-Q35J-PWK6-2VWC', 'BLIZZCON_MURLOC_COSTUME'),
    ('C7D9-CXMN-KNV5-SPH9', 'BLIZZCON_MURLOC_COSTUME'),
    ('7GAM-5TMB-63W6-VSJM', 'BLIZZCON_MURLOC_COSTUME');

-- BLIZZCON_BIG_BLIZZARD_BEAR  (Big Blizzard Bear)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('2WBS-H9UM-4CB4-5X6W', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('93DA-TBNQ-8MJS-AJQT', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('XNKP-8UHG-KXHM-68EX', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('7EWD-MMY3-QFRG-QZP2', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('GWFT-CX25-VNEA-HCYC', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('CJKT-QTKV-8SEM-PHG7', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('UK2M-V7XY-UMXR-VG8K', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('9SQD-2S78-K4G9-DMZD', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('BWPQ-UHAW-RUHC-7S9H', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('QKQT-V69G-QTYD-K7N6', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('GAYQ-4CRY-RM5S-QS83', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('2PGS-VCJF-SAXD-4NHN', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('Q7F3-3GK5-VQK5-CVKS', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('W39U-PYZT-YK34-8985', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('A5W9-9TFK-FQAY-57Q2', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('JPZQ-Z5QR-SEBV-BTT2', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('95P6-J2A6-Q8DZ-9WX7', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('BS6Y-T42W-TSHF-GYPY', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('MEVT-5MBX-APUS-HZE5', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('8BWQ-XDHS-GCBX-UHTG', 'BLIZZCON_BIG_BLIZZARD_BEAR');

-- PROMO_GURKY  (Gurky (Pink Murloc Egg))
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('DQZE-YW62-4SBU-HS6R', 'PROMO_GURKY'),
    ('N535-C6P8-UUXF-635T', 'PROMO_GURKY'),
    ('2T9V-9SBM-DJ2Q-QY4B', 'PROMO_GURKY'),
    ('Y3Q7-JWUW-MMYR-DRM2', 'PROMO_GURKY'),
    ('XNND-HR8P-BUM8-GPSE', 'PROMO_GURKY'),
    ('XNXG-KB4M-5CDX-JP66', 'PROMO_GURKY'),
    ('AVXC-6HMF-JG2S-T3YS', 'PROMO_GURKY'),
    ('NTXW-BTJ4-BNFV-ZYK8', 'PROMO_GURKY'),
    ('QRH8-U29T-BYN3-TWPW', 'PROMO_GURKY'),
    ('TBYV-57BA-SQSY-D6V7', 'PROMO_GURKY'),
    ('3JX5-3F9X-QD28-UPH6', 'PROMO_GURKY'),
    ('QVQ8-ZRUF-CC9C-3SVV', 'PROMO_GURKY'),
    ('WJ4J-H4CZ-QRKF-HEWM', 'PROMO_GURKY'),
    ('Q8MQ-EFJN-JQXK-GU7Y', 'PROMO_GURKY'),
    ('JNBX-SAM9-XBEU-H78Y', 'PROMO_GURKY'),
    ('QJDU-NK8E-U3YU-SVW7', 'PROMO_GURKY'),
    ('83M8-MMQC-PMHA-P6YS', 'PROMO_GURKY'),
    ('934E-2DMB-HXP8-ET2U', 'PROMO_GURKY'),
    ('E48Q-ZS24-F569-GJU2', 'PROMO_GURKY'),
    ('KYVB-T9GB-SHHV-RF86', 'PROMO_GURKY');

-- PROMO_ORANGE_MURLOC_EGG  (Orange Murloc Egg)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('BPXY-T9P9-4Q7E-DNH3', 'PROMO_ORANGE_MURLOC_EGG'),
    ('YJZ9-7F6V-CQGR-8ZAM', 'PROMO_ORANGE_MURLOC_EGG'),
    ('JJNG-7UG2-9BTQ-WMN9', 'PROMO_ORANGE_MURLOC_EGG'),
    ('5SUE-NYZ3-GFXT-FK3R', 'PROMO_ORANGE_MURLOC_EGG'),
    ('SBUB-T46D-W4DG-DPK9', 'PROMO_ORANGE_MURLOC_EGG'),
    ('RKWH-R96S-X4K5-WYUA', 'PROMO_ORANGE_MURLOC_EGG'),
    ('SEGM-Z6VT-Z9U7-7CQR', 'PROMO_ORANGE_MURLOC_EGG'),
    ('W4H2-Z9NR-DPQ9-AR8K', 'PROMO_ORANGE_MURLOC_EGG'),
    ('WH3Q-RDRB-65QR-WFVN', 'PROMO_ORANGE_MURLOC_EGG'),
    ('UQXK-2HZC-ZYKD-WQAB', 'PROMO_ORANGE_MURLOC_EGG'),
    ('CEZR-KJX6-SGAS-Z6F5', 'PROMO_ORANGE_MURLOC_EGG'),
    ('B6TA-PCSD-TTSJ-UTNG', 'PROMO_ORANGE_MURLOC_EGG'),
    ('CF2T-V9SE-PM3Z-VFND', 'PROMO_ORANGE_MURLOC_EGG'),
    ('ZKM7-8M9A-FVGP-EWV5', 'PROMO_ORANGE_MURLOC_EGG'),
    ('Y2T5-X7MF-UTSA-EMFT', 'PROMO_ORANGE_MURLOC_EGG'),
    ('WYKH-HHDJ-JN63-CKFR', 'PROMO_ORANGE_MURLOC_EGG'),
    ('D68M-MD77-K9X3-3TDB', 'PROMO_ORANGE_MURLOC_EGG'),
    ('FP32-KT63-HQ7Z-97R2', 'PROMO_ORANGE_MURLOC_EGG'),
    ('GATW-J57G-XBK6-E34J', 'PROMO_ORANGE_MURLOC_EGG'),
    ('RD85-XMTH-N7MD-TFA5', 'PROMO_ORANGE_MURLOC_EGG');

-- PROMO_WHITE_MURLOC_EGG  (White Murloc Egg)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('RG94-7RND-Z2CQ-CE99', 'PROMO_WHITE_MURLOC_EGG'),
    ('Z25F-JX8D-QASE-YNTH', 'PROMO_WHITE_MURLOC_EGG'),
    ('BE4H-9QAB-S8W9-YPYW', 'PROMO_WHITE_MURLOC_EGG'),
    ('394Z-C66Q-35TB-ZRV6', 'PROMO_WHITE_MURLOC_EGG'),
    ('MHZA-VN4W-Q7QC-2CCX', 'PROMO_WHITE_MURLOC_EGG'),
    ('PEUG-75A2-77UF-HA6D', 'PROMO_WHITE_MURLOC_EGG'),
    ('6S3C-WEWN-ARDV-27QV', 'PROMO_WHITE_MURLOC_EGG'),
    ('U72J-6R79-Z2PA-SG7T', 'PROMO_WHITE_MURLOC_EGG'),
    ('RG7Y-NCTS-TF5N-6HQA', 'PROMO_WHITE_MURLOC_EGG'),
    ('262J-F5J5-WJRF-TFZV', 'PROMO_WHITE_MURLOC_EGG'),
    ('ZA86-QS4C-864N-ETK9', 'PROMO_WHITE_MURLOC_EGG'),
    ('RVXJ-6WFG-DE5P-9BBA', 'PROMO_WHITE_MURLOC_EGG'),
    ('QVFQ-QH3Q-XEZR-KQBH', 'PROMO_WHITE_MURLOC_EGG'),
    ('VYVU-899C-RK35-6UD2', 'PROMO_WHITE_MURLOC_EGG'),
    ('2B6F-26DZ-XKDJ-CSC2', 'PROMO_WHITE_MURLOC_EGG'),
    ('GB8V-CQWW-TP7P-T4G7', 'PROMO_WHITE_MURLOC_EGG'),
    ('SEGM-QAE4-D433-C76G', 'PROMO_WHITE_MURLOC_EGG'),
    ('X2UK-6RF7-CZH6-DTK6', 'PROMO_WHITE_MURLOC_EGG'),
    ('HX97-RU9W-VBMG-E468', 'PROMO_WHITE_MURLOC_EGG'),
    ('8T3Y-YK7U-S7JF-QKUJ', 'PROMO_WHITE_MURLOC_EGG');

-- PROMO_HEAVY_MURLOC_EGG  (Heavy Murloc Egg)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('VC3H-7E9C-AB2P-UC4Q', 'PROMO_HEAVY_MURLOC_EGG'),
    ('D2T4-FMJR-5VSR-S2AF', 'PROMO_HEAVY_MURLOC_EGG'),
    ('G9NA-EXK6-QN2W-HFZH', 'PROMO_HEAVY_MURLOC_EGG'),
    ('ENDV-4EA5-CWE4-H44U', 'PROMO_HEAVY_MURLOC_EGG'),
    ('AV3Z-DGD8-AJ83-UQ6R', 'PROMO_HEAVY_MURLOC_EGG'),
    ('SWF7-KYKP-44V7-AVG7', 'PROMO_HEAVY_MURLOC_EGG'),
    ('FXNN-J47P-E58Q-9PV9', 'PROMO_HEAVY_MURLOC_EGG'),
    ('X9E8-AE2P-GFNV-VEFQ', 'PROMO_HEAVY_MURLOC_EGG'),
    ('9PTZ-CXJY-ZQHS-T6BV', 'PROMO_HEAVY_MURLOC_EGG'),
    ('C84Y-BA9Z-5MSQ-Q8QE', 'PROMO_HEAVY_MURLOC_EGG'),
    ('T5SV-C4JX-E2TC-C736', 'PROMO_HEAVY_MURLOC_EGG'),
    ('3U63-BNFZ-EKQZ-4TNQ', 'PROMO_HEAVY_MURLOC_EGG'),
    ('GNDA-CB9D-SKCA-PU35', 'PROMO_HEAVY_MURLOC_EGG'),
    ('RWFS-2TR7-AECZ-U7CG', 'PROMO_HEAVY_MURLOC_EGG'),
    ('YDCQ-WD5E-2DKG-K3VJ', 'PROMO_HEAVY_MURLOC_EGG'),
    ('SAS5-N2T5-FC4V-F9JX', 'PROMO_HEAVY_MURLOC_EGG'),
    ('NSY3-QF2K-52K2-Q87X', 'PROMO_HEAVY_MURLOC_EGG'),
    ('MAVZ-6QBA-PQZG-Q52U', 'PROMO_HEAVY_MURLOC_EGG'),
    ('R5B4-5UXP-5Q52-ZSDJ', 'PROMO_HEAVY_MURLOC_EGG'),
    ('MCBS-CS3B-DSUB-JFHH', 'PROMO_HEAVY_MURLOC_EGG');

-- PROMO_MURKIMUS_SPEAR  (Murkimus' Little Spear)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('U2E8-MA29-27TF-FBUN', 'PROMO_MURKIMUS_SPEAR'),
    ('DKU8-7AM9-CXMY-55DC', 'PROMO_MURKIMUS_SPEAR'),
    ('8A3M-44ZP-3QPX-W6ZQ', 'PROMO_MURKIMUS_SPEAR'),
    ('CSYS-ZMK9-ZV46-986J', 'PROMO_MURKIMUS_SPEAR'),
    ('8TGR-C57G-G98M-4ADQ', 'PROMO_MURKIMUS_SPEAR'),
    ('GS4Y-GA83-UREC-X685', 'PROMO_MURKIMUS_SPEAR'),
    ('VYP8-4AMF-2QMA-ZH83', 'PROMO_MURKIMUS_SPEAR'),
    ('B8EB-CRG5-GNEG-T9BR', 'PROMO_MURKIMUS_SPEAR'),
    ('2BAV-BPM5-TMXK-BB7C', 'PROMO_MURKIMUS_SPEAR'),
    ('5UFU-J46V-NHTW-8T7Y', 'PROMO_MURKIMUS_SPEAR'),
    ('RGNX-RQA8-DNN4-7F9W', 'PROMO_MURKIMUS_SPEAR'),
    ('DBQM-U3QQ-82ER-NMJ2', 'PROMO_MURKIMUS_SPEAR'),
    ('E7HE-9PDQ-9H8R-HD99', 'PROMO_MURKIMUS_SPEAR'),
    ('WTPU-WP6X-M4RR-7GJ8', 'PROMO_MURKIMUS_SPEAR'),
    ('HEX8-5V4T-356J-ANDP', 'PROMO_MURKIMUS_SPEAR'),
    ('PRXF-H2GH-WTRE-8RF5', 'PROMO_MURKIMUS_SPEAR'),
    ('2BE6-RE2C-GQAH-DNBD', 'PROMO_MURKIMUS_SPEAR'),
    ('2K6M-NVSA-JHN4-PCTJ', 'PROMO_MURKIMUS_SPEAR'),
    ('XXZ8-SW6Z-52SH-WRTB', 'PROMO_MURKIMUS_SPEAR'),
    ('ABGA-KMN9-SP8A-WJ5C', 'PROMO_MURKIMUS_SPEAR');

-- PROMO_ZERGLING_LEASH  (Zergling Leash)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('ZE32-UPVA-GU9A-9VDJ', 'PROMO_ZERGLING_LEASH'),
    ('NSN8-4KZ7-K3U7-7Y9W', 'PROMO_ZERGLING_LEASH'),
    ('MA3T-4DFT-HPMA-P442', 'PROMO_ZERGLING_LEASH'),
    ('HVED-7RXW-9FVQ-MJRB', 'PROMO_ZERGLING_LEASH'),
    ('4Y8W-HBG7-NXUR-P89M', 'PROMO_ZERGLING_LEASH'),
    ('USQJ-3CZR-N894-8B9F', 'PROMO_ZERGLING_LEASH'),
    ('V85V-AUX5-A42V-RCKE', 'PROMO_ZERGLING_LEASH'),
    ('6G4U-759Y-G95K-3E4P', 'PROMO_ZERGLING_LEASH'),
    ('JQQY-D2WX-GYER-MG6C', 'PROMO_ZERGLING_LEASH'),
    ('SPH5-AZYD-MRM4-RWVV', 'PROMO_ZERGLING_LEASH'),
    ('X79K-P468-J9QG-BDSW', 'PROMO_ZERGLING_LEASH'),
    ('CXBD-4VDR-FATD-63QT', 'PROMO_ZERGLING_LEASH'),
    ('X2DH-FDCK-S67W-3KCC', 'PROMO_ZERGLING_LEASH'),
    ('NHJW-RXZM-VGP9-9HZS', 'PROMO_ZERGLING_LEASH'),
    ('UKQW-YEAQ-R2Z3-6WXJ', 'PROMO_ZERGLING_LEASH'),
    ('286V-JT3G-JAUP-BYGT', 'PROMO_ZERGLING_LEASH'),
    ('NVK8-M2NA-GCHA-3PCH', 'PROMO_ZERGLING_LEASH'),
    ('F4V3-CFRP-KZJ5-KE2Q', 'PROMO_ZERGLING_LEASH'),
    ('YP9A-2RJB-A7R9-SPPX', 'PROMO_ZERGLING_LEASH'),
    ('HNAB-UBGX-X64Q-X43H', 'PROMO_ZERGLING_LEASH');

-- PROMO_PANDA_COLLAR  (Panda Collar)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('YZUC-BMJB-BWAS-3VX7', 'PROMO_PANDA_COLLAR'),
    ('ZM7A-8KB7-5F75-YSGZ', 'PROMO_PANDA_COLLAR'),
    ('Z4ZY-GNQZ-HQBG-QK47', 'PROMO_PANDA_COLLAR'),
    ('E8RP-QQYY-VEWB-6YMN', 'PROMO_PANDA_COLLAR'),
    ('WPSP-H2JB-RVH3-PN3Q', 'PROMO_PANDA_COLLAR'),
    ('RCRQ-E2JU-TV3M-RVRK', 'PROMO_PANDA_COLLAR'),
    ('XKPN-5EHY-QRNV-JT46', 'PROMO_PANDA_COLLAR'),
    ('6HGS-CGVV-FB3A-FNK5', 'PROMO_PANDA_COLLAR'),
    ('H2P2-GJNC-TNUZ-M2X8', 'PROMO_PANDA_COLLAR'),
    ('5JUP-YW48-8753-DYQA', 'PROMO_PANDA_COLLAR'),
    ('PX8N-RBKH-JDMX-35WS', 'PROMO_PANDA_COLLAR'),
    ('9DTW-HD2X-5FBX-QSG3', 'PROMO_PANDA_COLLAR'),
    ('SGP8-W3UP-M7JQ-4WDX', 'PROMO_PANDA_COLLAR'),
    ('9HNT-UFWC-NS87-9DRW', 'PROMO_PANDA_COLLAR'),
    ('SJRA-N64W-XBWX-YXG5', 'PROMO_PANDA_COLLAR'),
    ('32CR-73HZ-CC5G-Q2ER', 'PROMO_PANDA_COLLAR'),
    ('N6GU-96EW-2GN9-6T87', 'PROMO_PANDA_COLLAR'),
    ('KZD5-WGXY-9YPS-SHBA', 'PROMO_PANDA_COLLAR'),
    ('QAJG-KK5M-MKMW-3CUU', 'PROMO_PANDA_COLLAR'),
    ('GWNY-QS6A-P33H-RRWY', 'PROMO_PANDA_COLLAR');

-- PROMO_DIABLO_STONE  (Diablo Stone)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('64AA-BRQ6-27YA-7WY9', 'PROMO_DIABLO_STONE'),
    ('YNK6-RZJW-FHZ2-PXFG', 'PROMO_DIABLO_STONE'),
    ('M37D-WUPE-WEY5-KYV8', 'PROMO_DIABLO_STONE'),
    ('2YWN-VGAJ-VMC9-3YAR', 'PROMO_DIABLO_STONE'),
    ('5FSG-4859-DQ5Z-YDRW', 'PROMO_DIABLO_STONE'),
    ('GVNC-8CD5-3SMQ-FKSW', 'PROMO_DIABLO_STONE'),
    ('HA7Y-4M2J-T7PU-84W7', 'PROMO_DIABLO_STONE'),
    ('CBYE-CHVJ-KU9R-NE2M', 'PROMO_DIABLO_STONE'),
    ('VAHB-GPXH-7FCG-JAEH', 'PROMO_DIABLO_STONE'),
    ('CMJT-5NEE-R3PN-YNRX', 'PROMO_DIABLO_STONE'),
    ('K9JA-D7PV-7Z6G-AYXD', 'PROMO_DIABLO_STONE'),
    ('AXRF-PV8S-PTH9-R7Y5', 'PROMO_DIABLO_STONE'),
    ('F4FP-YWMX-PA5P-DRCY', 'PROMO_DIABLO_STONE'),
    ('6RB6-M839-ST9E-W8VT', 'PROMO_DIABLO_STONE'),
    ('P7ZV-N2KY-3RHA-RUTP', 'PROMO_DIABLO_STONE'),
    ('Z4VV-YFUV-9TRH-Z9D8', 'PROMO_DIABLO_STONE'),
    ('TAF3-CXHC-ENSS-6EM6', 'PROMO_DIABLO_STONE'),
    ('5KPB-RQPK-KBE9-2R5T', 'PROMO_DIABLO_STONE'),
    ('ER5G-G8JB-5X9Y-CYB7', 'PROMO_DIABLO_STONE'),
    ('NVCK-HJS5-2RCZ-R4YC', 'PROMO_DIABLO_STONE');

-- PROMO_NETHERWHELP  (Netherwhelp's Collar)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('VKX9-Y8SK-CYG6-6GEA', 'PROMO_NETHERWHELP'),
    ('FU9B-J3PG-5BUK-293H', 'PROMO_NETHERWHELP'),
    ('ZZTF-TJV2-F9C8-H9W4', 'PROMO_NETHERWHELP'),
    ('3G66-HSV4-9TVX-S586', 'PROMO_NETHERWHELP'),
    ('USYH-8MMJ-6VS8-6YP5', 'PROMO_NETHERWHELP'),
    ('5ZYE-PJUM-VXM3-MH5U', 'PROMO_NETHERWHELP'),
    ('J9GT-2MWJ-5GSN-5ZG6', 'PROMO_NETHERWHELP'),
    ('MGGR-5XNV-YYJX-NDA9', 'PROMO_NETHERWHELP'),
    ('QX9C-FUCZ-H7DQ-NDDR', 'PROMO_NETHERWHELP'),
    ('BS5B-CM6J-S3CT-6VXC', 'PROMO_NETHERWHELP'),
    ('UHZC-4AY6-GEFY-FS5A', 'PROMO_NETHERWHELP'),
    ('3UZE-N5ZH-5GN2-9S8K', 'PROMO_NETHERWHELP'),
    ('Y4RP-EBQQ-ANPS-WSF6', 'PROMO_NETHERWHELP'),
    ('XCTZ-NT6T-K9PC-U6MT', 'PROMO_NETHERWHELP'),
    ('9K4D-CPB6-25HD-T7R9', 'PROMO_NETHERWHELP'),
    ('KXD6-Y5BN-TWRJ-62N9', 'PROMO_NETHERWHELP'),
    ('H8FB-YKCJ-RKUK-K6R2', 'PROMO_NETHERWHELP'),
    ('JNUD-JVRF-8YX8-PDMS', 'PROMO_NETHERWHELP'),
    ('NFPV-MP9K-RQFE-7DK3', 'PROMO_NETHERWHELP'),
    ('GRSB-E9QE-YPFK-XPYM', 'PROMO_NETHERWHELP');

-- PROMO_FROSTYS_COLLAR  (Frosty's Collar)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('2T6X-78DG-5RRG-RRNH', 'PROMO_FROSTYS_COLLAR'),
    ('MUQZ-YNA7-MC4K-G3DX', 'PROMO_FROSTYS_COLLAR'),
    ('MSDN-KX3N-CUHE-2A4F', 'PROMO_FROSTYS_COLLAR'),
    ('8UX7-942S-7CDK-9UM3', 'PROMO_FROSTYS_COLLAR'),
    ('7GQN-2BNR-7W9H-6S5N', 'PROMO_FROSTYS_COLLAR'),
    ('AV3D-ZFSB-C38W-63RF', 'PROMO_FROSTYS_COLLAR'),
    ('RYM9-GH6G-Y7JB-2SKB', 'PROMO_FROSTYS_COLLAR'),
    ('9S7U-6QR8-PCAR-7QQD', 'PROMO_FROSTYS_COLLAR'),
    ('UHUA-2V2Q-HPKS-QFB7', 'PROMO_FROSTYS_COLLAR'),
    ('CYFP-A9JU-DFMZ-KJEY', 'PROMO_FROSTYS_COLLAR'),
    ('2MT7-ESPK-KT6R-4DZE', 'PROMO_FROSTYS_COLLAR'),
    ('A4G6-8CQ7-XMJD-Z9P8', 'PROMO_FROSTYS_COLLAR'),
    ('AUGQ-799K-HETH-SVPH', 'PROMO_FROSTYS_COLLAR'),
    ('48WZ-2D2K-7KRX-7SGZ', 'PROMO_FROSTYS_COLLAR'),
    ('55N9-HS2P-T5C7-98CD', 'PROMO_FROSTYS_COLLAR'),
    ('FUX8-5PPT-KDKD-SVMW', 'PROMO_FROSTYS_COLLAR'),
    ('HECB-3UGC-Z4XF-ZP7S', 'PROMO_FROSTYS_COLLAR'),
    ('5U6K-TN5Y-D4R4-T7RB', 'PROMO_FROSTYS_COLLAR'),
    ('9DJB-89NU-5HDC-T9RQ', 'PROMO_FROSTYS_COLLAR'),
    ('M56D-UX45-36CQ-57Z3', 'PROMO_FROSTYS_COLLAR');

-- PROMO_WARBOT_KEY  (Warbot Ignition Key)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('BBEZ-QY9Q-RKEQ-8KAW', 'PROMO_WARBOT_KEY'),
    ('MCPG-9BXK-QEBB-9ZD9', 'PROMO_WARBOT_KEY'),
    ('RF2U-VT39-TT77-VEW5', 'PROMO_WARBOT_KEY'),
    ('UTF3-6YNA-4VTQ-97TJ', 'PROMO_WARBOT_KEY'),
    ('CE3Y-5GGA-WVUZ-BKXZ', 'PROMO_WARBOT_KEY'),
    ('SPHE-KYB8-NTAH-EEDD', 'PROMO_WARBOT_KEY'),
    ('QTE3-WXMS-XYYU-AQKJ', 'PROMO_WARBOT_KEY'),
    ('D7PB-B24D-5F97-CMXH', 'PROMO_WARBOT_KEY'),
    ('SA3Y-CURH-7GD3-9XDK', 'PROMO_WARBOT_KEY'),
    ('HDNF-E594-WBPG-9Y3V', 'PROMO_WARBOT_KEY'),
    ('N96Y-HTU5-UN7F-ZB2B', 'PROMO_WARBOT_KEY'),
    ('6R29-8AAC-39AJ-TDJP', 'PROMO_WARBOT_KEY'),
    ('3TBW-FAYF-WKUZ-U6N8', 'PROMO_WARBOT_KEY'),
    ('3BRE-5CZM-EYA5-5EW9', 'PROMO_WARBOT_KEY'),
    ('BECG-BBCT-723H-X7Z2', 'PROMO_WARBOT_KEY'),
    ('XVNW-ZNR3-QRKR-QC2T', 'PROMO_WARBOT_KEY'),
    ('KFY8-KR6E-JK8P-VM7J', 'PROMO_WARBOT_KEY'),
    ('45WM-RCHX-WH9N-EETD', 'PROMO_WARBOT_KEY'),
    ('5HQ5-8GVS-75TQ-4GRD', 'PROMO_WARBOT_KEY'),
    ('W5G9-NHZK-7EWD-FZZM', 'PROMO_WARBOT_KEY');

-- PROMO_ENCHANTED_ONYX  (Enchanted Onyx)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('VX2M-WSA4-N7TX-WVW9', 'PROMO_ENCHANTED_ONYX'),
    ('9YZZ-AZM7-QCJN-PCRK', 'PROMO_ENCHANTED_ONYX'),
    ('QDDU-U8MK-9U32-6Q6K', 'PROMO_ENCHANTED_ONYX'),
    ('ZS3V-M4EG-5UP6-J9RS', 'PROMO_ENCHANTED_ONYX'),
    ('XBJ9-P9R9-JAMY-TM9Z', 'PROMO_ENCHANTED_ONYX'),
    ('JFW8-48G9-7EME-JKFH', 'PROMO_ENCHANTED_ONYX'),
    ('DKGB-PPM8-P3B6-FT5C', 'PROMO_ENCHANTED_ONYX'),
    ('KH3X-DMGG-5KR4-SMWK', 'PROMO_ENCHANTED_ONYX'),
    ('P78N-JF33-WRFQ-GW2T', 'PROMO_ENCHANTED_ONYX'),
    ('Y22D-NDGQ-5UHN-BEDX', 'PROMO_ENCHANTED_ONYX'),
    ('8BW5-PFDZ-U9K8-VVKT', 'PROMO_ENCHANTED_ONYX'),
    ('BVPF-YES5-ZA99-PVRX', 'PROMO_ENCHANTED_ONYX'),
    ('W6QC-6BGS-UDKB-J6C4', 'PROMO_ENCHANTED_ONYX'),
    ('GZM3-A7R8-RSD9-APRA', 'PROMO_ENCHANTED_ONYX'),
    ('WZC3-YS4E-EYN5-CTQW', 'PROMO_ENCHANTED_ONYX'),
    ('Q33Z-X5WT-5J6U-5PFW', 'PROMO_ENCHANTED_ONYX'),
    ('XGN6-UPZ7-KD6Y-C29W', 'PROMO_ENCHANTED_ONYX'),
    ('DEYM-24GN-ZJQ4-F76Y', 'PROMO_ENCHANTED_ONYX'),
    ('NB8J-MAHN-5YJD-S8UN', 'PROMO_ENCHANTED_ONYX'),
    ('3VEG-UGRP-45BS-AZD7', 'PROMO_ENCHANTED_ONYX');

-- PROMO_CORE_HOUND_PUP  (Core Hound Pup)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('HEGD-DBKU-WZMW-KK7A', 'PROMO_CORE_HOUND_PUP'),
    ('4YEG-2392-AFB8-YJDC', 'PROMO_CORE_HOUND_PUP'),
    ('PXQ6-ZGUW-E747-GRN2', 'PROMO_CORE_HOUND_PUP'),
    ('BNDE-9G8P-47JT-HM37', 'PROMO_CORE_HOUND_PUP'),
    ('YPBG-CBQ2-73D6-7NRB', 'PROMO_CORE_HOUND_PUP'),
    ('ZK3S-G83Z-N8EZ-G8C2', 'PROMO_CORE_HOUND_PUP'),
    ('BCH6-PMYP-ME6N-NEFY', 'PROMO_CORE_HOUND_PUP'),
    ('EYTH-8WVP-3K4U-WAS4', 'PROMO_CORE_HOUND_PUP'),
    ('7U5Q-H4TU-6YGX-49MJ', 'PROMO_CORE_HOUND_PUP'),
    ('4EC9-N8S4-J6VD-K72F', 'PROMO_CORE_HOUND_PUP'),
    ('QYVY-9823-F87E-EMRB', 'PROMO_CORE_HOUND_PUP'),
    ('89AW-PJF9-CXCY-GFVY', 'PROMO_CORE_HOUND_PUP'),
    ('E9MW-7MMG-M7M4-PM4P', 'PROMO_CORE_HOUND_PUP'),
    ('JUK9-2D6U-P6SH-8FDS', 'PROMO_CORE_HOUND_PUP'),
    ('6PX6-NX5F-F365-67ZY', 'PROMO_CORE_HOUND_PUP'),
    ('4P3S-ESFU-999V-47QG', 'PROMO_CORE_HOUND_PUP'),
    ('TYAK-8BE2-JRHU-26GZ', 'PROMO_CORE_HOUND_PUP'),
    ('R6R9-PDYR-TPU4-4ZDE', 'PROMO_CORE_HOUND_PUP'),
    ('GTGG-W7CF-6EU3-8U2S', 'PROMO_CORE_HOUND_PUP'),
    ('4X5F-83EZ-EWDC-AWKB', 'PROMO_CORE_HOUND_PUP');

-- PROMO_GRYPHON_HATCHLING  (Gryphon Hatchling)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('V5SP-P566-M9UT-W9N9', 'PROMO_GRYPHON_HATCHLING'),
    ('4EMX-ZMQE-PYTM-5CEE', 'PROMO_GRYPHON_HATCHLING'),
    ('2NX7-5STQ-HV7F-G3VF', 'PROMO_GRYPHON_HATCHLING'),
    ('8RWJ-ESU9-88NB-GS23', 'PROMO_GRYPHON_HATCHLING'),
    ('T5F7-E9E5-WFNC-TDTB', 'PROMO_GRYPHON_HATCHLING'),
    ('WV83-DUWS-JCSH-TMQV', 'PROMO_GRYPHON_HATCHLING'),
    ('KWYS-8H9E-BGDP-GCTV', 'PROMO_GRYPHON_HATCHLING'),
    ('RQ6H-8WRS-VJGV-RWUV', 'PROMO_GRYPHON_HATCHLING'),
    ('GNC3-3JMF-VPKD-JDH4', 'PROMO_GRYPHON_HATCHLING'),
    ('RZQB-46G5-PDD7-FW7C', 'PROMO_GRYPHON_HATCHLING'),
    ('5CFX-6F6Z-RBKH-XSZ6', 'PROMO_GRYPHON_HATCHLING'),
    ('8SYK-WZM6-X2JP-DN32', 'PROMO_GRYPHON_HATCHLING'),
    ('F9W3-DRJF-V32H-67MU', 'PROMO_GRYPHON_HATCHLING'),
    ('5VK3-K8K9-PW4Y-ZYVA', 'PROMO_GRYPHON_HATCHLING'),
    ('R5RA-2U2A-F74C-PFV9', 'PROMO_GRYPHON_HATCHLING'),
    ('HTGH-7ZZM-46XK-D8CN', 'PROMO_GRYPHON_HATCHLING'),
    ('44PU-TCGA-WSXV-6HHN', 'PROMO_GRYPHON_HATCHLING'),
    ('GH58-X9F6-XBMV-9VYQ', 'PROMO_GRYPHON_HATCHLING'),
    ('E7HE-YHBE-SZM4-JQNK', 'PROMO_GRYPHON_HATCHLING'),
    ('FJMD-PXAW-QRAK-CDGS', 'PROMO_GRYPHON_HATCHLING');

-- PROMO_WIND_RIDER_CUB  (Wind Rider Cub)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('MJUS-6NX3-23GD-ENBB', 'PROMO_WIND_RIDER_CUB'),
    ('KFCJ-598E-5MGU-J8BW', 'PROMO_WIND_RIDER_CUB'),
    ('6HBD-F8C3-AK7S-W8XM', 'PROMO_WIND_RIDER_CUB'),
    ('9XSR-H76D-TUFQ-4MBU', 'PROMO_WIND_RIDER_CUB'),
    ('W3VB-ECNB-FF4N-ZD3E', 'PROMO_WIND_RIDER_CUB'),
    ('RC7F-68KT-7KK4-J83F', 'PROMO_WIND_RIDER_CUB'),
    ('P4ZF-WWNY-G327-RDC9', 'PROMO_WIND_RIDER_CUB'),
    ('AFT3-HQ3B-YMUS-N7UP', 'PROMO_WIND_RIDER_CUB'),
    ('DH9V-SNHN-M8NJ-AW25', 'PROMO_WIND_RIDER_CUB'),
    ('4ZAX-TYP6-BUQ2-RT2X', 'PROMO_WIND_RIDER_CUB'),
    ('ZNHM-8PPF-7DK8-8BF8', 'PROMO_WIND_RIDER_CUB'),
    ('VCS7-W853-HM33-C56U', 'PROMO_WIND_RIDER_CUB'),
    ('NRG2-GS4Y-YQJW-RQM7', 'PROMO_WIND_RIDER_CUB'),
    ('NK27-JRMA-33QB-DFJ5', 'PROMO_WIND_RIDER_CUB'),
    ('9MQS-ZF2E-BRMH-5U7B', 'PROMO_WIND_RIDER_CUB'),
    ('473T-BXA7-DVAF-DAQF', 'PROMO_WIND_RIDER_CUB'),
    ('PXCY-N6DT-6EF2-XRY6', 'PROMO_WIND_RIDER_CUB'),
    ('P7QX-Q9UC-9RXY-V8J4', 'PROMO_WIND_RIDER_CUB'),
    ('DBCA-7G6Y-AF8M-RM93', 'PROMO_WIND_RIDER_CUB'),
    ('DMX4-UNMJ-PNC2-YSH7', 'PROMO_WIND_RIDER_CUB');

-- PROMO_PANDAREN_MONK  (Pandaren Monk)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('TJBW-AU5U-TQ9J-P57N', 'PROMO_PANDAREN_MONK'),
    ('5UVE-WHVM-A4GN-DQQE', 'PROMO_PANDAREN_MONK'),
    ('ARAJ-SABX-NMXK-H4SS', 'PROMO_PANDAREN_MONK'),
    ('5586-4RXC-MHKR-4GGE', 'PROMO_PANDAREN_MONK'),
    ('W9U8-KYU2-6ADU-38Y4', 'PROMO_PANDAREN_MONK'),
    ('RS5N-26RW-T3Q9-ER7G', 'PROMO_PANDAREN_MONK'),
    ('5C7T-AW9E-S78P-5PE5', 'PROMO_PANDAREN_MONK'),
    ('NU32-WZBG-SHSC-2JMY', 'PROMO_PANDAREN_MONK'),
    ('4PZB-H4YE-VMX6-8XVB', 'PROMO_PANDAREN_MONK'),
    ('EGBJ-NH85-KACT-N68C', 'PROMO_PANDAREN_MONK'),
    ('NR5G-YJSB-Y3F9-QYX9', 'PROMO_PANDAREN_MONK'),
    ('R9P6-HGCG-8HW9-98ZC', 'PROMO_PANDAREN_MONK'),
    ('TWBT-Q757-B3KF-TU82', 'PROMO_PANDAREN_MONK'),
    ('R44J-KP9T-WTRR-77ZW', 'PROMO_PANDAREN_MONK'),
    ('QWRB-DGVR-SH7Q-PT75', 'PROMO_PANDAREN_MONK'),
    ('CTSW-7VGZ-BJ5V-R32H', 'PROMO_PANDAREN_MONK'),
    ('777C-9YWR-TURD-A9BV', 'PROMO_PANDAREN_MONK'),
    ('Q82Q-TQMB-FYCP-23S3', 'PROMO_PANDAREN_MONK'),
    ('XXE8-V5QW-NNEX-JNYS', 'PROMO_PANDAREN_MONK'),
    ('3JDQ-BTYK-QZKC-BKHN', 'PROMO_PANDAREN_MONK');

-- PROMO_TYRAELS_HILT  (Tyrael's Hilt)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('7V4R-X4ED-SM6D-JWKA', 'PROMO_TYRAELS_HILT'),
    ('YSGR-E8B9-U5A2-MKW2', 'PROMO_TYRAELS_HILT'),
    ('SZYD-X9UP-YPZW-7SVN', 'PROMO_TYRAELS_HILT'),
    ('HU2J-GEHR-WF9X-7TQR', 'PROMO_TYRAELS_HILT'),
    ('5SEU-SH2E-2D9D-5SFR', 'PROMO_TYRAELS_HILT'),
    ('QWZK-HXUX-692R-3M4M', 'PROMO_TYRAELS_HILT'),
    ('PHVV-B6E2-H3PA-JF2U', 'PROMO_TYRAELS_HILT'),
    ('Y9C4-RN83-AQJX-H2QE', 'PROMO_TYRAELS_HILT'),
    ('5B9N-GRR9-8R36-W4H9', 'PROMO_TYRAELS_HILT'),
    ('HUZM-BUVZ-X4MT-EUH8', 'PROMO_TYRAELS_HILT'),
    ('K5EM-4KNQ-QZ7U-6F5M', 'PROMO_TYRAELS_HILT'),
    ('ZUNK-3ZYS-Z6CB-7U3V', 'PROMO_TYRAELS_HILT'),
    ('ZMEX-YY9H-TDWV-N7ET', 'PROMO_TYRAELS_HILT'),
    ('XHWD-95Z9-EYWQ-6UDE', 'PROMO_TYRAELS_HILT'),
    ('CFUJ-45WD-EU5B-6SS7', 'PROMO_TYRAELS_HILT'),
    ('JKFW-755Y-ZRBW-Q7QD', 'PROMO_TYRAELS_HILT'),
    ('N97B-46P8-T4NW-REAZ', 'PROMO_TYRAELS_HILT'),
    ('EY57-V2AU-RMMD-D59N', 'PROMO_TYRAELS_HILT'),
    ('W3NY-RB7Y-JKB2-W23M', 'PROMO_TYRAELS_HILT'),
    ('F976-WBNZ-EFPW-3YN3', 'PROMO_TYRAELS_HILT');

-- PROMO_LIL_PHYLACTERY  (Lil' Phylactery)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('Z56D-BR3H-NJRP-RBWU', 'PROMO_LIL_PHYLACTERY'),
    ('FXWZ-THR9-AT5M-AV2C', 'PROMO_LIL_PHYLACTERY'),
    ('HFDC-UYUX-9BSQ-H3YF', 'PROMO_LIL_PHYLACTERY'),
    ('CDKR-FK4E-WVTW-QSW5', 'PROMO_LIL_PHYLACTERY'),
    ('RAC6-DQZS-KWNP-HPDQ', 'PROMO_LIL_PHYLACTERY'),
    ('J53W-RDYW-JZ7Q-QE2Y', 'PROMO_LIL_PHYLACTERY'),
    ('6NWQ-9BRH-JCX4-SA49', 'PROMO_LIL_PHYLACTERY'),
    ('USSB-PN2J-2V5S-SVBJ', 'PROMO_LIL_PHYLACTERY'),
    ('85S8-YM99-F93A-5M6H', 'PROMO_LIL_PHYLACTERY'),
    ('48WV-EF52-CADJ-SGQX', 'PROMO_LIL_PHYLACTERY'),
    ('NKQN-PDBZ-7YGN-YE7P', 'PROMO_LIL_PHYLACTERY'),
    ('D9FY-U2RA-PTRP-8UM4', 'PROMO_LIL_PHYLACTERY'),
    ('7W46-K2BN-CDR7-JNYJ', 'PROMO_LIL_PHYLACTERY'),
    ('57B5-N398-XFVW-A52M', 'PROMO_LIL_PHYLACTERY'),
    ('CF3J-ZXA2-ENHQ-WJ3K', 'PROMO_LIL_PHYLACTERY'),
    ('BCE9-MEB7-E98U-RR9X', 'PROMO_LIL_PHYLACTERY'),
    ('9NBP-XKSD-769F-3MWY', 'PROMO_LIL_PHYLACTERY'),
    ('XVP6-H3UY-J6Q4-9G9C', 'PROMO_LIL_PHYLACTERY'),
    ('T3JG-6RNW-J26J-U7DY', 'PROMO_LIL_PHYLACTERY'),
    ('9R8R-MPQG-VWDC-NXRR', 'PROMO_LIL_PHYLACTERY');

-- PROMO_LIL_XT  (Lil' XT)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('E2KG-KMRE-DYXZ-VAH2', 'PROMO_LIL_XT'),
    ('S7Z3-97UV-G7CT-RXT6', 'PROMO_LIL_XT'),
    ('TK2K-GFCB-8CTG-79MB', 'PROMO_LIL_XT'),
    ('TZS2-KMAV-ACSD-N3NB', 'PROMO_LIL_XT'),
    ('XDAR-H33G-3H6B-FSQA', 'PROMO_LIL_XT'),
    ('H4UH-DFMD-BS9J-ANZY', 'PROMO_LIL_XT'),
    ('Q2EG-SE7G-J685-DTTE', 'PROMO_LIL_XT'),
    ('HK2B-5C42-CTCW-5G9V', 'PROMO_LIL_XT'),
    ('ZNWG-7XUA-92XM-SM5F', 'PROMO_LIL_XT'),
    ('R3VN-UFHU-4MGV-MXGE', 'PROMO_LIL_XT'),
    ('PTUF-VCG3-3J8G-3M9A', 'PROMO_LIL_XT'),
    ('K34B-88U8-G6BS-FQRZ', 'PROMO_LIL_XT'),
    ('CN67-98NX-YMAQ-N58A', 'PROMO_LIL_XT'),
    ('QQKB-M7MT-UBJ9-NFMA', 'PROMO_LIL_XT'),
    ('K8YS-5SUY-G2AR-PFNQ', 'PROMO_LIL_XT'),
    ('MHAM-T8V7-QF84-AAGU', 'PROMO_LIL_XT'),
    ('ATBR-PXAR-22W7-Y2DD', 'PROMO_LIL_XT'),
    ('J6BG-F2TE-6EZF-XDUN', 'PROMO_LIL_XT'),
    ('QT3D-XEW6-7ARK-KE49', 'PROMO_LIL_XT'),
    ('AP6Q-EAFF-TK5K-Z8VZ', 'PROMO_LIL_XT');

-- PROMO_MINI_THOR  (Mini Thor)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('SWCT-987E-7RYX-M3BG', 'PROMO_MINI_THOR'),
    ('9DW4-TP29-WJGC-SH2N', 'PROMO_MINI_THOR'),
    ('N4HK-FHMZ-G8WK-9NZA', 'PROMO_MINI_THOR'),
    ('79N9-AN7G-5UZ6-5Z83', 'PROMO_MINI_THOR'),
    ('UW29-M9U7-SNY7-TSZU', 'PROMO_MINI_THOR'),
    ('ZQZG-CMFW-4E64-H8ZA', 'PROMO_MINI_THOR'),
    ('NFBA-84CN-644Y-CP6V', 'PROMO_MINI_THOR'),
    ('9GM8-DKV6-F625-DYVE', 'PROMO_MINI_THOR'),
    ('DHY4-STAF-J6XN-A2MZ', 'PROMO_MINI_THOR'),
    ('3HQ5-QE3G-CC3N-AW3Q', 'PROMO_MINI_THOR'),
    ('4AW2-FZEE-ZUYR-HRVS', 'PROMO_MINI_THOR'),
    ('HG6T-UZJG-ZTKN-96KX', 'PROMO_MINI_THOR'),
    ('6GHV-KR6V-82NF-3NED', 'PROMO_MINI_THOR'),
    ('CMEW-QF4D-BW4B-UMSP', 'PROMO_MINI_THOR'),
    ('FZMD-KGBR-WX36-MUFS', 'PROMO_MINI_THOR'),
    ('QWF4-KSYB-UZZM-CB6G', 'PROMO_MINI_THOR'),
    ('HSNZ-T7D6-RQP8-E3S4', 'PROMO_MINI_THOR'),
    ('C3RN-X6T9-FYQJ-TYHU', 'PROMO_MINI_THOR'),
    ('GNGF-GRF6-6U7W-9VXK', 'PROMO_MINI_THOR'),
    ('Y6J5-4RXT-PEXQ-ZADF', 'PROMO_MINI_THOR');

-- PROMO_ONYXIAN_WHELPLING  (Onyxian Whelpling)
-- Generated: 2026-10-03 02:30:18 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('BS8T-TAFU-5TQE-V8TG', 'PROMO_ONYXIAN_WHELPLING'),
    ('JMBR-BQFK-A3TG-PMJB', 'PROMO_ONYXIAN_WHELPLING'),
    ('TYNV-NJPF-MVQV-ZYWS', 'PROMO_ONYXIAN_WHELPLING'),
    ('D9UM-2PJP-ZK2M-6XKV', 'PROMO_ONYXIAN_WHELPLING'),
    ('V64C-83VB-2Y94-VFKG', 'PROMO_ONYXIAN_WHELPLING'),
    ('BK82-8XZ4-PVBR-NG6A', 'PROMO_ONYXIAN_WHELPLING'),
    ('CF2V-NRV5-Y4YQ-CX63', 'PROMO_ONYXIAN_WHELPLING'),
    ('YSWY-8F59-2E5X-4G7J', 'PROMO_ONYXIAN_WHELPLING'),
    ('U6BJ-KDUZ-G3BJ-XCHF', 'PROMO_ONYXIAN_WHELPLING'),
    ('AZ5B-UGM6-GBCX-SMQG', 'PROMO_ONYXIAN_WHELPLING'),
    ('9BR6-C43P-PE6C-F42S', 'PROMO_ONYXIAN_WHELPLING'),
    ('4EGK-6D7K-B5WF-9DH8', 'PROMO_ONYXIAN_WHELPLING'),
    ('ZV48-EDGA-JB47-5DUN', 'PROMO_ONYXIAN_WHELPLING'),
    ('6Y8N-8EP3-377N-7C3F', 'PROMO_ONYXIAN_WHELPLING'),
    ('NNN5-UQ3C-B8SP-53WD', 'PROMO_ONYXIAN_WHELPLING'),
    ('CUX9-EZX6-U7RJ-4X2T', 'PROMO_ONYXIAN_WHELPLING'),
    ('CXPA-FGK4-52CR-87FR', 'PROMO_ONYXIAN_WHELPLING'),
    ('AEDR-FS4B-EHW5-KYN9', 'PROMO_ONYXIAN_WHELPLING'),
    ('KSDA-EDWS-4RV8-FKM2', 'PROMO_ONYXIAN_WHELPLING'),
    ('35NH-NFV5-GSKM-R4EQ', 'PROMO_ONYXIAN_WHELPLING');
