-- ============================================================
-- mod-tcg-vendors  --  Redemption Code Batch
-- Generated : 2026-10-03 09:06:39 UTC
-- Groups    : 70
-- Total     : 1400 codes
-- Apply to  : characters database
-- ============================================================

-- TCG_TABARD_OF_FLAME  (Tabard of Flame)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('NZV9-YX3N-5TXD-NGJK', 'TCG_TABARD_OF_FLAME'),
    ('VD88-7NPZ-RS4C-VAY3', 'TCG_TABARD_OF_FLAME'),
    ('VSGC-MUZN-K2MG-BSW9', 'TCG_TABARD_OF_FLAME'),
    ('954J-65V7-DENX-TN2D', 'TCG_TABARD_OF_FLAME'),
    ('FBAP-FX2H-RYFZ-JBC5', 'TCG_TABARD_OF_FLAME'),
    ('4Q95-R346-J2AX-GUAW', 'TCG_TABARD_OF_FLAME'),
    ('MDUF-7X2G-M4MY-8AGU', 'TCG_TABARD_OF_FLAME'),
    ('K78T-H5XJ-8YNZ-NU3C', 'TCG_TABARD_OF_FLAME'),
    ('45Q2-ZWDJ-9GGG-KQ3A', 'TCG_TABARD_OF_FLAME'),
    ('YYAY-CDMS-2ABR-HAJ7', 'TCG_TABARD_OF_FLAME'),
    ('7GG8-K9SB-24WH-23M5', 'TCG_TABARD_OF_FLAME'),
    ('GBDT-AUWT-AHKC-F6K4', 'TCG_TABARD_OF_FLAME'),
    ('3SXJ-7KC7-KTYR-BXMJ', 'TCG_TABARD_OF_FLAME'),
    ('R37Y-PAQ5-3JRH-XW9F', 'TCG_TABARD_OF_FLAME'),
    ('27P8-TUGY-CFY6-DYQ9', 'TCG_TABARD_OF_FLAME'),
    ('9HBY-XCW3-M8BF-GXXS', 'TCG_TABARD_OF_FLAME'),
    ('45WV-QJZR-PX9E-Q3HZ', 'TCG_TABARD_OF_FLAME'),
    ('VABG-TDXQ-8YYC-6VFZ', 'TCG_TABARD_OF_FLAME'),
    ('SDUK-CMW8-JPTG-RYNR', 'TCG_TABARD_OF_FLAME'),
    ('T3WF-MKYN-UKCE-CGT4', 'TCG_TABARD_OF_FLAME');

-- TCG_HIPPOGRYPH_HATCHLING  (Hippogryph Hatchling)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('EJ3W-6VXT-FEHP-J8KX', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('53S4-6JAP-UD9W-GDZM', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('3R5T-JNPY-JTY8-YAPH', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('JUM8-WBE8-MPAB-T3VW', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('35EM-TH97-4RXV-2A55', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('8KKF-ZTMW-MCF2-NSWV', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('3X45-9M7M-3G8S-FWX9', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('87V5-WCUH-EV6R-3HTX', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('7QXQ-D6AD-W79F-776P', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('8GNT-HEN8-3BWV-YU85', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('DDWC-7Q63-7BCG-2MMH', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('G8P9-GYJV-KQ3E-74KV', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('SMEM-GVE6-Z2C2-MKUY', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('QZQP-MDZ4-KRDT-32SS', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('WZR2-Z8Y4-KVWC-N9WC', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('X3X8-R89C-ZG7U-HPSJ', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('7VY5-CN3N-6TNW-RTYT', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('G4HT-V2ZC-Q7DP-5VNH', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('X8TB-883M-DW5N-5UR9', 'TCG_HIPPOGRYPH_HATCHLING'),
    ('B3A8-VMQ5-5YX7-YS9J', 'TCG_HIPPOGRYPH_HATCHLING');

-- TCG_RIDING_TURTLE  (Riding Turtle)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('CB6P-C87X-88FJ-R6YK', 'TCG_RIDING_TURTLE'),
    ('8ARE-88Q3-Y272-BFQY', 'TCG_RIDING_TURTLE'),
    ('7HK9-6D9C-7BEC-87Y7', 'TCG_RIDING_TURTLE'),
    ('NX5R-76BE-QRYE-2EYM', 'TCG_RIDING_TURTLE'),
    ('KD54-9RJW-D5DR-BGMD', 'TCG_RIDING_TURTLE'),
    ('RX5B-8MTT-Y277-MEBE', 'TCG_RIDING_TURTLE'),
    ('9PCG-RRQQ-WCJ5-8GCW', 'TCG_RIDING_TURTLE'),
    ('CDB2-GPU4-NQMQ-TGK8', 'TCG_RIDING_TURTLE'),
    ('JCPY-B4JX-32YN-HNVP', 'TCG_RIDING_TURTLE'),
    ('B3NM-9FWT-7WUB-Z5R6', 'TCG_RIDING_TURTLE'),
    ('PR78-AHAF-6846-V4XE', 'TCG_RIDING_TURTLE'),
    ('E8CZ-UG23-DBTY-TTAZ', 'TCG_RIDING_TURTLE'),
    ('YR4J-TADC-WASC-QWYQ', 'TCG_RIDING_TURTLE'),
    ('DTNN-KGAR-6CRK-SMFJ', 'TCG_RIDING_TURTLE'),
    ('EFWQ-AKDZ-QCZG-RAVW', 'TCG_RIDING_TURTLE'),
    ('TWW7-77UA-VSUB-FUZF', 'TCG_RIDING_TURTLE'),
    ('DFBZ-42NJ-8F7M-CQEM', 'TCG_RIDING_TURTLE'),
    ('2Y6P-RCQY-NRKV-SG7U', 'TCG_RIDING_TURTLE'),
    ('5KCY-PEN5-AW5N-APAT', 'TCG_RIDING_TURTLE'),
    ('FQ4C-GCYT-ZT43-H6NG', 'TCG_RIDING_TURTLE');

-- TCG_PICNIC_BASKET  (Picnic Basket)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('DKRE-TMU3-B3PF-MJRG', 'TCG_PICNIC_BASKET'),
    ('YBFC-4Z82-GBG5-GHAE', 'TCG_PICNIC_BASKET'),
    ('MCF6-B39J-JSK3-Z4EJ', 'TCG_PICNIC_BASKET'),
    ('2BPU-TKB3-8652-FQHU', 'TCG_PICNIC_BASKET'),
    ('WHAG-KRYG-KZTH-3HEC', 'TCG_PICNIC_BASKET'),
    ('BN73-JUFN-J4CH-P4Y7', 'TCG_PICNIC_BASKET'),
    ('424K-4CED-FX28-B34G', 'TCG_PICNIC_BASKET'),
    ('4TZY-582R-XRJB-55A3', 'TCG_PICNIC_BASKET'),
    ('U549-SHCA-8AK9-VN8K', 'TCG_PICNIC_BASKET'),
    ('NZ6D-DBYX-UXXF-FCXM', 'TCG_PICNIC_BASKET'),
    ('B5HR-KAZC-NR3U-FQ9J', 'TCG_PICNIC_BASKET'),
    ('H6V6-A7AY-5NF8-NY3W', 'TCG_PICNIC_BASKET'),
    ('SMXH-SUS3-2ZDW-JNRC', 'TCG_PICNIC_BASKET'),
    ('3RNF-77CS-5AKC-7J9R', 'TCG_PICNIC_BASKET'),
    ('JGH6-ESKC-6DX4-SGCT', 'TCG_PICNIC_BASKET'),
    ('SU2A-UNN6-7ZYF-P5BX', 'TCG_PICNIC_BASKET'),
    ('QV56-HHQ6-CXER-Q6SP', 'TCG_PICNIC_BASKET'),
    ('KAHS-PGCP-QXM9-WR34', 'TCG_PICNIC_BASKET'),
    ('DJX6-JWVX-QS7T-7VZY', 'TCG_PICNIC_BASKET'),
    ('R7GC-CGB6-QJDS-P9ZS', 'TCG_PICNIC_BASKET');

-- TCG_BANANA_CHARM  (Banana Charm)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('R6RX-GRPQ-66QG-3R52', 'TCG_BANANA_CHARM'),
    ('KJMZ-CVKT-D26X-4KXY', 'TCG_BANANA_CHARM'),
    ('6ZUA-BCUV-R4R8-Q72R', 'TCG_BANANA_CHARM'),
    ('WQXK-T72K-2N82-MSCE', 'TCG_BANANA_CHARM'),
    ('7PGV-9G6T-B5K4-SWWM', 'TCG_BANANA_CHARM'),
    ('4BCV-WP7N-TV42-P6XH', 'TCG_BANANA_CHARM'),
    ('NHE9-6ABD-R7WB-9UQR', 'TCG_BANANA_CHARM'),
    ('EC6X-J7G7-58ZF-JR7U', 'TCG_BANANA_CHARM'),
    ('AA88-SKA6-B7GA-FW4N', 'TCG_BANANA_CHARM'),
    ('9A5S-DWQ5-J4NT-W7NG', 'TCG_BANANA_CHARM'),
    ('ZYQ6-5KN9-SY4H-XSS8', 'TCG_BANANA_CHARM'),
    ('VHEJ-HCFK-CETV-32ZK', 'TCG_BANANA_CHARM'),
    ('VMP8-PJYJ-RUXP-VCVU', 'TCG_BANANA_CHARM'),
    ('QSRV-H46T-8JX6-P9DQ', 'TCG_BANANA_CHARM'),
    ('YAYS-D4MV-DJSS-S9MM', 'TCG_BANANA_CHARM'),
    ('X5ZZ-E3DR-2WUD-4BF8', 'TCG_BANANA_CHARM'),
    ('4UW7-PNBF-WSZT-8HFK', 'TCG_BANANA_CHARM'),
    ('XZEM-3E3N-BGNS-PZP2', 'TCG_BANANA_CHARM'),
    ('HS3X-ZKAT-P7BK-UDHC', 'TCG_BANANA_CHARM'),
    ('FH5V-ZPZ4-V7UE-5YDD', 'TCG_BANANA_CHARM');

-- TCG_IMP_IN_A_BALL  (Imp in a Ball)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('GRWB-7BV5-TPEK-VG49', 'TCG_IMP_IN_A_BALL'),
    ('KTG2-NQXM-DDDG-DBSK', 'TCG_IMP_IN_A_BALL'),
    ('NEF5-PT3E-5H73-XFK5', 'TCG_IMP_IN_A_BALL'),
    ('PPWH-KAGQ-4GPN-QC9H', 'TCG_IMP_IN_A_BALL'),
    ('Y4Y7-ZQSR-SDYK-RYRR', 'TCG_IMP_IN_A_BALL'),
    ('E3GA-Z245-ZWRA-87KE', 'TCG_IMP_IN_A_BALL'),
    ('656H-KZWB-NGY5-7B82', 'TCG_IMP_IN_A_BALL'),
    ('B26C-ENC8-84TW-QZK7', 'TCG_IMP_IN_A_BALL'),
    ('JPQQ-UVXE-SRED-P5BN', 'TCG_IMP_IN_A_BALL'),
    ('HHYZ-TPAC-WDXT-N27J', 'TCG_IMP_IN_A_BALL'),
    ('THWM-3N3J-BDDR-GKGT', 'TCG_IMP_IN_A_BALL'),
    ('AGYD-DSPS-3F2J-TF4J', 'TCG_IMP_IN_A_BALL'),
    ('PCTN-SP5G-YRDC-69PU', 'TCG_IMP_IN_A_BALL'),
    ('5C8M-KRM4-R5CX-AXXB', 'TCG_IMP_IN_A_BALL'),
    ('SU5W-BCGD-AAYS-744H', 'TCG_IMP_IN_A_BALL'),
    ('R7UD-GHTW-NSAW-XBCY', 'TCG_IMP_IN_A_BALL'),
    ('B683-6AGX-3DD5-MA5G', 'TCG_IMP_IN_A_BALL'),
    ('Q5SK-JR2U-Q3F6-78JX', 'TCG_IMP_IN_A_BALL'),
    ('FNW8-GPPE-22BE-Q4YB', 'TCG_IMP_IN_A_BALL'),
    ('KGSC-Z9FF-NSQ8-CEVT', 'TCG_IMP_IN_A_BALL');

-- TCG_GOBLIN_GUMBO_KETTLE  (Goblin Gumbo Kettle)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('QCTE-42AZ-9QR2-JRCP', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('9S5V-TC9E-AC6X-SM86', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('2JE4-K2ZV-G8H7-WT7G', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('6SM6-Z3FR-6THM-XKY5', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('5FS9-ME2R-648N-GTQ3', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('BVJH-VDMC-549K-RGNF', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('9BUK-FN3Z-URN9-FGHF', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('AQKU-HPPT-WY7A-USVZ', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('ARVY-5WZ7-VZHD-HN9Q', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('X63C-X52J-S23R-XN3C', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('UNAQ-6W48-QS8R-6Y6H', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('SUHY-CWS5-9ZRG-N5C5', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('T22N-8MMW-FXMK-K7F7', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('D7QD-HTR3-WGBJ-4YR6', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('M8BB-T9VH-4YRU-WC8D', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('KQDE-7VF7-SSZ3-DXZX', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('6SN6-9TFB-RFQN-9VF7', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('D8PZ-DW4H-FFQE-PTFV', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('K6Y3-EVZT-R7CS-CC77', 'TCG_GOBLIN_GUMBO_KETTLE'),
    ('4EQ6-CUQY-T867-D3UA', 'TCG_GOBLIN_GUMBO_KETTLE');

-- TCG_FISHING_CHAIR  (Fishing Chair)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('ZYY5-66RE-P9X9-KYU9', 'TCG_FISHING_CHAIR'),
    ('B5VU-8VWX-63RD-EMGD', 'TCG_FISHING_CHAIR'),
    ('Q99H-YN8W-Z9TG-3HM9', 'TCG_FISHING_CHAIR'),
    ('K8XK-VQNZ-YNUD-JUFW', 'TCG_FISHING_CHAIR'),
    ('ACDD-26Y2-K9HJ-GQCQ', 'TCG_FISHING_CHAIR'),
    ('XWD3-4YTV-7FY7-HA2K', 'TCG_FISHING_CHAIR'),
    ('UUGN-3Q4A-9XZZ-RUC8', 'TCG_FISHING_CHAIR'),
    ('9XCD-A9DR-3Y8U-2EEE', 'TCG_FISHING_CHAIR'),
    ('RPP6-EJA5-6C84-W5NT', 'TCG_FISHING_CHAIR'),
    ('C5F8-7VTX-B6QB-SSTB', 'TCG_FISHING_CHAIR'),
    ('NQUP-AV7D-9H4T-YZHU', 'TCG_FISHING_CHAIR'),
    ('SPRX-KN7W-FTH8-8VQK', 'TCG_FISHING_CHAIR'),
    ('CZ8T-VH7H-863P-JCV7', 'TCG_FISHING_CHAIR'),
    ('NY6Q-J7ZF-YM8M-QM62', 'TCG_FISHING_CHAIR'),
    ('AZW2-RTCD-4F22-DMBU', 'TCG_FISHING_CHAIR'),
    ('HN86-T7PU-KR99-SN7S', 'TCG_FISHING_CHAIR'),
    ('S9Z8-G2GH-NXF5-XVW6', 'TCG_FISHING_CHAIR'),
    ('3KQX-FQCB-8N2V-RV72', 'TCG_FISHING_CHAIR'),
    ('9BPS-MWGR-RUEZ-KVTP', 'TCG_FISHING_CHAIR'),
    ('DUPV-H3R2-QZ3A-CFRB', 'TCG_FISHING_CHAIR');

-- TCG_SPECTRAL_TIGER  (Reins of the Spectral Tiger (both variants))
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('STYK-XGNB-XWEV-H7Q8', 'TCG_SPECTRAL_TIGER'),
    ('EACG-W7KD-G3CX-U96C', 'TCG_SPECTRAL_TIGER'),
    ('RYCG-PJTF-3UFJ-GMPT', 'TCG_SPECTRAL_TIGER'),
    ('8X8F-WQC5-FXNA-TH5D', 'TCG_SPECTRAL_TIGER'),
    ('5WSD-EKFY-Z8MF-MA6D', 'TCG_SPECTRAL_TIGER'),
    ('477Y-3VH7-DJ8X-J3Y2', 'TCG_SPECTRAL_TIGER'),
    ('7R66-BDYQ-JMDU-DYK4', 'TCG_SPECTRAL_TIGER'),
    ('BX4K-T2PZ-68XA-DDXJ', 'TCG_SPECTRAL_TIGER'),
    ('BBTN-V25P-P3AF-8CF2', 'TCG_SPECTRAL_TIGER'),
    ('P5C2-AG5H-AWSG-MS3D', 'TCG_SPECTRAL_TIGER'),
    ('9VGQ-ZE2W-Z67B-VQWX', 'TCG_SPECTRAL_TIGER'),
    ('7KGX-DZ6C-QEW5-4Y4F', 'TCG_SPECTRAL_TIGER'),
    ('CV4B-BEAN-UF7B-AQFY', 'TCG_SPECTRAL_TIGER'),
    ('FPVE-D5CZ-UKZE-CZ4F', 'TCG_SPECTRAL_TIGER'),
    ('74PV-FY89-BQPG-SY2V', 'TCG_SPECTRAL_TIGER'),
    ('WWMJ-7K9A-D8UF-PGSQ', 'TCG_SPECTRAL_TIGER'),
    ('S2U2-PD3J-CMY3-FRP6', 'TCG_SPECTRAL_TIGER'),
    ('RR4X-MXGV-4BFS-EX6M', 'TCG_SPECTRAL_TIGER'),
    ('2TNC-3TQX-CNKV-BRTS', 'TCG_SPECTRAL_TIGER'),
    ('KPS8-Q9SZ-BCWV-YSXS', 'TCG_SPECTRAL_TIGER');

-- TCG_PAPER_FLYING_MACHINE  (Paper Flying Machine Kit)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('YTNV-WN6W-KKJJ-Z4XQ', 'TCG_PAPER_FLYING_MACHINE'),
    ('4CHR-6W3U-248W-28X4', 'TCG_PAPER_FLYING_MACHINE'),
    ('NYV5-5GBT-W5YZ-ENES', 'TCG_PAPER_FLYING_MACHINE'),
    ('P4KG-QNXU-ARXU-JY8M', 'TCG_PAPER_FLYING_MACHINE'),
    ('52QZ-SHKT-CZHE-GUFH', 'TCG_PAPER_FLYING_MACHINE'),
    ('JQSJ-BNQJ-5MQ7-V2KY', 'TCG_PAPER_FLYING_MACHINE'),
    ('GG6K-ACJY-2VZE-4U36', 'TCG_PAPER_FLYING_MACHINE'),
    ('R4U2-68DJ-4YUJ-B9F5', 'TCG_PAPER_FLYING_MACHINE'),
    ('8CE9-G8B7-JT84-VMWF', 'TCG_PAPER_FLYING_MACHINE'),
    ('7G6M-RVRX-D8XH-MHQU', 'TCG_PAPER_FLYING_MACHINE'),
    ('2PHS-A5DH-JDWG-DU85', 'TCG_PAPER_FLYING_MACHINE'),
    ('E4AZ-W6Y8-T25R-FPHY', 'TCG_PAPER_FLYING_MACHINE'),
    ('WBQK-R56D-XZC7-J5KG', 'TCG_PAPER_FLYING_MACHINE'),
    ('MARD-GTB2-CHKQ-W6W3', 'TCG_PAPER_FLYING_MACHINE'),
    ('GXQZ-H3HM-ZT5S-YHVH', 'TCG_PAPER_FLYING_MACHINE'),
    ('ZRK5-BE5V-N45E-B8HF', 'TCG_PAPER_FLYING_MACHINE'),
    ('8A4B-Z96N-2HMK-25RM', 'TCG_PAPER_FLYING_MACHINE'),
    ('7HFT-G93J-TM6E-FZH7', 'TCG_PAPER_FLYING_MACHINE'),
    ('BTSE-PWVU-KFST-RYVH', 'TCG_PAPER_FLYING_MACHINE'),
    ('2RRQ-342W-KGDX-ET57', 'TCG_PAPER_FLYING_MACHINE');

-- TCG_ROCKET_CHICKEN  (Rocket Chicken)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('9MYW-FZ26-864W-8GJC', 'TCG_ROCKET_CHICKEN'),
    ('Q69H-M55T-PV8T-BEBV', 'TCG_ROCKET_CHICKEN'),
    ('GRFE-TH56-8TWW-VBZG', 'TCG_ROCKET_CHICKEN'),
    ('T98U-DPDT-7E89-5C9Z', 'TCG_ROCKET_CHICKEN'),
    ('9RJY-9VCQ-URCR-GGQK', 'TCG_ROCKET_CHICKEN'),
    ('NDWJ-W47H-DH9Z-GN9Y', 'TCG_ROCKET_CHICKEN'),
    ('VBM6-7RTE-U378-HUCD', 'TCG_ROCKET_CHICKEN'),
    ('GRMJ-9SUA-MHV7-4HPD', 'TCG_ROCKET_CHICKEN'),
    ('78M5-BXQ8-H8UQ-A5PB', 'TCG_ROCKET_CHICKEN'),
    ('66M4-ARHQ-XXB5-JRV5', 'TCG_ROCKET_CHICKEN'),
    ('YEEF-3UKJ-K7S9-YK9Y', 'TCG_ROCKET_CHICKEN'),
    ('CFAU-K3BJ-3553-QBSR', 'TCG_ROCKET_CHICKEN'),
    ('6PQE-APAX-VNZB-64K5', 'TCG_ROCKET_CHICKEN'),
    ('VC3E-MG9G-J9YF-5BQD', 'TCG_ROCKET_CHICKEN'),
    ('YF6V-CTHY-JJSV-JK96', 'TCG_ROCKET_CHICKEN'),
    ('RBGU-EZD2-A38V-ZMU5', 'TCG_ROCKET_CHICKEN'),
    ('54PT-WV4E-SCF6-BBWK', 'TCG_ROCKET_CHICKEN'),
    ('GP9U-FHR8-2A2Z-X2Q7', 'TCG_ROCKET_CHICKEN'),
    ('N4MC-7WC6-2CAV-ZTQ9', 'TCG_ROCKET_CHICKEN'),
    ('99BV-FDSF-A4J9-ENYB', 'TCG_ROCKET_CHICKEN');

-- TCG_DRAGON_KITE  (Dragon Kite)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('2RXR-H8VQ-NHQM-GJRB', 'TCG_DRAGON_KITE'),
    ('SA6N-5RZC-XHUQ-B2J8', 'TCG_DRAGON_KITE'),
    ('USJN-Z4DN-MBGQ-RWEH', 'TCG_DRAGON_KITE'),
    ('SNJ7-VNHP-CHSA-2ARB', 'TCG_DRAGON_KITE'),
    ('2EAW-5ZD8-HQZP-FJMV', 'TCG_DRAGON_KITE'),
    ('JGMA-RK6R-Q6VM-VCQR', 'TCG_DRAGON_KITE'),
    ('U88Y-KFQQ-G9D8-FZUA', 'TCG_DRAGON_KITE'),
    ('VTCZ-WHBU-YUDV-VQ2E', 'TCG_DRAGON_KITE'),
    ('S7WA-HZX8-W8XJ-KP2F', 'TCG_DRAGON_KITE'),
    ('FFBG-7PBX-K8BA-NXUG', 'TCG_DRAGON_KITE'),
    ('9AHT-E7YT-S39Y-USDF', 'TCG_DRAGON_KITE'),
    ('2XJU-MYBX-7KCW-6EPE', 'TCG_DRAGON_KITE'),
    ('M4Y3-MYJY-59WK-QN7A', 'TCG_DRAGON_KITE'),
    ('EWXH-8NDF-MDFA-UAPW', 'TCG_DRAGON_KITE'),
    ('N8CF-VFWQ-FXRN-X9QV', 'TCG_DRAGON_KITE'),
    ('WHFN-EGJ5-39YS-TPNR', 'TCG_DRAGON_KITE'),
    ('KFM7-YE9S-A6XP-ZMAE', 'TCG_DRAGON_KITE'),
    ('2SP3-QFHS-B7A8-6NSA', 'TCG_DRAGON_KITE'),
    ('4WZE-AGZZ-3GEP-EVWA', 'TCG_DRAGON_KITE'),
    ('Q9GJ-X52N-R5G9-D7MH', 'TCG_DRAGON_KITE');

-- TCG_X51_NETHER_ROCKET  (X-51 Nether-Rocket (both variants))
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('AZ5F-ET98-E72B-GMZE', 'TCG_X51_NETHER_ROCKET'),
    ('E4TV-SFKB-AZ7K-CAYD', 'TCG_X51_NETHER_ROCKET'),
    ('32A6-7U5B-5VJ3-4C7M', 'TCG_X51_NETHER_ROCKET'),
    ('Y6EB-9M3V-Q9TX-V5B3', 'TCG_X51_NETHER_ROCKET'),
    ('EPUP-UCZH-KTT4-8JBC', 'TCG_X51_NETHER_ROCKET'),
    ('8FKK-YSMX-9XQ3-6KRX', 'TCG_X51_NETHER_ROCKET'),
    ('EA99-XZYM-MYEB-VXSE', 'TCG_X51_NETHER_ROCKET'),
    ('YWET-XFHT-BZK4-NNXP', 'TCG_X51_NETHER_ROCKET'),
    ('RWZ6-XRSA-GRYX-WNVN', 'TCG_X51_NETHER_ROCKET'),
    ('PJWQ-C8KU-49EE-4TWQ', 'TCG_X51_NETHER_ROCKET'),
    ('HHDD-KBFU-SF4T-M6P8', 'TCG_X51_NETHER_ROCKET'),
    ('QWAJ-VCV3-ZEPZ-XP9E', 'TCG_X51_NETHER_ROCKET'),
    ('HHKF-A4PV-2H8A-4Y4T', 'TCG_X51_NETHER_ROCKET'),
    ('XQ4B-AJBB-BX4T-GSG6', 'TCG_X51_NETHER_ROCKET'),
    ('4GTP-AJCW-X9D5-XKEG', 'TCG_X51_NETHER_ROCKET'),
    ('59Q8-KF2P-47R4-6NBK', 'TCG_X51_NETHER_ROCKET'),
    ('ZSUE-BNJ5-EHPV-5S2Q', 'TCG_X51_NETHER_ROCKET'),
    ('DXYU-RVQU-37B9-N98T', 'TCG_X51_NETHER_ROCKET'),
    ('MCT3-UXJU-D5ZR-ABY2', 'TCG_X51_NETHER_ROCKET'),
    ('GRVS-K2RK-B93R-X2Z3', 'TCG_X51_NETHER_ROCKET');

-- TCG_PET_BISCUIT  (Papa Hummel's Old-Fashioned Pet Biscuit)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('83ZT-754G-P665-UHFQ', 'TCG_PET_BISCUIT'),
    ('EKRW-JE88-N6E4-AJKG', 'TCG_PET_BISCUIT'),
    ('7YZX-F87W-G5N6-CMK3', 'TCG_PET_BISCUIT'),
    ('2H4T-889N-JV87-4JFA', 'TCG_PET_BISCUIT'),
    ('JNU5-GTGM-NZ4Y-PSJY', 'TCG_PET_BISCUIT'),
    ('3SVA-S9CK-GV95-G4J7', 'TCG_PET_BISCUIT'),
    ('6MKW-DVMW-AHUY-M5G4', 'TCG_PET_BISCUIT'),
    ('VQ4X-6ZGZ-GQ2K-UCFG', 'TCG_PET_BISCUIT'),
    ('8WR7-ZXJH-CK45-ZGFX', 'TCG_PET_BISCUIT'),
    ('4MF3-BJA5-8UZS-NP8R', 'TCG_PET_BISCUIT'),
    ('SKMF-TJ85-FCRY-RQYG', 'TCG_PET_BISCUIT'),
    ('6PMR-Z4V4-BZKG-WARS', 'TCG_PET_BISCUIT'),
    ('A42N-7398-BW38-BDXW', 'TCG_PET_BISCUIT'),
    ('E9RD-RBNG-B3A4-PPXN', 'TCG_PET_BISCUIT'),
    ('4NK6-EY2A-WYPY-WHXH', 'TCG_PET_BISCUIT'),
    ('VNBT-AAHV-7HX2-8P2M', 'TCG_PET_BISCUIT'),
    ('5P6A-4DS4-QMCB-QWNS', 'TCG_PET_BISCUIT'),
    ('XAP5-S4CV-2GJH-F5ZC', 'TCG_PET_BISCUIT'),
    ('QJ34-SFTW-UXTB-9XCK', 'TCG_PET_BISCUIT'),
    ('56N3-PAXK-YMY4-4RZG', 'TCG_PET_BISCUIT');

-- TCG_GOBLIN_WEATHER_MACHINE  (Goblin Weather Machine - Prototype 01-B)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('7D56-NZS7-4P56-D8PF', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('UV87-YG8P-QGZ9-XZFW', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('69ES-GTKU-NBSQ-AZB7', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('U5MC-8DBA-2YRU-2SUR', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('699F-GN8W-YM3B-57QG', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('T744-3VS9-9Q7Y-ME4D', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('GHCR-648T-8M32-9NRY', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('2U96-MKHW-RPYD-CA92', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('SME4-QZAT-SKE8-5N55', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('TU9P-7T38-NXWC-6E24', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('ZJMH-4SZF-64HW-P63S', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('HFDC-6AHC-EV5H-G8DN', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('3EP5-XQJQ-JSGD-ZNEY', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('JPUW-PJUX-5AFJ-8J4F', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('FHPS-6PMU-D4W7-JHZW', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('NUKB-GANC-UMD9-ZFXB', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('Z3A3-RZ3Z-TPCR-THMT', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('HG77-KJHA-5HZ5-9T3J', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('CU2A-BNZA-WMCW-APC7', 'TCG_GOBLIN_WEATHER_MACHINE'),
    ('N29F-ME6W-EJEA-7BJX', 'TCG_GOBLIN_WEATHER_MACHINE');

-- TCG_PATH_OF_ILLIDAN  (Path of Illidan)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('TSRE-XG7S-RKVE-4UK7', 'TCG_PATH_OF_ILLIDAN'),
    ('HVKA-EN9R-3PFY-F4WF', 'TCG_PATH_OF_ILLIDAN'),
    ('EC8Z-6HBT-M959-BE9Y', 'TCG_PATH_OF_ILLIDAN'),
    ('RKDV-G7F5-XUZK-G655', 'TCG_PATH_OF_ILLIDAN'),
    ('CHRH-XRG6-UK2T-RQ76', 'TCG_PATH_OF_ILLIDAN'),
    ('8N7V-WV6X-PW2N-4S9X', 'TCG_PATH_OF_ILLIDAN'),
    ('GR7A-75J5-R2V9-FARP', 'TCG_PATH_OF_ILLIDAN'),
    ('2W56-H8GR-GPC8-BN8B', 'TCG_PATH_OF_ILLIDAN'),
    ('JKTK-SFHR-R9MY-7FCX', 'TCG_PATH_OF_ILLIDAN'),
    ('NNKM-K3BS-UKEN-RSY8', 'TCG_PATH_OF_ILLIDAN'),
    ('Y73S-V743-R9C2-YAWY', 'TCG_PATH_OF_ILLIDAN'),
    ('6A4H-Z2DY-BCVB-D64D', 'TCG_PATH_OF_ILLIDAN'),
    ('FJRB-NG2Q-UNRD-87RE', 'TCG_PATH_OF_ILLIDAN'),
    ('JFU9-DCKK-M5A8-YY5V', 'TCG_PATH_OF_ILLIDAN'),
    ('B2K6-JR78-J964-39N3', 'TCG_PATH_OF_ILLIDAN'),
    ('5JTK-ATPP-W4UC-BBX3', 'TCG_PATH_OF_ILLIDAN'),
    ('XRCQ-Q8DU-QHU2-SMGQ', 'TCG_PATH_OF_ILLIDAN'),
    ('8XPY-CQTD-U9FP-WE8E', 'TCG_PATH_OF_ILLIDAN'),
    ('M92Q-NXJV-843S-P2KS', 'TCG_PATH_OF_ILLIDAN'),
    ('3ZJJ-HXAH-7637-CA3M', 'TCG_PATH_OF_ILLIDAN');

-- TCG_DISCO  (D.I.S.C.O.)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('G2SG-7EV6-DV7E-8N7Y', 'TCG_DISCO'),
    ('FJ3B-3VRN-NRZ4-EETY', 'TCG_DISCO'),
    ('PP23-4HEU-F82G-JQPP', 'TCG_DISCO'),
    ('AWGE-HH46-UYFA-UGWD', 'TCG_DISCO'),
    ('QKNX-35EV-X6V4-SEB8', 'TCG_DISCO'),
    ('MA2W-74Z7-9UR5-AA5W', 'TCG_DISCO'),
    ('X8N5-RGHH-FYXC-PAGH', 'TCG_DISCO'),
    ('42C6-Z8QP-652E-CC4R', 'TCG_DISCO'),
    ('E4XY-2KNH-A54J-U8KG', 'TCG_DISCO'),
    ('984D-K3WD-25TF-9DDN', 'TCG_DISCO'),
    ('VDY4-VAUA-TKZQ-EJXT', 'TCG_DISCO'),
    ('AHM5-DHTR-QZDV-YFDG', 'TCG_DISCO'),
    ('4P69-66E5-5DZG-T3NZ', 'TCG_DISCO'),
    ('5MKJ-HVSZ-MUQP-8M3W', 'TCG_DISCO'),
    ('7DBH-NBKH-CY4F-W933', 'TCG_DISCO'),
    ('KKDQ-EE3H-39JZ-T7G3', 'TCG_DISCO'),
    ('JMXN-QWRW-Q3FM-HM3Q', 'TCG_DISCO'),
    ('JDBQ-PFDE-JNP3-PNFY', 'TCG_DISCO'),
    ('HDZX-VMAD-N5XF-CBV8', 'TCG_DISCO'),
    ('J773-VN6P-3VX5-ZRYN', 'TCG_DISCO');

-- TCG_SOUL_TRADER_BEACON  (Soul-Trader Beacon)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('4S6K-K5BT-RPYY-FCZU', 'TCG_SOUL_TRADER_BEACON'),
    ('J5S7-AJAF-WBZK-A9KZ', 'TCG_SOUL_TRADER_BEACON'),
    ('XUZM-J6BW-J6GK-JXSP', 'TCG_SOUL_TRADER_BEACON'),
    ('UHFS-Y4G6-JZ6F-VYDK', 'TCG_SOUL_TRADER_BEACON'),
    ('FP27-BK4M-4GVG-UVXR', 'TCG_SOUL_TRADER_BEACON'),
    ('BB4Q-3SEV-CSQA-UY9W', 'TCG_SOUL_TRADER_BEACON'),
    ('8H6D-3U9P-STAE-HZHY', 'TCG_SOUL_TRADER_BEACON'),
    ('Q4Y7-MXPX-96JP-ZZU4', 'TCG_SOUL_TRADER_BEACON'),
    ('RS5E-BNE7-PHDR-JDED', 'TCG_SOUL_TRADER_BEACON'),
    ('3SA8-ZSRD-5PVD-UBAP', 'TCG_SOUL_TRADER_BEACON'),
    ('K7ZU-25Z6-2ZYM-3J4Q', 'TCG_SOUL_TRADER_BEACON'),
    ('DWJ3-JH6C-9PYN-4XQW', 'TCG_SOUL_TRADER_BEACON'),
    ('D7EU-57CN-W4Z8-HG7G', 'TCG_SOUL_TRADER_BEACON'),
    ('8MZ9-FUYB-GJ3D-4AB8', 'TCG_SOUL_TRADER_BEACON'),
    ('FBJV-7TFN-K45F-MGK3', 'TCG_SOUL_TRADER_BEACON'),
    ('5CZ5-GEX6-8JQ3-CHRC', 'TCG_SOUL_TRADER_BEACON'),
    ('BTW2-53M9-ZKQS-XRRB', 'TCG_SOUL_TRADER_BEACON'),
    ('4EYY-NYDX-QWJE-PRNB', 'TCG_SOUL_TRADER_BEACON'),
    ('9KWE-DD78-6RUX-KP2K', 'TCG_SOUL_TRADER_BEACON'),
    ('KWME-CF4S-TFBR-YZ7T', 'TCG_SOUL_TRADER_BEACON');

-- TCG_PARTY_GRENADE  (Party G.R.E.N.A.D.E.)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('KFAG-7BX5-BT9J-7FM8', 'TCG_PARTY_GRENADE'),
    ('PSUN-MZKQ-SMQU-S5AQ', 'TCG_PARTY_GRENADE'),
    ('SN4K-YYCF-7D35-SRAH', 'TCG_PARTY_GRENADE'),
    ('ZCMG-ZYDP-WPYH-DVGT', 'TCG_PARTY_GRENADE'),
    ('D8BD-V28F-SP9P-8DEH', 'TCG_PARTY_GRENADE'),
    ('88XF-B58T-EP7E-GRCB', 'TCG_PARTY_GRENADE'),
    ('VE3N-52Q7-3JX2-ZJCC', 'TCG_PARTY_GRENADE'),
    ('45WT-8D6J-DTT8-YHVD', 'TCG_PARTY_GRENADE'),
    ('BW8J-35CN-G3KS-EU5X', 'TCG_PARTY_GRENADE'),
    ('3W8K-VFSR-WZAW-EZFR', 'TCG_PARTY_GRENADE'),
    ('RX6C-KWMY-5626-M9BW', 'TCG_PARTY_GRENADE'),
    ('VJ4F-CF3E-6MXX-R3YF', 'TCG_PARTY_GRENADE'),
    ('FJAT-3KYA-42CG-7J4J', 'TCG_PARTY_GRENADE'),
    ('X6ME-FDS3-E4PA-DJYC', 'TCG_PARTY_GRENADE'),
    ('AVZ2-HWXR-HRNJ-W86R', 'TCG_PARTY_GRENADE'),
    ('9ANR-QK85-X2AD-SNP2', 'TCG_PARTY_GRENADE'),
    ('WEXE-4NED-58Y4-SMFX', 'TCG_PARTY_GRENADE'),
    ('9C6H-CM5T-J9NG-F4SM', 'TCG_PARTY_GRENADE'),
    ('DY33-CPHW-EFQX-DXJM', 'TCG_PARTY_GRENADE'),
    ('66M8-R28E-KZY4-WPE2', 'TCG_PARTY_GRENADE');

-- TCG_FLAG_OF_OWNERSHIP  (The Flag of Ownership)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('MZYA-UYQJ-X4F7-K3WX', 'TCG_FLAG_OF_OWNERSHIP'),
    ('7RJE-BF2A-T6HT-ABN9', 'TCG_FLAG_OF_OWNERSHIP'),
    ('KBEP-5KM2-7WTD-WEAR', 'TCG_FLAG_OF_OWNERSHIP'),
    ('E9W7-J3VZ-H9FY-Y4WB', 'TCG_FLAG_OF_OWNERSHIP'),
    ('3PBW-ENH7-S4FB-5GT2', 'TCG_FLAG_OF_OWNERSHIP'),
    ('N5FX-PG9J-SBHP-8MT5', 'TCG_FLAG_OF_OWNERSHIP'),
    ('T4FG-QQ3V-AT4T-ZBG7', 'TCG_FLAG_OF_OWNERSHIP'),
    ('PV6Y-FUXT-WCX2-M3KD', 'TCG_FLAG_OF_OWNERSHIP'),
    ('R4AT-8EE4-SES2-9KV5', 'TCG_FLAG_OF_OWNERSHIP'),
    ('VB8D-FEQV-DFGD-WWHJ', 'TCG_FLAG_OF_OWNERSHIP'),
    ('XKVK-SUSD-UKMZ-6ES4', 'TCG_FLAG_OF_OWNERSHIP'),
    ('APKZ-FKES-NFGZ-26UH', 'TCG_FLAG_OF_OWNERSHIP'),
    ('NHM6-YYXV-MCGY-W6AW', 'TCG_FLAG_OF_OWNERSHIP'),
    ('FH5Z-HXXD-CV4N-UAM5', 'TCG_FLAG_OF_OWNERSHIP'),
    ('A53R-K7Z4-7SA3-38XJ', 'TCG_FLAG_OF_OWNERSHIP'),
    ('2JP2-U273-S4GR-RQUD', 'TCG_FLAG_OF_OWNERSHIP'),
    ('29QE-C6KE-D9PH-JACB', 'TCG_FLAG_OF_OWNERSHIP'),
    ('E23S-GXQJ-B9CQ-D6QT', 'TCG_FLAG_OF_OWNERSHIP'),
    ('YXMT-XMHF-KFAG-JE9P', 'TCG_FLAG_OF_OWNERSHIP'),
    ('TVJ7-MWY5-VRCB-VFJT', 'TCG_FLAG_OF_OWNERSHIP');

-- TCG_BIG_BATTLE_BEAR  (Big Battle Bear)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('FT7V-7YYV-E6Q9-AM8M', 'TCG_BIG_BATTLE_BEAR'),
    ('HBE7-GS6D-V7WT-RR9U', 'TCG_BIG_BATTLE_BEAR'),
    ('X2TS-K89T-AYZS-W3ZX', 'TCG_BIG_BATTLE_BEAR'),
    ('S4VZ-FQ2E-DM69-PBG6', 'TCG_BIG_BATTLE_BEAR'),
    ('NGAP-ZYYU-EVEG-7Q69', 'TCG_BIG_BATTLE_BEAR'),
    ('FW6E-Y2KQ-QWQV-RDSS', 'TCG_BIG_BATTLE_BEAR'),
    ('J7JJ-3YM8-U4CP-XANH', 'TCG_BIG_BATTLE_BEAR'),
    ('U96U-ZF9Z-XSPE-TVE4', 'TCG_BIG_BATTLE_BEAR'),
    ('495B-YKQR-NXN7-MPV6', 'TCG_BIG_BATTLE_BEAR'),
    ('BW5Y-FDFM-23M8-67NY', 'TCG_BIG_BATTLE_BEAR'),
    ('46MC-X47F-GJ7U-C9F5', 'TCG_BIG_BATTLE_BEAR'),
    ('RKGB-VKF9-BPD4-T4GT', 'TCG_BIG_BATTLE_BEAR'),
    ('5SYH-78RX-2Z7P-7MGC', 'TCG_BIG_BATTLE_BEAR'),
    ('GNFB-JZAS-ZFZF-R279', 'TCG_BIG_BATTLE_BEAR'),
    ('299R-ECCV-89TW-9DHT', 'TCG_BIG_BATTLE_BEAR'),
    ('EUHF-XBN9-SMNU-PKGQ', 'TCG_BIG_BATTLE_BEAR'),
    ('KUBC-N9XU-QCH4-DGDS', 'TCG_BIG_BATTLE_BEAR'),
    ('5375-HHZ2-4CHG-AXRE', 'TCG_BIG_BATTLE_BEAR'),
    ('WQD9-6GZE-RZZU-G9K6', 'TCG_BIG_BATTLE_BEAR'),
    ('8VGB-QPY3-E6G9-TW7P', 'TCG_BIG_BATTLE_BEAR');

-- TCG_SANDBOX_TIGER  (Sandbox Tiger)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('NC95-M4CY-NMVA-B7KJ', 'TCG_SANDBOX_TIGER'),
    ('9DP5-3TU3-4QRM-KYDU', 'TCG_SANDBOX_TIGER'),
    ('NVQH-ZRCA-RDAP-D2B7', 'TCG_SANDBOX_TIGER'),
    ('VRNC-E47D-4STW-RRMG', 'TCG_SANDBOX_TIGER'),
    ('9FSV-SJ6U-6ET8-GBHP', 'TCG_SANDBOX_TIGER'),
    ('V99F-45EC-U372-V7GT', 'TCG_SANDBOX_TIGER'),
    ('UXP4-7KA8-URZQ-VNVZ', 'TCG_SANDBOX_TIGER'),
    ('XKHK-H5EZ-63G2-333K', 'TCG_SANDBOX_TIGER'),
    ('X3KZ-YAAZ-8MQA-PFEX', 'TCG_SANDBOX_TIGER'),
    ('HZGA-SYGG-TK5G-46JZ', 'TCG_SANDBOX_TIGER'),
    ('MYM3-9XWU-N7P2-KRQ8', 'TCG_SANDBOX_TIGER'),
    ('89XW-VD3U-CJEM-YRTC', 'TCG_SANDBOX_TIGER'),
    ('PMQ8-WKSM-VMSR-88WR', 'TCG_SANDBOX_TIGER'),
    ('DWJM-B5BA-3UFD-MWFG', 'TCG_SANDBOX_TIGER'),
    ('59AA-3CFK-7RWM-CAJ4', 'TCG_SANDBOX_TIGER'),
    ('EBAS-PNQG-DFYP-A499', 'TCG_SANDBOX_TIGER'),
    ('P8VW-RNNA-RMG4-PCSX', 'TCG_SANDBOX_TIGER'),
    ('A648-26K2-5EJZ-PDJZ', 'TCG_SANDBOX_TIGER'),
    ('2P33-CTQH-CHSG-7RKT', 'TCG_SANDBOX_TIGER'),
    ('CTVM-CGEB-VYCB-DAF7', 'TCG_SANDBOX_TIGER');

-- TCG_EPIC_PURPLE_SHIRT  (Epic Purple Shirt)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('5999-4CNZ-BZ5E-WBYD', 'TCG_EPIC_PURPLE_SHIRT'),
    ('N895-DQMG-J8W6-GDCP', 'TCG_EPIC_PURPLE_SHIRT'),
    ('7X75-QTK9-UPY4-NAQV', 'TCG_EPIC_PURPLE_SHIRT'),
    ('PHXM-MGFC-ZZVA-XA6K', 'TCG_EPIC_PURPLE_SHIRT'),
    ('B4BF-UAMY-ACFV-TFV6', 'TCG_EPIC_PURPLE_SHIRT'),
    ('75UU-TN2T-CTZR-KCUX', 'TCG_EPIC_PURPLE_SHIRT'),
    ('GT2S-73U2-D77A-WQT4', 'TCG_EPIC_PURPLE_SHIRT'),
    ('Q7YB-4RDQ-CGN8-J6YM', 'TCG_EPIC_PURPLE_SHIRT'),
    ('YS3U-KMGR-8J7A-Q663', 'TCG_EPIC_PURPLE_SHIRT'),
    ('PD6Y-4DAV-DDQS-XYHR', 'TCG_EPIC_PURPLE_SHIRT'),
    ('Q37F-65QQ-FEVX-74EW', 'TCG_EPIC_PURPLE_SHIRT'),
    ('5QCQ-R9RV-S43J-TKMW', 'TCG_EPIC_PURPLE_SHIRT'),
    ('KX24-K5V5-VRK2-X88M', 'TCG_EPIC_PURPLE_SHIRT'),
    ('9C5N-VRVA-FFZM-8NJU', 'TCG_EPIC_PURPLE_SHIRT'),
    ('JXC8-DZNH-UTE7-M7U5', 'TCG_EPIC_PURPLE_SHIRT'),
    ('VCPA-4D66-X7PM-PTVH', 'TCG_EPIC_PURPLE_SHIRT'),
    ('7PE4-VRNJ-ZC9R-HZ69', 'TCG_EPIC_PURPLE_SHIRT'),
    ('ZAGU-22DD-E9SM-6VNV', 'TCG_EPIC_PURPLE_SHIRT'),
    ('3MSF-NQJN-DMVY-2U54', 'TCG_EPIC_PURPLE_SHIRT'),
    ('J9JH-HGXM-524J-PEC6', 'TCG_EPIC_PURPLE_SHIRT');

-- TCG_FOAM_SWORD_RACK  (Foam Sword Rack)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('PBBS-AA3K-BMZT-CCD5', 'TCG_FOAM_SWORD_RACK'),
    ('R98Q-M2UK-2AR2-UJ3Q', 'TCG_FOAM_SWORD_RACK'),
    ('EQ8D-N395-9UB4-V92G', 'TCG_FOAM_SWORD_RACK'),
    ('8QW9-WXP4-DH3G-UR6B', 'TCG_FOAM_SWORD_RACK'),
    ('S96H-VPQW-VMPW-7U5W', 'TCG_FOAM_SWORD_RACK'),
    ('RHKZ-M6TY-8TN2-NP3G', 'TCG_FOAM_SWORD_RACK'),
    ('7H7C-5QWG-ZFR9-KQEZ', 'TCG_FOAM_SWORD_RACK'),
    ('AP8Z-9T6H-PR5Y-XVRD', 'TCG_FOAM_SWORD_RACK'),
    ('V7XD-V7UX-A2HC-Y5DK', 'TCG_FOAM_SWORD_RACK'),
    ('JQYD-AGTP-4BBQ-8BUU', 'TCG_FOAM_SWORD_RACK'),
    ('CMXS-VS7M-59YT-R23V', 'TCG_FOAM_SWORD_RACK'),
    ('UD3Q-X6H8-2MFA-TRN9', 'TCG_FOAM_SWORD_RACK'),
    ('HUFC-W67E-9M5B-KJQP', 'TCG_FOAM_SWORD_RACK'),
    ('8PQY-A56Q-FG9G-ZQAK', 'TCG_FOAM_SWORD_RACK'),
    ('AX5P-8XTQ-FKVM-SEW3', 'TCG_FOAM_SWORD_RACK'),
    ('DN6H-WZXH-EJ47-VSDV', 'TCG_FOAM_SWORD_RACK'),
    ('F324-97B7-6QEF-MVPB', 'TCG_FOAM_SWORD_RACK'),
    ('DR9G-8JZQ-K4W6-5APJ', 'TCG_FOAM_SWORD_RACK'),
    ('2RXH-8GGK-SA3Y-2VA2', 'TCG_FOAM_SWORD_RACK'),
    ('DS34-JXTD-KA9S-GYHS', 'TCG_FOAM_SWORD_RACK');

-- TCG_PATH_OF_CENARIUS  (Path of Cenarius)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('KJ4F-H5TR-GNSY-GGJQ', 'TCG_PATH_OF_CENARIUS'),
    ('4CV6-AY45-RDD2-VUTG', 'TCG_PATH_OF_CENARIUS'),
    ('VDHS-E47R-HFYG-B6FJ', 'TCG_PATH_OF_CENARIUS'),
    ('UQ42-ZMAK-CJ9J-2YKX', 'TCG_PATH_OF_CENARIUS'),
    ('NXYS-BMZT-A4X2-UYVJ', 'TCG_PATH_OF_CENARIUS'),
    ('A837-6QDX-VM3E-WSDJ', 'TCG_PATH_OF_CENARIUS'),
    ('M7SP-7AJC-JV46-N2N4', 'TCG_PATH_OF_CENARIUS'),
    ('6EY6-58WD-VQ9U-TCRC', 'TCG_PATH_OF_CENARIUS'),
    ('3REG-BDHW-Q6AZ-XPA7', 'TCG_PATH_OF_CENARIUS'),
    ('ZG5H-BZFP-8U7K-4CJ2', 'TCG_PATH_OF_CENARIUS'),
    ('WW8G-Q9JW-2UE9-ZSQC', 'TCG_PATH_OF_CENARIUS'),
    ('7W67-JW7T-SWMU-PJ2D', 'TCG_PATH_OF_CENARIUS'),
    ('6QAP-3JFN-SM6J-H9NC', 'TCG_PATH_OF_CENARIUS'),
    ('AKCQ-SQG6-HSQE-PRMH', 'TCG_PATH_OF_CENARIUS'),
    ('Z2MS-FGRD-EDGM-NBH7', 'TCG_PATH_OF_CENARIUS'),
    ('HKB5-UP4N-C9GE-K3BX', 'TCG_PATH_OF_CENARIUS'),
    ('CU2V-XNX8-E56Y-8KD6', 'TCG_PATH_OF_CENARIUS'),
    ('74Q2-NB6Q-85WX-WQCB', 'TCG_PATH_OF_CENARIUS'),
    ('8XJV-QX6A-62EB-CUTJ', 'TCG_PATH_OF_CENARIUS'),
    ('RQEZ-Q34V-R7RK-8NCQ', 'TCG_PATH_OF_CENARIUS');

-- TCG_OGRE_PINATA  (Ogre Pinata)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('8Y5T-27D6-DZB4-ZTP9', 'TCG_OGRE_PINATA'),
    ('T5D5-XVVT-B9JS-2N55', 'TCG_OGRE_PINATA'),
    ('G6RN-TGMJ-9UEC-SXWX', 'TCG_OGRE_PINATA'),
    ('SNBY-4BS3-WHWY-KHZB', 'TCG_OGRE_PINATA'),
    ('XUN9-QKMG-ABE7-JUR3', 'TCG_OGRE_PINATA'),
    ('M8TS-7RUY-K229-2Q32', 'TCG_OGRE_PINATA'),
    ('2FRV-N6W8-VMS6-GVK2', 'TCG_OGRE_PINATA'),
    ('9JK8-P86C-CEWC-3QH2', 'TCG_OGRE_PINATA'),
    ('D36X-4QJZ-KUMS-UENU', 'TCG_OGRE_PINATA'),
    ('KFQK-FGWX-3Z8E-829D', 'TCG_OGRE_PINATA'),
    ('KG3Q-KFTZ-6P6Q-XYUG', 'TCG_OGRE_PINATA'),
    ('S97E-VWPJ-MMF5-DJVH', 'TCG_OGRE_PINATA'),
    ('6JAG-JY37-USJV-53HS', 'TCG_OGRE_PINATA'),
    ('JDXF-XHB4-YBPA-P6CW', 'TCG_OGRE_PINATA'),
    ('MAN7-SBDQ-TSDM-DE77', 'TCG_OGRE_PINATA'),
    ('CG5D-E98Q-YXN5-9QZM', 'TCG_OGRE_PINATA'),
    ('XBSU-QTBW-ANHF-5GKB', 'TCG_OGRE_PINATA'),
    ('VG4P-THVN-8DY4-2CQ4', 'TCG_OGRE_PINATA'),
    ('PBTB-STSR-SG3H-PYNT', 'TCG_OGRE_PINATA'),
    ('TXJ3-64V7-PB3Y-Z3R6', 'TCG_OGRE_PINATA');

-- TCG_MAGIC_ROOSTER_EGG  (Magic Rooster Egg)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('ERGC-6TA6-5WDM-D44M', 'TCG_MAGIC_ROOSTER_EGG'),
    ('FKQE-FXQS-R4CY-4B2A', 'TCG_MAGIC_ROOSTER_EGG'),
    ('HJ5F-ZST2-W5FJ-FQCP', 'TCG_MAGIC_ROOSTER_EGG'),
    ('HNZN-UN5F-3U4X-24Z4', 'TCG_MAGIC_ROOSTER_EGG'),
    ('PXS2-T6RJ-32U9-4VYH', 'TCG_MAGIC_ROOSTER_EGG'),
    ('7NPK-JKK3-TVPD-725Q', 'TCG_MAGIC_ROOSTER_EGG'),
    ('W3A9-XPD2-3V4P-DMZT', 'TCG_MAGIC_ROOSTER_EGG'),
    ('XFRX-KKT9-D5N2-WYFU', 'TCG_MAGIC_ROOSTER_EGG'),
    ('DQ9T-D3BP-67K8-MXZ2', 'TCG_MAGIC_ROOSTER_EGG'),
    ('S83C-SM4C-WZ5Z-VECK', 'TCG_MAGIC_ROOSTER_EGG'),
    ('X2C2-Z2RR-JZUZ-PAQD', 'TCG_MAGIC_ROOSTER_EGG'),
    ('6PY5-3CWF-QQTP-TH8Y', 'TCG_MAGIC_ROOSTER_EGG'),
    ('ZNFZ-DB6F-N2V2-K6H7', 'TCG_MAGIC_ROOSTER_EGG'),
    ('WKR2-EFWJ-72JE-BX7P', 'TCG_MAGIC_ROOSTER_EGG'),
    ('Y6J7-AWAP-2HPB-HJKH', 'TCG_MAGIC_ROOSTER_EGG'),
    ('K4QP-NNYX-YBTQ-PCQ8', 'TCG_MAGIC_ROOSTER_EGG'),
    ('3X3V-S249-DHDG-F6ZU', 'TCG_MAGIC_ROOSTER_EGG'),
    ('8VQ9-KKW2-5FSS-KE46', 'TCG_MAGIC_ROOSTER_EGG'),
    ('N3S4-H2HG-HWQT-HDDN', 'TCG_MAGIC_ROOSTER_EGG'),
    ('8ZFU-2EZA-GNB5-YZFS', 'TCG_MAGIC_ROOSTER_EGG');

-- TCG_SCOURGEWAR_MINIMOUNT  (Scourgewar Mini-Mount (faction-aware))
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('7XJG-WX3R-K95N-TKDF', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('W7HY-YEDW-RW75-7J56', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('NEPW-HXE6-SKK5-6EPT', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('C7P2-93XD-AF5V-NUNZ', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('GUGH-VGVH-JBG6-4VNC', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('MUNT-KZ2G-T8DW-GJYP', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('HHKD-7FFF-U4ZA-YXDW', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('4JC4-XAH7-CYAE-EJKX', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('GWV4-2FZQ-E2S3-PR7V', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('JGP8-P9S6-AMXS-B6DD', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('Z6TN-FFAG-P4U2-CXX7', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('QPH8-ANUC-P8N8-MPQY', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('PMMQ-QFQ6-RJXR-XPFD', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('XBJU-7CT8-DXQ6-VA5V', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('BYEH-X667-38Y8-QHT2', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('8ZQF-5KA5-SGWQ-HPBD', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('RPCN-4W42-RRVU-CEQG', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('AN6D-E58B-NPBG-GHSB', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('R52C-PZVS-SBX6-AQGT', 'TCG_SCOURGEWAR_MINIMOUNT'),
    ('7PB4-AA46-AWVE-K596', 'TCG_SCOURGEWAR_MINIMOUNT');

-- TCG_TUSKARR_KITE  (Tuskarr Kite)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('QDSY-Y8W2-PHHU-SYJS', 'TCG_TUSKARR_KITE'),
    ('3PQJ-BUJS-42PM-F7ZG', 'TCG_TUSKARR_KITE'),
    ('9229-BCZE-SKSZ-3FJD', 'TCG_TUSKARR_KITE'),
    ('7QN3-D8YV-9WNV-WDF4', 'TCG_TUSKARR_KITE'),
    ('BB44-2PBF-YGBS-UV8D', 'TCG_TUSKARR_KITE'),
    ('ZG62-G37T-2QDY-X9HF', 'TCG_TUSKARR_KITE'),
    ('FU7T-V97G-QJ2K-PTBH', 'TCG_TUSKARR_KITE'),
    ('7NTZ-SSK5-D37U-XDHU', 'TCG_TUSKARR_KITE'),
    ('XA4P-EVGD-YH8E-DBBE', 'TCG_TUSKARR_KITE'),
    ('3ZZH-7EK4-ARKQ-77PH', 'TCG_TUSKARR_KITE'),
    ('VJS7-329M-YW9Z-ATWE', 'TCG_TUSKARR_KITE'),
    ('XAD2-GFUR-R52V-2H5Q', 'TCG_TUSKARR_KITE'),
    ('T2RA-VNSN-AKTG-AEVR', 'TCG_TUSKARR_KITE'),
    ('KHPJ-UMN7-FTB4-7YZB', 'TCG_TUSKARR_KITE'),
    ('3XD2-U9CE-WGSX-8T9Y', 'TCG_TUSKARR_KITE'),
    ('SPTX-WH76-HZA6-7FJE', 'TCG_TUSKARR_KITE'),
    ('FWUD-Z375-MUGN-UVBV', 'TCG_TUSKARR_KITE'),
    ('3V3V-7X5B-3RQ5-3R43', 'TCG_TUSKARR_KITE'),
    ('BQSY-WC7Q-K6NE-ZZVN', 'TCG_TUSKARR_KITE'),
    ('5232-A4RF-QPSW-Q454', 'TCG_TUSKARR_KITE');

-- TCG_SPECTRAL_TIGER_CUB  (Spectral Tiger Cub)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('HAGC-DFG9-6TEP-ENKX', 'TCG_SPECTRAL_TIGER_CUB'),
    ('9U6D-E6D5-8PWQ-7ZWE', 'TCG_SPECTRAL_TIGER_CUB'),
    ('Y2TC-FDSW-6BWQ-TVX6', 'TCG_SPECTRAL_TIGER_CUB'),
    ('JJPJ-M9KV-HZ4Q-7BKF', 'TCG_SPECTRAL_TIGER_CUB'),
    ('KXCN-K67W-C5W9-VYTS', 'TCG_SPECTRAL_TIGER_CUB'),
    ('NVR2-92KV-N2RD-W648', 'TCG_SPECTRAL_TIGER_CUB'),
    ('HCWX-Z9VF-KRRQ-EXB5', 'TCG_SPECTRAL_TIGER_CUB'),
    ('HAF4-FSP4-5JNK-5S73', 'TCG_SPECTRAL_TIGER_CUB'),
    ('D7HV-3AJ8-4TE2-GAH4', 'TCG_SPECTRAL_TIGER_CUB'),
    ('SE29-W8SB-NEGW-BWRF', 'TCG_SPECTRAL_TIGER_CUB'),
    ('MMDE-V57J-X2FZ-M5J3', 'TCG_SPECTRAL_TIGER_CUB'),
    ('CEQD-7RUG-PT5C-H8QX', 'TCG_SPECTRAL_TIGER_CUB'),
    ('5DB3-UV95-EF2D-DSCU', 'TCG_SPECTRAL_TIGER_CUB'),
    ('GSZ7-7HKM-H6NM-G7E6', 'TCG_SPECTRAL_TIGER_CUB'),
    ('6EKX-DW7X-9R8J-DCYC', 'TCG_SPECTRAL_TIGER_CUB'),
    ('P8BY-Q4E5-9GHK-E5HJ', 'TCG_SPECTRAL_TIGER_CUB'),
    ('YCVS-CHEF-KTYS-HN66', 'TCG_SPECTRAL_TIGER_CUB'),
    ('MZAK-Z5N6-BTE8-K66A', 'TCG_SPECTRAL_TIGER_CUB'),
    ('DQ94-2HNU-8ZUT-SWUZ', 'TCG_SPECTRAL_TIGER_CUB'),
    ('5XNC-E97C-F6YF-P822', 'TCG_SPECTRAL_TIGER_CUB');

-- TCG_LANDROS_GIFT_BOX  (Landro's Gift Box)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('3XCC-DKY8-R9E9-33QM', 'TCG_LANDROS_GIFT_BOX'),
    ('VP3B-MWBK-RZDQ-8ZFQ', 'TCG_LANDROS_GIFT_BOX'),
    ('TK9K-MU9U-MH2G-RKNZ', 'TCG_LANDROS_GIFT_BOX'),
    ('QPCF-VFN5-HQAT-YXQ2', 'TCG_LANDROS_GIFT_BOX'),
    ('FZTV-3JCS-QYW4-47W5', 'TCG_LANDROS_GIFT_BOX'),
    ('PNN2-E6XY-P7WR-9JY4', 'TCG_LANDROS_GIFT_BOX'),
    ('2RT9-4STP-STDK-N8R5', 'TCG_LANDROS_GIFT_BOX'),
    ('VJ9X-PVUE-KXKN-G6MC', 'TCG_LANDROS_GIFT_BOX'),
    ('DJ7M-236Q-JDFX-FVMJ', 'TCG_LANDROS_GIFT_BOX'),
    ('96CH-FG26-YWJT-RKTS', 'TCG_LANDROS_GIFT_BOX'),
    ('KA9Q-JTUU-DKK4-8E8K', 'TCG_LANDROS_GIFT_BOX'),
    ('YMR4-3NGQ-42C4-VP3S', 'TCG_LANDROS_GIFT_BOX'),
    ('NCXV-8T2J-Y457-UYW5', 'TCG_LANDROS_GIFT_BOX'),
    ('JFNX-7WG4-ZGYQ-PV22', 'TCG_LANDROS_GIFT_BOX'),
    ('J78X-SA3U-DDUA-KF6K', 'TCG_LANDROS_GIFT_BOX'),
    ('5FJM-VB3Y-VSUW-UMNV', 'TCG_LANDROS_GIFT_BOX'),
    ('J46E-NDVM-5DQG-FD2K', 'TCG_LANDROS_GIFT_BOX'),
    ('5B3K-XZGJ-WSKY-6AE9', 'TCG_LANDROS_GIFT_BOX'),
    ('2GKY-JP4R-R39E-R98F', 'TCG_LANDROS_GIFT_BOX'),
    ('C6A9-5S2G-Y5XF-Z44X', 'TCG_LANDROS_GIFT_BOX');

-- TCG_INSTANT_STATUE_PEDESTAL  (Instant Statue Pedestal)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('EK68-VF42-AK42-FX9P', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('8XFB-T68U-CK8T-TVJN', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('VEE5-69KK-YURG-MRMH', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('45K5-RCUT-6GSC-2AXF', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('GC37-YHEB-J77N-5X6X', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('57DB-BHHH-6WX5-GKA6', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('U49B-SFCB-P4QJ-FKXX', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('8AK6-2DM4-NVKJ-BF5G', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('GRDM-Z3CU-FU8W-ANVW', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('VZD7-YXF5-FXBM-BYZE', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('36B6-GZ76-D3Q9-FUHX', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('YD86-U8KK-JKPV-CGV9', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('V6XH-NQ2R-6MX7-87Z7', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('N9TW-D5T4-CZUE-WD3T', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('7JQZ-9NRN-DCZJ-G8VE', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('3CD3-2HAC-9KYX-KEA8', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('JTKQ-3FPT-RP9H-BDXF', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('KS2G-UY5S-BQCK-4EEW', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('9CXZ-HGSE-77U3-2P7Z', 'TCG_INSTANT_STATUE_PEDESTAL'),
    ('NCZE-F7AF-KKW2-DRE2', 'TCG_INSTANT_STATUE_PEDESTAL');

-- TCG_BLAZING_HIPPOGRYPH  (Blazing Hippogryph)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('KGGS-E6MJ-QEVW-MTXU', 'TCG_BLAZING_HIPPOGRYPH'),
    ('Z5YT-BEJ2-UHF8-FBCS', 'TCG_BLAZING_HIPPOGRYPH'),
    ('54T7-R4J9-SDNU-FXKQ', 'TCG_BLAZING_HIPPOGRYPH'),
    ('6AA2-37P3-WMT3-4GQN', 'TCG_BLAZING_HIPPOGRYPH'),
    ('BHTT-Y83G-X59Y-BGTN', 'TCG_BLAZING_HIPPOGRYPH'),
    ('6N5U-5RWT-XURB-FAYG', 'TCG_BLAZING_HIPPOGRYPH'),
    ('KGG9-TEYV-ZTVH-ZBZK', 'TCG_BLAZING_HIPPOGRYPH'),
    ('GMRU-9MK9-WQBD-J6HW', 'TCG_BLAZING_HIPPOGRYPH'),
    ('EK2P-QVN6-MRG4-7FP5', 'TCG_BLAZING_HIPPOGRYPH'),
    ('BS5V-ZG8P-Y46C-HDST', 'TCG_BLAZING_HIPPOGRYPH'),
    ('XQ8Z-UQPQ-ZW7Z-9XQE', 'TCG_BLAZING_HIPPOGRYPH'),
    ('RQWW-BU83-8GAV-36HB', 'TCG_BLAZING_HIPPOGRYPH'),
    ('FX2D-T4W2-6THJ-TM8B', 'TCG_BLAZING_HIPPOGRYPH'),
    ('3KT4-WHM7-FQDD-MX3Q', 'TCG_BLAZING_HIPPOGRYPH'),
    ('XDP3-KM8Z-BGMR-UPU9', 'TCG_BLAZING_HIPPOGRYPH'),
    ('RJGH-KRDF-M9H3-VK2W', 'TCG_BLAZING_HIPPOGRYPH'),
    ('UQZN-PX8V-AC97-REB2', 'TCG_BLAZING_HIPPOGRYPH'),
    ('66EX-TQJY-2CZA-Q639', 'TCG_BLAZING_HIPPOGRYPH'),
    ('FKJF-E2TA-F9PT-SZ5R', 'TCG_BLAZING_HIPPOGRYPH'),
    ('YHRN-5F4D-DZGJ-3W8Q', 'TCG_BLAZING_HIPPOGRYPH');

-- TCG_PAINT_BOMB  (Paint Bomb)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('EKC5-PJ9U-2YBY-UBPJ', 'TCG_PAINT_BOMB'),
    ('RHA3-N486-K37V-X4NQ', 'TCG_PAINT_BOMB'),
    ('MHA6-W65X-5QPY-BVN7', 'TCG_PAINT_BOMB'),
    ('7JJD-NC9A-PNHM-XZMS', 'TCG_PAINT_BOMB'),
    ('3TUV-J2MM-GR8C-NCEU', 'TCG_PAINT_BOMB'),
    ('AY9M-HZPK-F9BQ-SQEG', 'TCG_PAINT_BOMB'),
    ('VSKK-NC2J-ZC39-EXMD', 'TCG_PAINT_BOMB'),
    ('4R6H-CZ8N-PSKQ-B8G7', 'TCG_PAINT_BOMB'),
    ('4A25-VTZE-A4GH-ZZYD', 'TCG_PAINT_BOMB'),
    ('G8MW-DTCE-MKAX-5VEX', 'TCG_PAINT_BOMB'),
    ('FF2S-ZUMW-GXZX-AXHJ', 'TCG_PAINT_BOMB'),
    ('2V89-37Q7-S3JV-BVJZ', 'TCG_PAINT_BOMB'),
    ('YQW2-Q9N8-7UKT-B4G4', 'TCG_PAINT_BOMB'),
    ('WVYN-VSSD-SJWJ-CRJX', 'TCG_PAINT_BOMB'),
    ('P7N4-U2HP-MBKF-7YAT', 'TCG_PAINT_BOMB'),
    ('ZXU3-VP9P-2SHH-GNAC', 'TCG_PAINT_BOMB'),
    ('78YN-2E9E-9DKB-PJY7', 'TCG_PAINT_BOMB'),
    ('AM3D-6P3M-WAJF-4DJD', 'TCG_PAINT_BOMB'),
    ('C7MT-XKPV-2D8U-C8PJ', 'TCG_PAINT_BOMB'),
    ('EKJN-KXDX-4A5J-VHNN', 'TCG_PAINT_BOMB');

-- TCG_ETHEREAL_PORTAL  (Ethereal Portal)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('7QUW-RC9M-GXBA-KG2W', 'TCG_ETHEREAL_PORTAL'),
    ('65QA-H6QH-VM5Q-QUVK', 'TCG_ETHEREAL_PORTAL'),
    ('FDQP-QF7T-7JDR-68YF', 'TCG_ETHEREAL_PORTAL'),
    ('2YBZ-YJCF-JNWH-7SW5', 'TCG_ETHEREAL_PORTAL'),
    ('CFCS-F732-8VNT-ZQR4', 'TCG_ETHEREAL_PORTAL'),
    ('P35X-GKCG-FWBZ-QC4G', 'TCG_ETHEREAL_PORTAL'),
    ('H8PG-VXGX-BSPS-E72Q', 'TCG_ETHEREAL_PORTAL'),
    ('US75-987F-Y7VZ-8YUZ', 'TCG_ETHEREAL_PORTAL'),
    ('DHZG-3JQ9-AQPT-ARVF', 'TCG_ETHEREAL_PORTAL'),
    ('UY5Y-HQN5-HB4M-4W8N', 'TCG_ETHEREAL_PORTAL'),
    ('GYWE-A74Q-6V75-NC5S', 'TCG_ETHEREAL_PORTAL'),
    ('262M-MVBT-GSA3-3R46', 'TCG_ETHEREAL_PORTAL'),
    ('9BNN-5D6F-44KR-8V6G', 'TCG_ETHEREAL_PORTAL'),
    ('K75E-BM6W-TF63-PKMH', 'TCG_ETHEREAL_PORTAL'),
    ('QMY4-Y3RJ-4J5K-RB3Z', 'TCG_ETHEREAL_PORTAL'),
    ('RB26-URQ3-EEWZ-TPEG', 'TCG_ETHEREAL_PORTAL'),
    ('EB9D-8C2H-UA7W-YYSP', 'TCG_ETHEREAL_PORTAL'),
    ('497X-GWX5-8GFV-EQ2E', 'TCG_ETHEREAL_PORTAL'),
    ('B6XQ-8JHZ-FDHT-XW6V', 'TCG_ETHEREAL_PORTAL'),
    ('TU7M-CWY3-EB5W-DRN6', 'TCG_ETHEREAL_PORTAL');

-- TCG_WOOLY_WHITE_RHINO  (Wooly White Rhino)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('3XSX-JRUC-YDU9-6WFN', 'TCG_WOOLY_WHITE_RHINO'),
    ('MCP8-4P2B-BPQ8-BUZX', 'TCG_WOOLY_WHITE_RHINO'),
    ('QJ9H-CN67-66KC-GDHG', 'TCG_WOOLY_WHITE_RHINO'),
    ('UXE4-UF2Y-R4M5-V6SG', 'TCG_WOOLY_WHITE_RHINO'),
    ('WNKQ-4M9U-45AU-R9SB', 'TCG_WOOLY_WHITE_RHINO'),
    ('JEF2-E2WD-V3TN-SPMR', 'TCG_WOOLY_WHITE_RHINO'),
    ('SVHE-MX4W-FX9B-UAQ9', 'TCG_WOOLY_WHITE_RHINO'),
    ('VD26-5RX4-BUNE-7NG8', 'TCG_WOOLY_WHITE_RHINO'),
    ('56RJ-XPJJ-2ZGX-MCJ9', 'TCG_WOOLY_WHITE_RHINO'),
    ('YVV9-WKSA-2422-JKPM', 'TCG_WOOLY_WHITE_RHINO'),
    ('BADS-ZVJ5-D84T-W3SF', 'TCG_WOOLY_WHITE_RHINO'),
    ('9FFA-QKUK-J2V4-RK9F', 'TCG_WOOLY_WHITE_RHINO'),
    ('XPWR-J3PD-9M5E-E3UY', 'TCG_WOOLY_WHITE_RHINO'),
    ('A2BZ-NHWD-FYG3-DZ7S', 'TCG_WOOLY_WHITE_RHINO'),
    ('M7P5-CPTM-F5FW-BQ2H', 'TCG_WOOLY_WHITE_RHINO'),
    ('PZ2C-FS4B-PE4Q-8AH8', 'TCG_WOOLY_WHITE_RHINO'),
    ('R48T-P9RQ-JKPS-FWA2', 'TCG_WOOLY_WHITE_RHINO'),
    ('UYEV-DRF2-ZA47-Q5MU', 'TCG_WOOLY_WHITE_RHINO'),
    ('V4NV-FQG6-GBRK-N2D6', 'TCG_WOOLY_WHITE_RHINO'),
    ('NJRF-UQM2-2PVR-JWEW', 'TCG_WOOLY_WHITE_RHINO');

-- TCG_TABARD_OF_FROST  (Tabard of Frost)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('UGRZ-UXAY-V8XF-3S79', 'TCG_TABARD_OF_FROST'),
    ('JH85-UT3T-TTSC-MW5M', 'TCG_TABARD_OF_FROST'),
    ('G7HA-PMCK-EYFF-98W2', 'TCG_TABARD_OF_FROST'),
    ('3RAB-NY5W-UNUK-FCQ9', 'TCG_TABARD_OF_FROST'),
    ('RAV2-BZKB-WX2R-7D8D', 'TCG_TABARD_OF_FROST'),
    ('UC9S-MF7R-2TYU-MPPS', 'TCG_TABARD_OF_FROST'),
    ('UP95-MJJM-XJBK-CS2B', 'TCG_TABARD_OF_FROST'),
    ('2HRC-AH9G-Y5Q8-DBG7', 'TCG_TABARD_OF_FROST'),
    ('YYQR-3KF3-25EM-XR9D', 'TCG_TABARD_OF_FROST'),
    ('D38K-CCG5-8SS5-9P2D', 'TCG_TABARD_OF_FROST'),
    ('X3JD-8QRC-64FK-P2JZ', 'TCG_TABARD_OF_FROST'),
    ('YHX3-J6FS-STHF-T57Y', 'TCG_TABARD_OF_FROST'),
    ('CTAD-AYRH-3SW2-3J6U', 'TCG_TABARD_OF_FROST'),
    ('32Y4-7WY5-2RJQ-M48Y', 'TCG_TABARD_OF_FROST'),
    ('FUMQ-W2TB-5GXB-F8WP', 'TCG_TABARD_OF_FROST'),
    ('MBM7-9BAT-4YYC-GX84', 'TCG_TABARD_OF_FROST'),
    ('S5UQ-78XS-B4GH-C3S8', 'TCG_TABARD_OF_FROST'),
    ('Q6MX-PVZM-RWG3-KUMR', 'TCG_TABARD_OF_FROST'),
    ('HQGS-JTD6-KC6B-6WXE', 'TCG_TABARD_OF_FROST'),
    ('7U88-J4WM-QMMW-66TU', 'TCG_TABARD_OF_FROST');

-- TCG_PERPETUAL_PURPLE_FIREWORK  (Perpetual Purple Firework)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('KWTX-HVXB-8YWU-A4AM', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('6NQT-Z46C-GETB-28X3', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('UEZV-TZMP-7EXE-QGN6', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('72NE-TBUU-64CQ-CW83', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('RAJM-KTGR-YDF9-6XXS', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('CU9Q-7RS3-3F3C-MD37', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('3M72-GHNY-VDS9-HNJY', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('WZ8E-Z928-TU3R-QYTQ', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('6KQ6-MTF4-EA5Q-ANXJ', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('63CB-XUSZ-7AYA-SKKD', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('NRA6-YWZ8-BG65-WRXB', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('9W4Q-RNWQ-PM5T-479X', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('ZT6H-K3DG-RNJW-M6WF', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('QT52-5QEP-NNDE-5DMH', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('6374-ZGR9-QVP4-MW2K', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('EEDC-T3EV-KJEC-5TVQ', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('6GAB-B4CP-Z8XH-45G3', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('8ERP-6GUA-JKZ4-FBXK', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('KNGG-8QNV-3ZMW-7UTT', 'TCG_PERPETUAL_PURPLE_FIREWORK'),
    ('4JS5-YNC3-VVK7-W9Q4', 'TCG_PERPETUAL_PURPLE_FIREWORK');

-- TCG_CARVED_OGRE_IDOL  (Carved Ogre Idol)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('R3WR-ZS9T-6BCG-ET23', 'TCG_CARVED_OGRE_IDOL'),
    ('PKW3-2YHZ-CHTY-A8F5', 'TCG_CARVED_OGRE_IDOL'),
    ('F4HG-H58D-MN32-4GQ5', 'TCG_CARVED_OGRE_IDOL'),
    ('A5X8-PMY9-4CZU-RS88', 'TCG_CARVED_OGRE_IDOL'),
    ('BYDM-4XVA-5EXC-XEYV', 'TCG_CARVED_OGRE_IDOL'),
    ('M53W-KS5N-ZMSY-JZPE', 'TCG_CARVED_OGRE_IDOL'),
    ('NKQZ-M5WJ-ZSRU-ZVAV', 'TCG_CARVED_OGRE_IDOL'),
    ('9C6U-7CCS-D685-W9PX', 'TCG_CARVED_OGRE_IDOL'),
    ('E9TJ-NSRP-WATC-DK2Q', 'TCG_CARVED_OGRE_IDOL'),
    ('ZZA3-6JZM-QJCY-RV79', 'TCG_CARVED_OGRE_IDOL'),
    ('S3B8-EMUX-M5KG-4KHD', 'TCG_CARVED_OGRE_IDOL'),
    ('D7YX-PSRM-8UM6-RAEB', 'TCG_CARVED_OGRE_IDOL'),
    ('YREQ-RFM7-V2TE-8GVM', 'TCG_CARVED_OGRE_IDOL'),
    ('J7XA-R2S9-D87J-6BXR', 'TCG_CARVED_OGRE_IDOL'),
    ('XZ9J-FNDZ-T7KE-QX5A', 'TCG_CARVED_OGRE_IDOL'),
    ('KYT3-M2BW-KF7P-U3AF', 'TCG_CARVED_OGRE_IDOL'),
    ('7U4K-ZF77-KAA4-9RJP', 'TCG_CARVED_OGRE_IDOL'),
    ('43T5-CHYV-XJD4-5RM7', 'TCG_CARVED_OGRE_IDOL'),
    ('VSCF-2JXY-X8V7-9ZJF', 'TCG_CARVED_OGRE_IDOL'),
    ('9R2E-KQ29-7XAE-5VGB', 'TCG_CARVED_OGRE_IDOL');

-- TCG_TABARD_OF_THE_ARCANE  (Tabard of the Arcane)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('TMRQ-4WTB-7D7R-R6QP', 'TCG_TABARD_OF_THE_ARCANE'),
    ('V3AP-2GPT-9DH2-UV7R', 'TCG_TABARD_OF_THE_ARCANE'),
    ('2C7U-XK6Y-HBWN-F9JR', 'TCG_TABARD_OF_THE_ARCANE'),
    ('XEJ9-X3VT-9WPP-QFW8', 'TCG_TABARD_OF_THE_ARCANE'),
    ('CYD6-KWC5-XRQJ-HKUG', 'TCG_TABARD_OF_THE_ARCANE'),
    ('PNFX-74AX-5SM5-QB5Z', 'TCG_TABARD_OF_THE_ARCANE'),
    ('6HT6-E88B-9YRJ-A37P', 'TCG_TABARD_OF_THE_ARCANE'),
    ('MTT9-8E2C-WWQR-J3EY', 'TCG_TABARD_OF_THE_ARCANE'),
    ('QGE3-H5JB-RYBE-FNG6', 'TCG_TABARD_OF_THE_ARCANE'),
    ('G3GM-BBD7-ZAGE-FNJF', 'TCG_TABARD_OF_THE_ARCANE'),
    ('M4DY-3A6K-UQF3-F4HC', 'TCG_TABARD_OF_THE_ARCANE'),
    ('TCDA-5FFH-7P8F-9DBM', 'TCG_TABARD_OF_THE_ARCANE'),
    ('4ZH8-98FY-MJNZ-B824', 'TCG_TABARD_OF_THE_ARCANE'),
    ('VY5G-RE5J-6XNV-ZT5T', 'TCG_TABARD_OF_THE_ARCANE'),
    ('3DB3-RZZC-D742-2VSA', 'TCG_TABARD_OF_THE_ARCANE'),
    ('H9UK-7YPJ-M6U6-ARJQ', 'TCG_TABARD_OF_THE_ARCANE'),
    ('K3HU-YKSR-DEFA-DH94', 'TCG_TABARD_OF_THE_ARCANE'),
    ('9JHZ-CDSZ-6UWF-B4DX', 'TCG_TABARD_OF_THE_ARCANE'),
    ('AR7A-AZKK-NMBG-6V8A', 'TCG_TABARD_OF_THE_ARCANE'),
    ('RMFN-BZ4S-J82F-4X5T', 'TCG_TABARD_OF_THE_ARCANE');

-- TCG_TABARD_OF_BRILLIANCE  (Tabard of Brilliance)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('QFGB-N6NG-4D8G-UFQP', 'TCG_TABARD_OF_BRILLIANCE'),
    ('WTDV-3PZY-68E5-J8AE', 'TCG_TABARD_OF_BRILLIANCE'),
    ('Q6YV-RCDZ-FKXV-QBZN', 'TCG_TABARD_OF_BRILLIANCE'),
    ('3W36-YJ7B-G5JW-QMJY', 'TCG_TABARD_OF_BRILLIANCE'),
    ('AXWX-XEZV-DASQ-GYS5', 'TCG_TABARD_OF_BRILLIANCE'),
    ('S7AK-7CTF-UH4B-ZMD6', 'TCG_TABARD_OF_BRILLIANCE'),
    ('N7H9-MB53-FR7M-GTBK', 'TCG_TABARD_OF_BRILLIANCE'),
    ('3R5V-KX6Z-8HHB-RVVD', 'TCG_TABARD_OF_BRILLIANCE'),
    ('QZXK-EEC7-4U48-EETJ', 'TCG_TABARD_OF_BRILLIANCE'),
    ('Y4H9-7397-3JBK-2HDQ', 'TCG_TABARD_OF_BRILLIANCE'),
    ('H37F-NVKN-HKS3-VFJR', 'TCG_TABARD_OF_BRILLIANCE'),
    ('ZAJ2-JCUW-9X6T-5D7V', 'TCG_TABARD_OF_BRILLIANCE'),
    ('PR5Y-9MDK-6SE5-43Q5', 'TCG_TABARD_OF_BRILLIANCE'),
    ('C4B5-A843-KUVW-B6TH', 'TCG_TABARD_OF_BRILLIANCE'),
    ('3TFH-G4HQ-SRDR-74GD', 'TCG_TABARD_OF_BRILLIANCE'),
    ('3CV8-2PMJ-Q5C4-F4E5', 'TCG_TABARD_OF_BRILLIANCE'),
    ('G5XH-J3FY-J5MS-T495', 'TCG_TABARD_OF_BRILLIANCE'),
    ('EF2K-78Y8-SWWM-9EQE', 'TCG_TABARD_OF_BRILLIANCE'),
    ('WA65-GDHU-9T9M-3KBR', 'TCG_TABARD_OF_BRILLIANCE'),
    ('F9JC-FFBW-72UU-P286', 'TCG_TABARD_OF_BRILLIANCE');

-- TCG_TABARD_OF_THE_DEFENDER  (Tabard of the Defender)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('WUDP-SYXZ-HV9R-GUGZ', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('BJ7H-A34X-6PBX-N9CJ', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('BEBZ-8NHX-7MWC-7VUH', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('AVWV-HN8J-UWFD-AYQD', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('GA8Y-VYMS-B8TC-75JG', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('5SDD-XD3T-TTFP-YNWS', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('3DEP-R993-5MZ6-3QA2', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('5TNX-3CQG-8FQ6-XV73', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('BPMM-5AQT-DV6J-3PUM', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('JJ47-CGSG-U4H5-R7CU', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('PMTY-B56R-R8VE-95RA', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('RFHZ-4EBF-ZJXW-ANH4', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('MZNR-2X76-CGX5-42MY', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('T43U-3W2H-H4W7-JZXV', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('2JFW-87YJ-NJ7U-WHWC', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('BRKW-CXMH-PXAB-CVAY', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('2MA9-WS4F-ZBCM-RFV2', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('T46H-9SRM-APG9-EMEA', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('6FUC-ZMPP-QCCK-ST83', 'TCG_TABARD_OF_THE_DEFENDER'),
    ('UM3V-X9ZP-FRJ8-3BVR', 'TCG_TABARD_OF_THE_DEFENDER');

-- TCG_TABARD_OF_FURY  (Tabard of Fury)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('GAFS-G7PY-WB85-B9MD', 'TCG_TABARD_OF_FURY'),
    ('YJVG-UQWG-J72B-SVZJ', 'TCG_TABARD_OF_FURY'),
    ('R85X-5U58-ASEA-BPH3', 'TCG_TABARD_OF_FURY'),
    ('W2PP-C2TU-A7ZZ-JNK9', 'TCG_TABARD_OF_FURY'),
    ('23XN-EU29-Y4XD-94HE', 'TCG_TABARD_OF_FURY'),
    ('QUBK-A9E7-ZQBU-R4CN', 'TCG_TABARD_OF_FURY'),
    ('UMY7-9QK4-AVJK-X635', 'TCG_TABARD_OF_FURY'),
    ('AZND-FTXR-5WWX-QMJ8', 'TCG_TABARD_OF_FURY'),
    ('E3UY-ZH9U-RJ6H-FK5P', 'TCG_TABARD_OF_FURY'),
    ('XQYZ-6EMV-B6YV-WG2E', 'TCG_TABARD_OF_FURY'),
    ('2HR9-6TPQ-B5PE-835G', 'TCG_TABARD_OF_FURY'),
    ('KMHW-4GJF-626R-X3JV', 'TCG_TABARD_OF_FURY'),
    ('3QN4-S96R-JKYE-HBWB', 'TCG_TABARD_OF_FURY'),
    ('QMRF-S676-4WQ5-Y52G', 'TCG_TABARD_OF_FURY'),
    ('D3P2-MAZP-T52Y-MMAD', 'TCG_TABARD_OF_FURY'),
    ('TRX8-92VY-93PX-W8M3', 'TCG_TABARD_OF_FURY'),
    ('FY6F-UEJ5-7CAS-TT7W', 'TCG_TABARD_OF_FURY'),
    ('C8US-3EEU-7CHS-NCP8', 'TCG_TABARD_OF_FURY'),
    ('JXD8-DJQY-FTBT-PEHP', 'TCG_TABARD_OF_FURY'),
    ('TSUT-7KPP-2M67-93ZT', 'TCG_TABARD_OF_FURY');

-- TCG_TABARD_OF_NATURE  (Tabard of Nature)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('BEQZ-Z557-YUQ4-7NZV', 'TCG_TABARD_OF_NATURE'),
    ('M8ST-WM2K-6DEJ-MHF4', 'TCG_TABARD_OF_NATURE'),
    ('J67J-DK5V-XY44-AU2K', 'TCG_TABARD_OF_NATURE'),
    ('SYZG-V9FU-5E9S-P8FB', 'TCG_TABARD_OF_NATURE'),
    ('YPF5-3447-KA4B-F4DJ', 'TCG_TABARD_OF_NATURE'),
    ('8VD3-8KQK-K2WB-DPS5', 'TCG_TABARD_OF_NATURE'),
    ('X7NN-3VW8-HPKS-CK8V', 'TCG_TABARD_OF_NATURE'),
    ('Q87U-3SAZ-KXHW-34YB', 'TCG_TABARD_OF_NATURE'),
    ('4PA4-U5GM-9RYS-KHKT', 'TCG_TABARD_OF_NATURE'),
    ('VSJC-EN33-68HM-E5VY', 'TCG_TABARD_OF_NATURE'),
    ('9EEP-MDA3-QN34-URSM', 'TCG_TABARD_OF_NATURE'),
    ('586K-6X7G-4ZKA-T8F8', 'TCG_TABARD_OF_NATURE'),
    ('THPT-8SM8-8WYK-2ZM2', 'TCG_TABARD_OF_NATURE'),
    ('MRJX-SC8Z-SPNW-T4UV', 'TCG_TABARD_OF_NATURE'),
    ('G3MY-QS9Q-J6NC-9D7U', 'TCG_TABARD_OF_NATURE'),
    ('WNJ9-XGHT-FTAT-AWGU', 'TCG_TABARD_OF_NATURE'),
    ('B9KG-STUR-PCBU-AJ94', 'TCG_TABARD_OF_NATURE'),
    ('865D-EBGF-E5X4-GST6', 'TCG_TABARD_OF_NATURE'),
    ('TEWW-BC4M-ZCUH-4ZFE', 'TCG_TABARD_OF_NATURE'),
    ('3KNF-696U-RMCS-F6BH', 'TCG_TABARD_OF_NATURE');

-- TCG_TABARD_OF_THE_VOID  (Tabard of the Void)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('G3FQ-789H-8HWN-WQY3', 'TCG_TABARD_OF_THE_VOID'),
    ('BNYT-A3YS-VDDC-GYMS', 'TCG_TABARD_OF_THE_VOID'),
    ('V75M-5JBY-B958-F6RX', 'TCG_TABARD_OF_THE_VOID'),
    ('6EST-NF6Y-F5UR-B4Q6', 'TCG_TABARD_OF_THE_VOID'),
    ('KAU7-5QPQ-7AUF-N6FS', 'TCG_TABARD_OF_THE_VOID'),
    ('XNM6-97HN-KYJQ-34YK', 'TCG_TABARD_OF_THE_VOID'),
    ('K99Z-64NR-ZZE9-4ZV2', 'TCG_TABARD_OF_THE_VOID'),
    ('4PPM-SFFD-NB9P-5FP5', 'TCG_TABARD_OF_THE_VOID'),
    ('YA7S-F3EZ-ZRD7-XAW2', 'TCG_TABARD_OF_THE_VOID'),
    ('ZNBT-JMT4-UFHX-2FRN', 'TCG_TABARD_OF_THE_VOID'),
    ('GXEQ-JY5Z-XXZB-PQBF', 'TCG_TABARD_OF_THE_VOID'),
    ('8TCQ-NRXA-EKZZ-T3HC', 'TCG_TABARD_OF_THE_VOID'),
    ('MPJV-CWQ9-HP6K-DSAZ', 'TCG_TABARD_OF_THE_VOID'),
    ('XJTC-URNC-6Q7T-SB8N', 'TCG_TABARD_OF_THE_VOID'),
    ('29FQ-XCFH-PNE8-7BX8', 'TCG_TABARD_OF_THE_VOID'),
    ('BCGA-N9WK-ZE6X-KKA7', 'TCG_TABARD_OF_THE_VOID'),
    ('TQNR-ZNG6-7HWR-5ENA', 'TCG_TABARD_OF_THE_VOID'),
    ('Z6R8-CTSV-582T-ZSDY', 'TCG_TABARD_OF_THE_VOID'),
    ('R9WX-AX4N-JANN-2KE6', 'TCG_TABARD_OF_THE_VOID'),
    ('CG5M-MRCR-WYFF-UJF2', 'TCG_TABARD_OF_THE_VOID');

-- TCG_LANDROS_PET_BOX  (Landro's Pet Box)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('JJMT-X7XB-SWWC-ZRZK', 'TCG_LANDROS_PET_BOX'),
    ('DCZD-R7CU-KQRM-96QS', 'TCG_LANDROS_PET_BOX'),
    ('9XZW-NAH6-MSEF-JFQW', 'TCG_LANDROS_PET_BOX'),
    ('85N3-8V2R-DXMN-JWR5', 'TCG_LANDROS_PET_BOX'),
    ('4RFS-VAQZ-K925-2ZPB', 'TCG_LANDROS_PET_BOX'),
    ('R7VU-ERRG-XEMA-MNRH', 'TCG_LANDROS_PET_BOX'),
    ('R76U-3WFA-5HFV-FRNY', 'TCG_LANDROS_PET_BOX'),
    ('SKWU-XC8K-6CFY-XQDD', 'TCG_LANDROS_PET_BOX'),
    ('JNB4-9N8Z-M4QV-HTBD', 'TCG_LANDROS_PET_BOX'),
    ('GPSC-Y68F-N45X-KTPT', 'TCG_LANDROS_PET_BOX'),
    ('ZQ8Y-QRQQ-5WHH-ARCJ', 'TCG_LANDROS_PET_BOX'),
    ('FXK6-TV5H-5ABG-8HT4', 'TCG_LANDROS_PET_BOX'),
    ('5RDK-X2M5-G7E4-DXQZ', 'TCG_LANDROS_PET_BOX'),
    ('TQJ3-ZUJU-NSPE-AWG2', 'TCG_LANDROS_PET_BOX'),
    ('7PYB-4G7K-VURT-N4H6', 'TCG_LANDROS_PET_BOX'),
    ('ZAJS-ZA87-CCGR-ACSS', 'TCG_LANDROS_PET_BOX'),
    ('M7RV-GHRN-PPS6-CTQU', 'TCG_LANDROS_PET_BOX'),
    ('Q8DW-MZ5C-R4KF-XTXJ', 'TCG_LANDROS_PET_BOX'),
    ('4K9E-M66J-VTQG-SZN7', 'TCG_LANDROS_PET_BOX'),
    ('CDBM-TDCD-H7TD-QGT3', 'TCG_LANDROS_PET_BOX');

-- BLIZZCON_MURKY  (Murky (Blue Murloc Egg))
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('G7ZB-VSYD-36VS-4MW3', 'BLIZZCON_MURKY'),
    ('AU8Q-BRU4-CWHG-9NC9', 'BLIZZCON_MURKY'),
    ('PHJX-A5YZ-G9T7-2YSV', 'BLIZZCON_MURKY'),
    ('URXW-GKS3-WM6P-4Q3J', 'BLIZZCON_MURKY'),
    ('8BKT-BEC9-SKV7-KR9H', 'BLIZZCON_MURKY'),
    ('VXKV-ZWKK-S2QE-CTXP', 'BLIZZCON_MURKY'),
    ('YERQ-XQP5-T6E5-T42H', 'BLIZZCON_MURKY'),
    ('8RBE-7A63-6X3U-DVZX', 'BLIZZCON_MURKY'),
    ('RZZ7-G2SE-TZZT-98XR', 'BLIZZCON_MURKY'),
    ('GNQ4-N5M3-7THF-X946', 'BLIZZCON_MURKY'),
    ('NYHM-R6VA-9XQ3-8RRN', 'BLIZZCON_MURKY'),
    ('ZV46-6GS7-VZ9Y-2CY9', 'BLIZZCON_MURKY'),
    ('NNBB-H87N-VGRV-CPYE', 'BLIZZCON_MURKY'),
    ('VQW8-ZXWT-FUMQ-W7AU', 'BLIZZCON_MURKY'),
    ('BCCR-K98H-4R8X-A79X', 'BLIZZCON_MURKY'),
    ('TZMG-XPZY-HYFJ-W4E5', 'BLIZZCON_MURKY'),
    ('G8FP-MTDY-ST8C-6MXR', 'BLIZZCON_MURKY'),
    ('QYGZ-7XEW-HJ99-TQR7', 'BLIZZCON_MURKY'),
    ('KD85-D6DC-GMZC-XNPT', 'BLIZZCON_MURKY'),
    ('S434-WRMM-P2QR-Z8BC', 'BLIZZCON_MURKY');

-- BLIZZCON_MURLOC_COSTUME  (Murloc Costume)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('GJVG-C4AS-TWDM-KBQF', 'BLIZZCON_MURLOC_COSTUME'),
    ('6B2X-APNG-M9AH-PAFR', 'BLIZZCON_MURLOC_COSTUME'),
    ('FS7T-Z7H5-9NV4-K7NB', 'BLIZZCON_MURLOC_COSTUME'),
    ('F4EK-YCPA-PENG-468B', 'BLIZZCON_MURLOC_COSTUME'),
    ('C7WG-G469-3UDX-R3G9', 'BLIZZCON_MURLOC_COSTUME'),
    ('3XRM-65T4-HSH3-7UBD', 'BLIZZCON_MURLOC_COSTUME'),
    ('2N5E-GNN8-NERS-F2HT', 'BLIZZCON_MURLOC_COSTUME'),
    ('QWN6-7QHU-R2WZ-EYVN', 'BLIZZCON_MURLOC_COSTUME'),
    ('AQEA-D3Q8-FXYA-A6JT', 'BLIZZCON_MURLOC_COSTUME'),
    ('F6NP-YTXZ-JR8X-AKRA', 'BLIZZCON_MURLOC_COSTUME'),
    ('A8RB-Q7JW-VKDH-RBRV', 'BLIZZCON_MURLOC_COSTUME'),
    ('F44U-HJE5-3D39-97ET', 'BLIZZCON_MURLOC_COSTUME'),
    ('H3U8-ANEX-MUE9-Q4DD', 'BLIZZCON_MURLOC_COSTUME'),
    ('KY2C-WFDR-5YMG-PFJA', 'BLIZZCON_MURLOC_COSTUME'),
    ('ZXZU-5RME-Q7X4-FKQW', 'BLIZZCON_MURLOC_COSTUME'),
    ('7FSD-E6DB-5NR6-6XKQ', 'BLIZZCON_MURLOC_COSTUME'),
    ('WQCS-FMXQ-UJ9Y-QEH3', 'BLIZZCON_MURLOC_COSTUME'),
    ('2ZZF-W5A6-9MZN-FHP5', 'BLIZZCON_MURLOC_COSTUME'),
    ('3CJW-ADGD-MYK8-PGWX', 'BLIZZCON_MURLOC_COSTUME'),
    ('BYAM-KNGP-HBEZ-5B2H', 'BLIZZCON_MURLOC_COSTUME');

-- BLIZZCON_BIG_BLIZZARD_BEAR  (Big Blizzard Bear)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('5DPY-EUEB-PZ9Q-WR5T', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('53EK-9Y6H-B6B9-FXDA', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('M5Y7-46RT-MKWN-A2RD', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('TSHJ-8G6G-7GWF-Q2QJ', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('BX4N-Q5EM-JK2Z-78YJ', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('NJDC-X9SR-VV86-KMFN', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('VAY6-SAHB-YQCA-FEDG', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('786B-4ME9-CZJA-8AAU', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('DYWJ-FFTP-6UJC-P7GZ', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('VTDZ-JEYB-WMYY-TSBU', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('8K8R-JNWD-FRXB-5Z58', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('X2H6-7N8E-RJNP-TEE8', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('AW4Y-MMNJ-58RP-AKZT', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('N8V4-AQ8U-X85Q-X6XE', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('QQY7-SAEY-TF4X-35QM', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('JG7A-B3RG-HSBU-AKVW', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('H6Y7-H3UT-ZNR7-932Q', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('WKET-9D7X-CRX5-NMDA', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('QBRU-QAGC-N3YS-N8G9', 'BLIZZCON_BIG_BLIZZARD_BEAR'),
    ('TPDS-WXX2-7RHZ-MQ58', 'BLIZZCON_BIG_BLIZZARD_BEAR');

-- PROMO_GURKY  (Gurky (Pink Murloc Egg))
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('PUCB-BXJ5-RKVT-4BGM', 'PROMO_GURKY'),
    ('QCMK-8MSC-GNGE-ZCZJ', 'PROMO_GURKY'),
    ('YZ3C-8UEK-UQ2F-Y4YB', 'PROMO_GURKY'),
    ('AUPB-F7M3-MHTT-79DN', 'PROMO_GURKY'),
    ('VBP2-YXCF-RSP8-QX49', 'PROMO_GURKY'),
    ('7GJ7-NUG9-B3AS-59JK', 'PROMO_GURKY'),
    ('EE96-BGVQ-F74E-YB73', 'PROMO_GURKY'),
    ('UKDU-38D2-BH4F-D8VP', 'PROMO_GURKY'),
    ('MD8C-EASU-UGCJ-RX8R', 'PROMO_GURKY'),
    ('CFF3-SKFR-Y8Q5-ZF76', 'PROMO_GURKY'),
    ('52HF-RZE6-R4WK-M2U9', 'PROMO_GURKY'),
    ('H9CR-UPDR-YQGR-DKKR', 'PROMO_GURKY'),
    ('ZMB7-CVMN-RDMM-9XQ7', 'PROMO_GURKY'),
    ('6JBN-NF53-EX94-FH4D', 'PROMO_GURKY'),
    ('Y2PD-2QGN-GA8E-7B89', 'PROMO_GURKY'),
    ('JNJN-7NP3-P2UP-6MPD', 'PROMO_GURKY'),
    ('YADN-Q3VZ-N6E6-6TFX', 'PROMO_GURKY'),
    ('7F84-7TPU-A4B9-347N', 'PROMO_GURKY'),
    ('P3K4-MVGS-4ZRP-XQ9N', 'PROMO_GURKY'),
    ('BVV2-6W8Q-2U4C-JKPZ', 'PROMO_GURKY');

-- PROMO_ORANGE_MURLOC_EGG  (Orange Murloc Egg)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('GNE8-TY8N-JFWR-WM5M', 'PROMO_ORANGE_MURLOC_EGG'),
    ('ERD4-YVWW-ZQ6C-EES2', 'PROMO_ORANGE_MURLOC_EGG'),
    ('3V3P-Q4JV-V9NT-6WZ8', 'PROMO_ORANGE_MURLOC_EGG'),
    ('8ERC-7KH8-MRAN-VF2Z', 'PROMO_ORANGE_MURLOC_EGG'),
    ('YNRF-58R6-NM4Y-3K4W', 'PROMO_ORANGE_MURLOC_EGG'),
    ('QZ4T-XGM4-3SZ4-2BQZ', 'PROMO_ORANGE_MURLOC_EGG'),
    ('C8G6-AXHQ-BJAB-HRDF', 'PROMO_ORANGE_MURLOC_EGG'),
    ('XQKC-ZAHK-D632-3EMD', 'PROMO_ORANGE_MURLOC_EGG'),
    ('MG4S-ZCJR-56CB-FQK7', 'PROMO_ORANGE_MURLOC_EGG'),
    ('G93J-22UB-6XSQ-UTW3', 'PROMO_ORANGE_MURLOC_EGG'),
    ('FBDB-CRHW-6CM2-XPXS', 'PROMO_ORANGE_MURLOC_EGG'),
    ('Z7V4-GH69-SX2X-XXMK', 'PROMO_ORANGE_MURLOC_EGG'),
    ('9APE-GPMK-6DBK-FD9F', 'PROMO_ORANGE_MURLOC_EGG'),
    ('BGE8-HTDM-KXP2-3AUW', 'PROMO_ORANGE_MURLOC_EGG'),
    ('YZVQ-7CT5-M8NA-23JH', 'PROMO_ORANGE_MURLOC_EGG'),
    ('QJD6-N96S-QM97-R22N', 'PROMO_ORANGE_MURLOC_EGG'),
    ('5YYT-RA8X-R48W-EY73', 'PROMO_ORANGE_MURLOC_EGG'),
    ('FTDF-NPUK-957E-ZFJA', 'PROMO_ORANGE_MURLOC_EGG'),
    ('NJTH-4EXV-W4AE-GTVE', 'PROMO_ORANGE_MURLOC_EGG'),
    ('Y55K-CAQT-GYP7-NYMU', 'PROMO_ORANGE_MURLOC_EGG');

-- PROMO_WHITE_MURLOC_EGG  (White Murloc Egg)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('PPKB-WWNY-WDCB-P2HK', 'PROMO_WHITE_MURLOC_EGG'),
    ('SJ3F-9YSW-JP3F-PK35', 'PROMO_WHITE_MURLOC_EGG'),
    ('4NUV-QAHF-PPP2-BCBN', 'PROMO_WHITE_MURLOC_EGG'),
    ('E3PC-G42K-MPK3-U2MK', 'PROMO_WHITE_MURLOC_EGG'),
    ('5VME-RR3N-RDVU-W8NJ', 'PROMO_WHITE_MURLOC_EGG'),
    ('W75N-YWXN-G946-JMWC', 'PROMO_WHITE_MURLOC_EGG'),
    ('KQEN-J8VS-BM7D-K5VW', 'PROMO_WHITE_MURLOC_EGG'),
    ('XX3P-B2MT-B5WB-BKRE', 'PROMO_WHITE_MURLOC_EGG'),
    ('PRPD-HRH9-24W5-3Q24', 'PROMO_WHITE_MURLOC_EGG'),
    ('C2HW-QMVQ-K6T8-8RDR', 'PROMO_WHITE_MURLOC_EGG'),
    ('J4AK-8VFX-S5US-NC2D', 'PROMO_WHITE_MURLOC_EGG'),
    ('NMXZ-PUGT-ZNZB-8DXK', 'PROMO_WHITE_MURLOC_EGG'),
    ('CDKC-H7VD-KJFH-2U5G', 'PROMO_WHITE_MURLOC_EGG'),
    ('S9JH-JW8V-AZMN-4HZK', 'PROMO_WHITE_MURLOC_EGG'),
    ('WX9U-V9YZ-2AVU-4T5S', 'PROMO_WHITE_MURLOC_EGG'),
    ('DB2H-F8CS-8T8E-CRJ7', 'PROMO_WHITE_MURLOC_EGG'),
    ('GGVY-XFYU-EYCJ-9WSG', 'PROMO_WHITE_MURLOC_EGG'),
    ('6EYY-FWM5-AG9Z-JER4', 'PROMO_WHITE_MURLOC_EGG'),
    ('QEV9-DZRB-9FAQ-MM6Q', 'PROMO_WHITE_MURLOC_EGG'),
    ('AXCT-NW9K-KFSU-SRUD', 'PROMO_WHITE_MURLOC_EGG');

-- PROMO_HEAVY_MURLOC_EGG  (Heavy Murloc Egg)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('ACYG-25M4-QBXD-369N', 'PROMO_HEAVY_MURLOC_EGG'),
    ('GNWX-HM6X-N7FU-JJH5', 'PROMO_HEAVY_MURLOC_EGG'),
    ('RYD4-89HG-7RME-U8KP', 'PROMO_HEAVY_MURLOC_EGG'),
    ('9H8Y-NCAH-4Z6P-2J5S', 'PROMO_HEAVY_MURLOC_EGG'),
    ('N935-97RD-4497-APV5', 'PROMO_HEAVY_MURLOC_EGG'),
    ('RQX2-3NJ5-35RV-CF6N', 'PROMO_HEAVY_MURLOC_EGG'),
    ('ZAKS-YWAJ-3GE7-78SM', 'PROMO_HEAVY_MURLOC_EGG'),
    ('HYGQ-V9CX-2FDK-6Y2D', 'PROMO_HEAVY_MURLOC_EGG'),
    ('ZWQ7-RTVD-XRVX-G898', 'PROMO_HEAVY_MURLOC_EGG'),
    ('EGD2-FUYF-TN4H-THAG', 'PROMO_HEAVY_MURLOC_EGG'),
    ('4TET-2UNZ-X6W9-QRNJ', 'PROMO_HEAVY_MURLOC_EGG'),
    ('DVA9-ZUE3-PZUS-SDP4', 'PROMO_HEAVY_MURLOC_EGG'),
    ('B9FT-ENXR-HXNF-TJD5', 'PROMO_HEAVY_MURLOC_EGG'),
    ('E36Y-4XSD-NADG-QC78', 'PROMO_HEAVY_MURLOC_EGG'),
    ('CKEM-WADJ-CNXS-GG9N', 'PROMO_HEAVY_MURLOC_EGG'),
    ('2FKG-F66Q-EHCC-MHH4', 'PROMO_HEAVY_MURLOC_EGG'),
    ('KWSS-X785-SS8C-THPA', 'PROMO_HEAVY_MURLOC_EGG'),
    ('P536-TF69-GC4U-SDU6', 'PROMO_HEAVY_MURLOC_EGG'),
    ('S8H6-YFT8-URMZ-R5MH', 'PROMO_HEAVY_MURLOC_EGG'),
    ('2QSY-9KHV-JYSK-ZMRP', 'PROMO_HEAVY_MURLOC_EGG');

-- PROMO_MURKIMUS_SPEAR  (Murkimus' Little Spear)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('6XAT-BSV3-TKHV-7FY2', 'PROMO_MURKIMUS_SPEAR'),
    ('Y2QP-QFJ3-S7CY-SBWS', 'PROMO_MURKIMUS_SPEAR'),
    ('BANX-7SXC-JKYP-G5QP', 'PROMO_MURKIMUS_SPEAR'),
    ('UVD3-FN6S-YH6Z-376M', 'PROMO_MURKIMUS_SPEAR'),
    ('DNVJ-FGHP-ZBWG-N6Z5', 'PROMO_MURKIMUS_SPEAR'),
    ('635M-YNF4-BB5F-ZAX2', 'PROMO_MURKIMUS_SPEAR'),
    ('8C6W-D7Q4-QAER-X57D', 'PROMO_MURKIMUS_SPEAR'),
    ('BH7G-D2UD-ACUS-MUCJ', 'PROMO_MURKIMUS_SPEAR'),
    ('H9AN-JBFW-H9R5-CJ9S', 'PROMO_MURKIMUS_SPEAR'),
    ('SPWX-SNY4-R99W-4S9P', 'PROMO_MURKIMUS_SPEAR'),
    ('D59J-382N-HTB2-4X2X', 'PROMO_MURKIMUS_SPEAR'),
    ('J5TK-NUUT-8ZCM-XQSW', 'PROMO_MURKIMUS_SPEAR'),
    ('878R-FQXN-JBUC-MGC3', 'PROMO_MURKIMUS_SPEAR'),
    ('DTA5-WXAH-45NT-56KG', 'PROMO_MURKIMUS_SPEAR'),
    ('5YQU-63ZK-W8A6-7CDM', 'PROMO_MURKIMUS_SPEAR'),
    ('E7RB-AFSN-77HY-VMC6', 'PROMO_MURKIMUS_SPEAR'),
    ('XUNN-E737-PD34-G7ZR', 'PROMO_MURKIMUS_SPEAR'),
    ('6RHJ-QF76-82BK-FAXA', 'PROMO_MURKIMUS_SPEAR'),
    ('MV4G-UMET-B375-26BM', 'PROMO_MURKIMUS_SPEAR'),
    ('5UU4-V3NX-WBQT-JJ26', 'PROMO_MURKIMUS_SPEAR');

-- PROMO_ZERGLING_LEASH  (Zergling Leash)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('K3KG-XAVA-MTUN-ASK3', 'PROMO_ZERGLING_LEASH'),
    ('6HJ9-NBGW-WGY8-8NFU', 'PROMO_ZERGLING_LEASH'),
    ('ZM7X-4SU6-6JD3-25EY', 'PROMO_ZERGLING_LEASH'),
    ('TYX8-VF43-26QE-6MYR', 'PROMO_ZERGLING_LEASH'),
    ('N3KU-8QDZ-UQKN-7U4R', 'PROMO_ZERGLING_LEASH'),
    ('66XS-X88G-8QHW-XH3Q', 'PROMO_ZERGLING_LEASH'),
    ('QAUQ-P6RS-WK9C-VSPQ', 'PROMO_ZERGLING_LEASH'),
    ('JXFJ-TCF3-4N7R-5M27', 'PROMO_ZERGLING_LEASH'),
    ('C88A-WAGC-BBNW-X72T', 'PROMO_ZERGLING_LEASH'),
    ('WU7N-FPU4-CH8Q-767D', 'PROMO_ZERGLING_LEASH'),
    ('JDU6-AF23-4M72-QGPN', 'PROMO_ZERGLING_LEASH'),
    ('9WFV-NWDJ-4226-MU5J', 'PROMO_ZERGLING_LEASH'),
    ('ZNYG-8RBX-T5FM-A58S', 'PROMO_ZERGLING_LEASH'),
    ('KK3A-QK57-ZTUC-SM5V', 'PROMO_ZERGLING_LEASH'),
    ('SGRN-M3PH-XEN7-HAJ7', 'PROMO_ZERGLING_LEASH'),
    ('4SWR-8FCK-MUPB-2HDY', 'PROMO_ZERGLING_LEASH'),
    ('7BT7-GQUF-HJWV-3DTR', 'PROMO_ZERGLING_LEASH'),
    ('F93E-QSJH-FMEF-PZUU', 'PROMO_ZERGLING_LEASH'),
    ('79MU-HMKC-QHZ9-YXJE', 'PROMO_ZERGLING_LEASH'),
    ('YZYW-NSRT-U8Z4-A94G', 'PROMO_ZERGLING_LEASH');

-- PROMO_PANDA_COLLAR  (Panda Collar)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('6TMC-6UXA-E6JE-KDXE', 'PROMO_PANDA_COLLAR'),
    ('F82F-Q86W-HB5Q-2Y6A', 'PROMO_PANDA_COLLAR'),
    ('G9CM-HQU4-J78N-VY2C', 'PROMO_PANDA_COLLAR'),
    ('BEU9-BRR6-VKPR-QNSK', 'PROMO_PANDA_COLLAR'),
    ('MNXB-CEKY-2RBT-8QBR', 'PROMO_PANDA_COLLAR'),
    ('2JK6-DA5D-FT59-A822', 'PROMO_PANDA_COLLAR'),
    ('A5NF-F436-BJFS-S3XU', 'PROMO_PANDA_COLLAR'),
    ('CDK9-UTGQ-E8XD-TV3A', 'PROMO_PANDA_COLLAR'),
    ('JJ9P-QUA5-66GM-SRZF', 'PROMO_PANDA_COLLAR'),
    ('75PD-9D66-5TXS-PJVN', 'PROMO_PANDA_COLLAR'),
    ('XS55-WS9M-DYDU-QUCF', 'PROMO_PANDA_COLLAR'),
    ('8YGM-GTAC-XPN9-RAY5', 'PROMO_PANDA_COLLAR'),
    ('CHAP-RRQK-QF43-2353', 'PROMO_PANDA_COLLAR'),
    ('2R38-B3SQ-H2AX-FQR6', 'PROMO_PANDA_COLLAR'),
    ('XQCS-4Y3U-MG2S-8RN4', 'PROMO_PANDA_COLLAR'),
    ('6T9E-SATF-6T3Q-76AB', 'PROMO_PANDA_COLLAR'),
    ('FJJQ-7FUU-6JJT-9ESK', 'PROMO_PANDA_COLLAR'),
    ('YEZ8-XQSM-5KTR-WJB4', 'PROMO_PANDA_COLLAR'),
    ('X9CC-WPBB-D6ZW-7NT4', 'PROMO_PANDA_COLLAR'),
    ('KZPQ-YEXJ-K73F-84YE', 'PROMO_PANDA_COLLAR');

-- PROMO_DIABLO_STONE  (Diablo Stone)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('JY74-GHGW-S2PA-45Q6', 'PROMO_DIABLO_STONE'),
    ('QY6J-39Z4-Y5PZ-FSMT', 'PROMO_DIABLO_STONE'),
    ('54U3-MWPU-EUGD-7RDC', 'PROMO_DIABLO_STONE'),
    ('K753-SSEY-BBRM-TV4G', 'PROMO_DIABLO_STONE'),
    ('EEK9-R7FH-TWS4-VZB6', 'PROMO_DIABLO_STONE'),
    ('TFSF-ARTV-SEV6-RKYC', 'PROMO_DIABLO_STONE'),
    ('4XRW-X469-BDF4-MMMC', 'PROMO_DIABLO_STONE'),
    ('EU5N-G5M5-4XRR-9DTP', 'PROMO_DIABLO_STONE'),
    ('EZ9D-K5B7-NCYE-ZDNQ', 'PROMO_DIABLO_STONE'),
    ('6ZMA-3UEY-7CFG-5GWK', 'PROMO_DIABLO_STONE'),
    ('4B2G-RSTE-4845-5YF3', 'PROMO_DIABLO_STONE'),
    ('84P7-9RZE-2NHF-S4NB', 'PROMO_DIABLO_STONE'),
    ('AYTA-4DJS-RDAK-HTGZ', 'PROMO_DIABLO_STONE'),
    ('JREP-6CFC-MPKC-YQAC', 'PROMO_DIABLO_STONE'),
    ('BC4P-TXN4-VRVZ-46X4', 'PROMO_DIABLO_STONE'),
    ('3K27-7MBA-A7QW-63SH', 'PROMO_DIABLO_STONE'),
    ('P2H5-YTC3-H8AA-DEPS', 'PROMO_DIABLO_STONE'),
    ('GPJ5-2UPE-2ZPY-SBSZ', 'PROMO_DIABLO_STONE'),
    ('327T-2UA7-PDHS-ZKAQ', 'PROMO_DIABLO_STONE'),
    ('9XKC-8Y4P-CFUW-FDH3', 'PROMO_DIABLO_STONE');

-- PROMO_NETHERWHELP  (Netherwhelp's Collar)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('3QR5-D9BB-CW6D-FQSP', 'PROMO_NETHERWHELP'),
    ('QFW5-A8QF-QVPF-TZ7W', 'PROMO_NETHERWHELP'),
    ('8JHJ-ZSHJ-2NZA-Q3SG', 'PROMO_NETHERWHELP'),
    ('2ACB-JP46-ERHY-D86F', 'PROMO_NETHERWHELP'),
    ('TCKJ-DP84-G579-HZBJ', 'PROMO_NETHERWHELP'),
    ('YMTR-V7X9-CSPZ-Q684', 'PROMO_NETHERWHELP'),
    ('4E6E-MR4J-HDK6-8TZ6', 'PROMO_NETHERWHELP'),
    ('D3SQ-X7BD-BB26-X8MY', 'PROMO_NETHERWHELP'),
    ('QSCA-X9KT-AVZN-AQBE', 'PROMO_NETHERWHELP'),
    ('HCEG-N53V-WS4R-FQ9A', 'PROMO_NETHERWHELP'),
    ('SMPE-WQEX-CKYP-54YC', 'PROMO_NETHERWHELP'),
    ('ZEAT-YV9H-MAYX-EJMA', 'PROMO_NETHERWHELP'),
    ('ZWMB-TNZN-3WFK-ZC6A', 'PROMO_NETHERWHELP'),
    ('KK3Z-4Z4K-QF6V-F936', 'PROMO_NETHERWHELP'),
    ('8CM7-VYQX-Y7HS-K8Z4', 'PROMO_NETHERWHELP'),
    ('89CC-AQWF-BBQW-FHGD', 'PROMO_NETHERWHELP'),
    ('MAPM-FXSF-GCD5-9CEU', 'PROMO_NETHERWHELP'),
    ('WSKK-52EM-QA2B-SNG4', 'PROMO_NETHERWHELP'),
    ('5DPW-FBYX-TYJQ-5WJJ', 'PROMO_NETHERWHELP'),
    ('7EUK-JUGR-EUY6-562K', 'PROMO_NETHERWHELP');

-- PROMO_FROSTYS_COLLAR  (Frosty's Collar)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('N3U5-2YSW-5XVH-TC4Y', 'PROMO_FROSTYS_COLLAR'),
    ('U965-JRAP-EXCT-GWHQ', 'PROMO_FROSTYS_COLLAR'),
    ('ZZKC-ZPDG-NFRQ-AD3A', 'PROMO_FROSTYS_COLLAR'),
    ('Y4RB-GW4D-XD48-FBZ3', 'PROMO_FROSTYS_COLLAR'),
    ('BXJT-4ZKN-MVGC-PFS4', 'PROMO_FROSTYS_COLLAR'),
    ('QYHE-RV37-NDHZ-GMJE', 'PROMO_FROSTYS_COLLAR'),
    ('ND8P-8ZR2-EHTU-GZGQ', 'PROMO_FROSTYS_COLLAR'),
    ('XPS8-5MA7-JAAW-B2BH', 'PROMO_FROSTYS_COLLAR'),
    ('YZZF-932M-CXUW-ZZGG', 'PROMO_FROSTYS_COLLAR'),
    ('A94J-PZJK-XWW2-7AAB', 'PROMO_FROSTYS_COLLAR'),
    ('25RK-NUB9-CK2C-YP4Z', 'PROMO_FROSTYS_COLLAR'),
    ('YRD9-5B6R-YR9D-9WV9', 'PROMO_FROSTYS_COLLAR'),
    ('7WXY-T2AP-EAS9-C6CE', 'PROMO_FROSTYS_COLLAR'),
    ('ZJB2-J5VB-BTAV-MAEK', 'PROMO_FROSTYS_COLLAR'),
    ('H2T3-XT9N-3F4P-F2A7', 'PROMO_FROSTYS_COLLAR'),
    ('EJ8A-5HNN-ANPW-V39Q', 'PROMO_FROSTYS_COLLAR'),
    ('YWAA-H8QE-6YDW-YK2Y', 'PROMO_FROSTYS_COLLAR'),
    ('T43E-N9H2-EEBS-BYT3', 'PROMO_FROSTYS_COLLAR'),
    ('4AGD-3TY4-FSRR-4SV4', 'PROMO_FROSTYS_COLLAR'),
    ('RGBC-8S5Y-UWY9-7T6Q', 'PROMO_FROSTYS_COLLAR');

-- PROMO_WARBOT_KEY  (Warbot Ignition Key)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('CMGK-MV6W-AR3T-3PBT', 'PROMO_WARBOT_KEY'),
    ('JR7C-Y83P-PNPY-5EJT', 'PROMO_WARBOT_KEY'),
    ('3JZA-U4QD-B4ZN-XMB6', 'PROMO_WARBOT_KEY'),
    ('VE3V-HMBQ-2CJ6-QX6U', 'PROMO_WARBOT_KEY'),
    ('5TD8-H2UU-EP47-EVTB', 'PROMO_WARBOT_KEY'),
    ('PWUA-C7P2-FQ8A-YNH4', 'PROMO_WARBOT_KEY'),
    ('P823-25V5-8A4A-Z7BR', 'PROMO_WARBOT_KEY'),
    ('M8AX-HR6Z-GPHN-WBZM', 'PROMO_WARBOT_KEY'),
    ('2J2C-CP58-V8SE-836W', 'PROMO_WARBOT_KEY'),
    ('KTXE-HTNT-2Q4P-J9BA', 'PROMO_WARBOT_KEY'),
    ('Y8FA-J592-V647-SNHM', 'PROMO_WARBOT_KEY'),
    ('Q6VM-TZDG-DKRF-9DUT', 'PROMO_WARBOT_KEY'),
    ('247F-7FPR-RXSH-F998', 'PROMO_WARBOT_KEY'),
    ('HMXN-NR8N-WEWE-JXPC', 'PROMO_WARBOT_KEY'),
    ('XPSY-JZFC-68VY-CVEF', 'PROMO_WARBOT_KEY'),
    ('YPUX-Z9DY-DTX5-2Y8K', 'PROMO_WARBOT_KEY'),
    ('YM24-8JTN-SGB8-3ESG', 'PROMO_WARBOT_KEY'),
    ('NNZV-EQ93-8FHC-7AW8', 'PROMO_WARBOT_KEY'),
    ('22S5-DV4H-BFKK-FHPP', 'PROMO_WARBOT_KEY'),
    ('GYQS-WVRV-KUF5-Q3GX', 'PROMO_WARBOT_KEY');

-- PROMO_ENCHANTED_ONYX  (Enchanted Onyx)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('XMY2-UMVZ-8H3H-HBD6', 'PROMO_ENCHANTED_ONYX'),
    ('KAYH-XFNB-W6BA-RZCJ', 'PROMO_ENCHANTED_ONYX'),
    ('YFRT-PNGB-SAC3-JVPU', 'PROMO_ENCHANTED_ONYX'),
    ('GQ87-DUDJ-GNAA-FD3H', 'PROMO_ENCHANTED_ONYX'),
    ('RQCG-6PJ4-CPWU-5GDK', 'PROMO_ENCHANTED_ONYX'),
    ('H72U-TMFS-CJ7G-QJX2', 'PROMO_ENCHANTED_ONYX'),
    ('2XQY-A436-GKUA-V5AM', 'PROMO_ENCHANTED_ONYX'),
    ('2UGR-YWXQ-WGU7-BDGF', 'PROMO_ENCHANTED_ONYX'),
    ('DRBG-MR56-FBWH-FFUH', 'PROMO_ENCHANTED_ONYX'),
    ('YQRH-XZ2P-3FTR-CVR6', 'PROMO_ENCHANTED_ONYX'),
    ('HA26-U3UV-368T-NYVM', 'PROMO_ENCHANTED_ONYX'),
    ('F7SY-HSD9-FFQP-BKU4', 'PROMO_ENCHANTED_ONYX'),
    ('TU5G-YE29-T5UK-GEWD', 'PROMO_ENCHANTED_ONYX'),
    ('CH7G-CS3Z-6Y52-5AUP', 'PROMO_ENCHANTED_ONYX'),
    ('TYCH-SJG9-2GUH-XRJH', 'PROMO_ENCHANTED_ONYX'),
    ('6SR3-XJT3-FTQV-KZEC', 'PROMO_ENCHANTED_ONYX'),
    ('4MTU-TSF5-83WV-JRAX', 'PROMO_ENCHANTED_ONYX'),
    ('FGBY-4VQ4-ACC5-GKXX', 'PROMO_ENCHANTED_ONYX'),
    ('WESJ-HEPB-K7QM-2KQU', 'PROMO_ENCHANTED_ONYX'),
    ('5HG2-XR7P-T29S-MKAU', 'PROMO_ENCHANTED_ONYX');

-- PROMO_CORE_HOUND_PUP  (Core Hound Pup)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('7UP7-QZYT-MSVB-W9S2', 'PROMO_CORE_HOUND_PUP'),
    ('4WYQ-Z382-HWYN-EANP', 'PROMO_CORE_HOUND_PUP'),
    ('7GXF-83AV-Q33G-WYGN', 'PROMO_CORE_HOUND_PUP'),
    ('BB5D-2GRW-SJE3-6SKQ', 'PROMO_CORE_HOUND_PUP'),
    ('SC32-AU38-Q9DK-37V5', 'PROMO_CORE_HOUND_PUP'),
    ('9US9-7WMQ-98W7-GAER', 'PROMO_CORE_HOUND_PUP'),
    ('4MTQ-343Q-PC8W-DUGF', 'PROMO_CORE_HOUND_PUP'),
    ('BM8N-TGB9-P8AY-YHUS', 'PROMO_CORE_HOUND_PUP'),
    ('54MQ-JGHN-HR4H-EZ7V', 'PROMO_CORE_HOUND_PUP'),
    ('9A2K-273G-9DUM-RQ3U', 'PROMO_CORE_HOUND_PUP'),
    ('Z6UJ-6RJZ-VXHK-ZRN8', 'PROMO_CORE_HOUND_PUP'),
    ('MMJR-KBMP-Q4BJ-EHXX', 'PROMO_CORE_HOUND_PUP'),
    ('WZYX-YRS3-PNAM-GWN5', 'PROMO_CORE_HOUND_PUP'),
    ('R3CZ-925C-PZWC-F59J', 'PROMO_CORE_HOUND_PUP'),
    ('MA7C-DUAD-F9PT-JNE4', 'PROMO_CORE_HOUND_PUP'),
    ('Q35C-BKQS-H9RJ-645T', 'PROMO_CORE_HOUND_PUP'),
    ('FDMY-MF4S-NJHJ-99S3', 'PROMO_CORE_HOUND_PUP'),
    ('VFT6-KFWN-YY97-XGTK', 'PROMO_CORE_HOUND_PUP'),
    ('SQJ2-MQYY-M9CJ-CXZN', 'PROMO_CORE_HOUND_PUP'),
    ('X227-QK98-5YRE-AT32', 'PROMO_CORE_HOUND_PUP');

-- PROMO_GRYPHON_HATCHLING  (Gryphon Hatchling)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('UCNG-2S7G-V878-XZ57', 'PROMO_GRYPHON_HATCHLING'),
    ('5F94-3B3D-7PYP-ZSWP', 'PROMO_GRYPHON_HATCHLING'),
    ('EE7B-6VKY-7NVM-X7SV', 'PROMO_GRYPHON_HATCHLING'),
    ('P6HR-5ARP-6BA4-PP8F', 'PROMO_GRYPHON_HATCHLING'),
    ('JP3X-J5G4-CVNH-9HA2', 'PROMO_GRYPHON_HATCHLING'),
    ('Q9PV-F647-J7BF-7D4S', 'PROMO_GRYPHON_HATCHLING'),
    ('TC7X-98SF-TPMK-4927', 'PROMO_GRYPHON_HATCHLING'),
    ('VWUP-UMDS-FXE8-T936', 'PROMO_GRYPHON_HATCHLING'),
    ('CGMD-EPZ2-ZUJS-9NAD', 'PROMO_GRYPHON_HATCHLING'),
    ('67Z4-4G2D-AG5E-NF8A', 'PROMO_GRYPHON_HATCHLING'),
    ('5RSZ-V3HQ-FZET-472P', 'PROMO_GRYPHON_HATCHLING'),
    ('TQ9U-GMJ3-A5JZ-JMKW', 'PROMO_GRYPHON_HATCHLING'),
    ('APA5-BJYT-RK5N-2Z47', 'PROMO_GRYPHON_HATCHLING'),
    ('R2G7-ZA5Y-SNWP-P5Q6', 'PROMO_GRYPHON_HATCHLING'),
    ('6JQ7-3HJN-UM5W-XY8F', 'PROMO_GRYPHON_HATCHLING'),
    ('W5CG-GB94-EXKR-BV8N', 'PROMO_GRYPHON_HATCHLING'),
    ('KGHT-VNWT-9HER-3M65', 'PROMO_GRYPHON_HATCHLING'),
    ('KHXR-58JR-A7U3-XWUP', 'PROMO_GRYPHON_HATCHLING'),
    ('YP6K-F3NX-MQS9-VWDA', 'PROMO_GRYPHON_HATCHLING'),
    ('YUGZ-MWZZ-S6YB-VZ6M', 'PROMO_GRYPHON_HATCHLING');

-- PROMO_WIND_RIDER_CUB  (Wind Rider Cub)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('FKYH-WHCF-C9QG-5RSU', 'PROMO_WIND_RIDER_CUB'),
    ('KFUZ-DT3K-H97S-SW5J', 'PROMO_WIND_RIDER_CUB'),
    ('5V7P-U9DN-3WSJ-PM8S', 'PROMO_WIND_RIDER_CUB'),
    ('94CD-RHQY-65NG-A6CQ', 'PROMO_WIND_RIDER_CUB'),
    ('TKHK-58H3-CG6P-3GG7', 'PROMO_WIND_RIDER_CUB'),
    ('2FVV-BT4Z-ZZH5-CJ4X', 'PROMO_WIND_RIDER_CUB'),
    ('ZGW6-DKK6-7835-RZC3', 'PROMO_WIND_RIDER_CUB'),
    ('QHNC-EMRH-3BZG-KWPZ', 'PROMO_WIND_RIDER_CUB'),
    ('GM8P-7JAM-MM73-TDCA', 'PROMO_WIND_RIDER_CUB'),
    ('WGD3-AVU3-CPME-DKXA', 'PROMO_WIND_RIDER_CUB'),
    ('K3PG-7NB6-BKY4-JMJK', 'PROMO_WIND_RIDER_CUB'),
    ('VKCM-BMA6-WY89-53NA', 'PROMO_WIND_RIDER_CUB'),
    ('ZS5D-586Y-NHXE-Y49V', 'PROMO_WIND_RIDER_CUB'),
    ('T3JH-QMG6-5UC2-N2KH', 'PROMO_WIND_RIDER_CUB'),
    ('6W4Z-EK5H-JXPJ-Q45B', 'PROMO_WIND_RIDER_CUB'),
    ('APER-VZN8-SXMY-9SYU', 'PROMO_WIND_RIDER_CUB'),
    ('AA68-5SBU-UR2V-VFCR', 'PROMO_WIND_RIDER_CUB'),
    ('CVWV-F4PD-TH3D-2YZU', 'PROMO_WIND_RIDER_CUB'),
    ('9CXV-3DEZ-3JNX-K9KU', 'PROMO_WIND_RIDER_CUB'),
    ('SD3P-9M7D-EMVU-554D', 'PROMO_WIND_RIDER_CUB');

-- PROMO_PANDAREN_MONK  (Pandaren Monk)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('KCYP-VUFF-8QA4-AGQ5', 'PROMO_PANDAREN_MONK'),
    ('ZKR4-UE4X-KGRQ-M2KY', 'PROMO_PANDAREN_MONK'),
    ('TZ59-EXBF-BQJ9-SCYU', 'PROMO_PANDAREN_MONK'),
    ('YX35-D839-MJ6Z-A935', 'PROMO_PANDAREN_MONK'),
    ('TBH2-TRRA-8NV5-C7CK', 'PROMO_PANDAREN_MONK'),
    ('X2SE-2N29-4AHE-WMZQ', 'PROMO_PANDAREN_MONK'),
    ('ZYUT-UJDR-5XWT-GKHD', 'PROMO_PANDAREN_MONK'),
    ('76W7-2SEW-MMB6-DJVF', 'PROMO_PANDAREN_MONK'),
    ('RWPN-CM8K-56AR-9MJ5', 'PROMO_PANDAREN_MONK'),
    ('PTWM-52ZB-XRH8-KDHS', 'PROMO_PANDAREN_MONK'),
    ('JVJ5-CFUH-7P87-KS8P', 'PROMO_PANDAREN_MONK'),
    ('XJYC-WS2Z-5THT-RH6M', 'PROMO_PANDAREN_MONK'),
    ('V5WZ-SYEV-A4X9-4Y7T', 'PROMO_PANDAREN_MONK'),
    ('8GHC-MR4D-7VHX-YAWX', 'PROMO_PANDAREN_MONK'),
    ('89PH-4SV9-88HC-NBUB', 'PROMO_PANDAREN_MONK'),
    ('4XFT-AZRK-92ZC-ABYB', 'PROMO_PANDAREN_MONK'),
    ('UJT4-M6GK-CTSD-8DMQ', 'PROMO_PANDAREN_MONK'),
    ('9RD3-3XCV-62ZV-END4', 'PROMO_PANDAREN_MONK'),
    ('RA78-MNRP-42KN-Y2EG', 'PROMO_PANDAREN_MONK'),
    ('VF99-WZZ2-WJX3-5QA6', 'PROMO_PANDAREN_MONK');

-- WWI_TYRAELS_HILT  (Tyrael's Hilt)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('B3T9-5G4H-MMYH-FMHX', 'WWI_TYRAELS_HILT'),
    ('4STH-HTG9-YCT9-KZTC', 'WWI_TYRAELS_HILT'),
    ('GGGM-PTG9-YMC9-8SAW', 'WWI_TYRAELS_HILT'),
    ('9F4J-7TRV-RKAT-UQUT', 'WWI_TYRAELS_HILT'),
    ('8ZH6-WMFS-FMKF-ES9Q', 'WWI_TYRAELS_HILT'),
    ('C5V5-6N5Y-VGDK-JCE2', 'WWI_TYRAELS_HILT'),
    ('Y8QY-83ZM-W94N-X985', 'WWI_TYRAELS_HILT'),
    ('9KEA-FB82-XKYP-TKB4', 'WWI_TYRAELS_HILT'),
    ('Z53M-YYFD-8UFZ-DVSH', 'WWI_TYRAELS_HILT'),
    ('MUB7-UMNV-K99Y-G7RS', 'WWI_TYRAELS_HILT'),
    ('BJJU-ZP65-GSJJ-Q8QM', 'WWI_TYRAELS_HILT'),
    ('MDSA-FKFD-V5ST-5QHQ', 'WWI_TYRAELS_HILT'),
    ('5TWP-A73U-X2VR-UD67', 'WWI_TYRAELS_HILT'),
    ('PEWF-6AEP-FN3N-PMYD', 'WWI_TYRAELS_HILT'),
    ('UK5H-7A25-EPZ7-HAFA', 'WWI_TYRAELS_HILT'),
    ('3K47-YQUS-W6F3-H2DC', 'WWI_TYRAELS_HILT'),
    ('VEYT-G68X-KCKG-8CPB', 'WWI_TYRAELS_HILT'),
    ('NQVG-9GFW-B92N-KGS3', 'WWI_TYRAELS_HILT'),
    ('CR5B-NDCR-V2XA-ETGD', 'WWI_TYRAELS_HILT'),
    ('DNPJ-7TCK-Y593-74W4', 'WWI_TYRAELS_HILT');

-- PROMO_LIL_PHYLACTERY  (Lil' Phylactery)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('3AVD-RABY-HPZ3-5BEB', 'PROMO_LIL_PHYLACTERY'),
    ('MZ7K-NVVX-Y5ET-J9AR', 'PROMO_LIL_PHYLACTERY'),
    ('2PR6-YNAR-YAYF-24Q2', 'PROMO_LIL_PHYLACTERY'),
    ('ZDV7-2B9T-NJ5R-D94X', 'PROMO_LIL_PHYLACTERY'),
    ('AG75-EZMK-KDCD-AAGJ', 'PROMO_LIL_PHYLACTERY'),
    ('DHP3-MKHE-VWTQ-AG4C', 'PROMO_LIL_PHYLACTERY'),
    ('YVYH-JFT8-93KZ-4Y9S', 'PROMO_LIL_PHYLACTERY'),
    ('SVUH-5HFU-4U43-6ZNX', 'PROMO_LIL_PHYLACTERY'),
    ('KVCT-PYF9-VWAX-NAG7', 'PROMO_LIL_PHYLACTERY'),
    ('P2D4-ZBFP-SM6B-369M', 'PROMO_LIL_PHYLACTERY'),
    ('AM85-GY9E-HPN8-NWUY', 'PROMO_LIL_PHYLACTERY'),
    ('AD83-NB6S-ZSAZ-G5HG', 'PROMO_LIL_PHYLACTERY'),
    ('49CD-JUT7-PM4Z-MCEJ', 'PROMO_LIL_PHYLACTERY'),
    ('GMKD-5D9H-M3A9-F2KS', 'PROMO_LIL_PHYLACTERY'),
    ('5EBQ-2WF9-2UNT-NEHA', 'PROMO_LIL_PHYLACTERY'),
    ('452J-5HXH-GS6Y-HWEG', 'PROMO_LIL_PHYLACTERY'),
    ('FGJV-987P-V3E8-JGG7', 'PROMO_LIL_PHYLACTERY'),
    ('BJ47-B7XY-Y4GX-KHNR', 'PROMO_LIL_PHYLACTERY'),
    ('9UPV-HM86-HNHG-RU33', 'PROMO_LIL_PHYLACTERY'),
    ('2NP2-DCB5-MZT4-ARST', 'PROMO_LIL_PHYLACTERY');

-- PROMO_LIL_XT  (Lil' XT)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('HZZE-SETU-78C8-WVXF', 'PROMO_LIL_XT'),
    ('GBH3-C25B-3WGR-JQAG', 'PROMO_LIL_XT'),
    ('9UKD-YR2H-69GG-4NS9', 'PROMO_LIL_XT'),
    ('UKB2-ZWVN-8CUN-6YMF', 'PROMO_LIL_XT'),
    ('F98M-99ZS-TDSE-EA2E', 'PROMO_LIL_XT'),
    ('ARJK-M8ZA-KHZ4-UAKF', 'PROMO_LIL_XT'),
    ('WHN9-FN6Q-8G88-SW3B', 'PROMO_LIL_XT'),
    ('N9SA-85ZJ-K795-DRH7', 'PROMO_LIL_XT'),
    ('3XEJ-UWW9-7SWQ-UEK3', 'PROMO_LIL_XT'),
    ('R99Q-8PA6-YR7Z-6MAS', 'PROMO_LIL_XT'),
    ('XB6J-Y5TM-5Y8R-XUQG', 'PROMO_LIL_XT'),
    ('QQHS-U92M-PZR8-4K6F', 'PROMO_LIL_XT'),
    ('BJTW-3AJZ-KJ5Z-AZ6E', 'PROMO_LIL_XT'),
    ('2ABJ-YEC3-H2DE-PZQM', 'PROMO_LIL_XT'),
    ('SHVA-DUYW-WGVE-BWCC', 'PROMO_LIL_XT'),
    ('VYBE-7KSY-8MDB-X9YQ', 'PROMO_LIL_XT'),
    ('3UYU-8JM8-AWJH-RRGN', 'PROMO_LIL_XT'),
    ('RUN4-P2FD-AQVM-STBE', 'PROMO_LIL_XT'),
    ('GHH2-PEUE-MT65-APDJ', 'PROMO_LIL_XT'),
    ('KZMY-SWAS-3EAW-HKQ9', 'PROMO_LIL_XT');

-- PROMO_MINI_THOR  (Mini Thor)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('XMM3-P9WE-4AR7-2J52', 'PROMO_MINI_THOR'),
    ('P66M-M8EV-UG7S-8EHG', 'PROMO_MINI_THOR'),
    ('XHNX-99Z2-JGR9-GQGK', 'PROMO_MINI_THOR'),
    ('E42K-H4JZ-N4Y3-U95Y', 'PROMO_MINI_THOR'),
    ('DRFB-NGHP-RTX2-QHB8', 'PROMO_MINI_THOR'),
    ('4ZCK-2SJZ-AJF5-MHUH', 'PROMO_MINI_THOR'),
    ('BGXH-XAAA-3RWG-PZUN', 'PROMO_MINI_THOR'),
    ('R7SK-8PCN-3FVN-YER2', 'PROMO_MINI_THOR'),
    ('2F37-92R5-P44A-2BSJ', 'PROMO_MINI_THOR'),
    ('HYBF-225Z-6ZFQ-SR78', 'PROMO_MINI_THOR'),
    ('EJAB-QB76-42YY-2KEQ', 'PROMO_MINI_THOR'),
    ('3UXC-3S8T-DVSW-Z8CZ', 'PROMO_MINI_THOR'),
    ('H4HN-RDR3-QR78-NX6M', 'PROMO_MINI_THOR'),
    ('WGRV-QGJQ-MH3G-JGXD', 'PROMO_MINI_THOR'),
    ('ZBW8-ZRYE-WMXW-WYQ8', 'PROMO_MINI_THOR'),
    ('PG82-R2HQ-ADD8-DCZX', 'PROMO_MINI_THOR'),
    ('QRNM-P8W5-QCBY-AK4F', 'PROMO_MINI_THOR'),
    ('UXGT-335R-PR3V-9GTW', 'PROMO_MINI_THOR'),
    ('TKRK-UU3N-KGET-NWGX', 'PROMO_MINI_THOR'),
    ('5HK8-7HF5-YX55-F6WQ', 'PROMO_MINI_THOR');

-- PROMO_ONYXIAN_WHELPLING  (Onyxian Whelpling)
-- Generated: 2026-10-03 09:06:39 UTC  |  Count: 20
INSERT IGNORE INTO `account_tcg_codes` (`code`, `reward_group`) VALUES
    ('HDXX-BS5Y-CZ4A-KJ2A', 'PROMO_ONYXIAN_WHELPLING'),
    ('JSYR-DJJ6-SPGS-GYAK', 'PROMO_ONYXIAN_WHELPLING'),
    ('YEZ7-K92Q-QZXK-VSYY', 'PROMO_ONYXIAN_WHELPLING'),
    ('488B-4NCS-PM2U-NJ4Y', 'PROMO_ONYXIAN_WHELPLING'),
    ('Z4QG-XSVG-Z888-8TR3', 'PROMO_ONYXIAN_WHELPLING'),
    ('XK43-APGQ-FPN8-R9RD', 'PROMO_ONYXIAN_WHELPLING'),
    ('KR9J-2XA6-DRJF-W73T', 'PROMO_ONYXIAN_WHELPLING'),
    ('82YP-KF59-ZQTJ-UP3C', 'PROMO_ONYXIAN_WHELPLING'),
    ('TSDT-482R-UVEZ-AFZH', 'PROMO_ONYXIAN_WHELPLING'),
    ('MBGQ-T4BZ-TH6H-2Q22', 'PROMO_ONYXIAN_WHELPLING'),
    ('7RFY-CA2H-QP9U-V6PY', 'PROMO_ONYXIAN_WHELPLING'),
    ('J9EU-AQG3-F99A-D7GB', 'PROMO_ONYXIAN_WHELPLING'),
    ('GEXM-E3BD-CT98-W8B9', 'PROMO_ONYXIAN_WHELPLING'),
    ('TV5B-Z655-YDUU-8TE5', 'PROMO_ONYXIAN_WHELPLING'),
    ('VG82-R6EZ-ASHA-4WQX', 'PROMO_ONYXIAN_WHELPLING'),
    ('DC8A-SE62-TBKW-QPP2', 'PROMO_ONYXIAN_WHELPLING'),
    ('3HWK-RC5R-H2F3-PMYM', 'PROMO_ONYXIAN_WHELPLING'),
    ('K28C-QPET-UPYE-SY5X', 'PROMO_ONYXIAN_WHELPLING'),
    ('UZUC-DYW3-DWWH-56HE', 'PROMO_ONYXIAN_WHELPLING'),
    ('P78K-TW2M-MAEN-9GG2', 'PROMO_ONYXIAN_WHELPLING');
